using System.Linq;
using Content.Client._RMC14.LinkAccount;
using Content.Client.Options.UI;
using Content.Client.UserInterface.Screens;
using Content.Shared._RMC14.CCVar;
using Content.Shared._RMC14.NightVision;
using Content.Shared.CCVar;
using Content.Shared.HUD;
using Content.Shared.Localizations;
using Robust.Client;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MiscTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly LinkAccountManager _linkAccount = default!;
    [Dependency] private readonly IGameController _gameController = default!;
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly ContentLocalizationManager _contentLoc = default!;

    private OptionDropDownCVar<string>? _clientLanguageOption;
    private LanguageRestartConfirmWindow? _languageRestartWindow;
    private bool _ignoreLanguageSelection;
    private string? _pendingLanguageCode;
    private string? _pendingPreviousLanguageCode;
    private ISawmill _sawmill = default!;
    private const int LobbyBackgroundPresetConsoleId = 0;
    private const int LobbyBackgroundPresetCommunityId = 1;
    private const int LobbyBackgroundPresetRmcaId = 2;

    public MiscTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("language-restart");

        var themes = _prototypeManager.EnumeratePrototypes<HudThemePrototype>().ToList();
        themes.Sort();
        var themeEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var gear in themes)
        {
            themeEntries.Add(new OptionDropDownCVar<string>.ValueOption(gear.ID, Loc.GetString(gear.Name)));
        }

        var layoutEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var layout in Enum.GetValues(typeof(ScreenType)))
        {
            layoutEntries.Add(new OptionDropDownCVar<string>.ValueOption(layout.ToString()!, Loc.GetString($"ui-options-hud-layout-{layout.ToString()!.ToLower()}")));
        }

        var languageEntries = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new("ru-RU", Loc.GetString("ui-options-language-russian")),
            new("en-US", Loc.GetString("ui-options-language-english")),
        };

        var colorThemeEntries = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new("green", Loc.GetString("ui-options-ui-color-theme-green")),
            new("gray", Loc.GetString("ui-options-ui-color-theme-gray")),
        };

        NormalizeChatTranslationTarget();

        var chatTranslationLanguageEntries = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new("ru", Loc.GetString("ui-options-language-russian")),
            new("en", Loc.GetString("ui-options-language-english")),
        };

        var lobbyBackgroundPresetEntries = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new("console", Loc.GetString("ui-options-lobby-background-preset-console")),
            new("community", Loc.GetString("ui-options-lobby-background-preset-community")),
            new("rmca", Loc.GetString("ui-options-lobby-background-preset-rmca")),
        };

        var lobbyUiStyleEntries = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new("new", Loc.GetString("ui-options-lobby-ui-style-new")),
            new("old", Loc.GetString("ui-options-lobby-ui-style-old")),
        };

        var xenoNightVisionEntries = new List<OptionDropDownCVar<int>.ValueOption>
        {
            new((int) NightVisionState.Off, Loc.GetString("rmc-ui-xeno-night-vision-default-off")),
            new((int) NightVisionState.Half, Loc.GetString("rmc-ui-xeno-night-vision-default-half")),
            new((int) NightVisionState.Full, Loc.GetString("rmc-ui-xeno-night-vision-default-full")),
        };

        // Channel can be null in replays so.
        // ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
        ShowOocPatronColor.Visible = _linkAccount.Tier != null;

        _clientLanguageOption = Control.AddOptionDropDown(CCVars.ClientLocale, DropDownClientLanguage, languageEntries);
        _clientLanguageOption.ImmediateValueChanged += OnClientLanguageChanged;
        Control.AddOptionDropDown(CVars.InterfaceTheme, DropDownHudTheme, themeEntries);
        Control.AddOptionDropDown(RMCCVars.RMCUIColorTheme, DropDownUiColorTheme, colorThemeEntries);
        Control.AddOptionDropDown(RMCCVars.RMCLobbyUiStyle, DropDownLobbyUiStyle, lobbyUiStyleEntries);
        Control.AddOptionDropDown(RMCCVars.RMCLobbyBackgroundPreset, DropDownLobbyBackgroundPreset, lobbyBackgroundPresetEntries);
        Control.AddOptionDropDown(CCVars.UILayout, DropDownHudLayout, layoutEntries);

        Control.AddOptionCheckBox(CVars.DiscordEnabled, DiscordRich);
        Control.AddOptionCheckBox(CCVars.ShowOocPatronColor, ShowOocPatronColor);
        Control.AddOptionCheckBox(CCVars.LoocAboveHeadShow, ShowLoocAboveHeadCheckBox);
        Control.AddOptionCheckBox(CCVars.HudHeldItemShow, ShowHeldItemCheckBox);
        Control.AddOptionCheckBox(CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsCheckBox);
        Control.AddOptionCheckBox(CCVars.OpaqueStorageWindow, OpaqueStorageWindowCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatEnableFancyBubbles, FancySpeechBubblesCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatFancyNameBackground, FancyNameBackgroundsCheckBox);
        Control.AddOptionCheckBox(CCVars.StaticStorageUI, StaticStorageUI);
        Control.AddOptionCheckBox(RMCCVars.RMCChatTranslateEnabled, ChatTranslationEnabledCheckBox);
        Control.AddOptionDropDown(RMCCVars.RMCChatTranslateTarget, DropDownChatTranslationLanguage, chatTranslationLanguageEntries);

        Control.AddOptionCheckBox(RMCCVars.RMCAutoPunctuate, RMCAutoPunctuate);
        Control.AddOptionCheckBox(RMCCVars.RMCAutoEjectMagazines, RMCAutoEjectMagazines);
        Control.AddOptionCheckBox(RMCCVars.RMCDamageYourself, RMCDamageYourself);
        Control.AddOptionCheckBox(RMCCVars.RMCShowNewPlayerIcons, RMCShowNewPlayerIcons);
        Control.AddOptionDropDown(RMCCVars.RMCXenoDefaultNightVision, RMCXenoNightVisionDefault, xenoNightVisionEntries);

        Control.Initialize();
        _cfg.OnValueChanged(RMCCVars.RMCLobbyUiStyle, RefreshLobbyBackgroundPresetOptions, true);
    }

    private void RefreshLobbyBackgroundPresetOptions(string style)
    {
        var oldStyle = string.Equals(style, "old", StringComparison.OrdinalIgnoreCase);
        var currentPreset = _cfg.GetCVar(RMCCVars.RMCLobbyBackgroundPreset) ?? "community";
        if (oldStyle && string.Equals(currentPreset, "console", StringComparison.OrdinalIgnoreCase))
        {
            currentPreset = "rmca";
            _cfg.SetCVar(RMCCVars.RMCLobbyBackgroundPreset, currentPreset);
        }

        var button = DropDownLobbyBackgroundPreset.Button;
        button.Clear();

        if (!oldStyle)
            AddLobbyBackgroundPresetItem(button, LobbyBackgroundPresetConsoleId, "console", Loc.GetString("ui-options-lobby-background-preset-console"));

        AddLobbyBackgroundPresetItem(button, LobbyBackgroundPresetCommunityId, "community", Loc.GetString("ui-options-lobby-background-preset-community"));
        AddLobbyBackgroundPresetItem(button, LobbyBackgroundPresetRmcaId, "rmca", Loc.GetString("ui-options-lobby-background-preset-rmca"));

        var selectedId = currentPreset.ToLowerInvariant() switch
        {
            "community" => LobbyBackgroundPresetCommunityId,
            "rmca" => LobbyBackgroundPresetRmcaId,
            _ => LobbyBackgroundPresetConsoleId,
        };

        if (!oldStyle || selectedId != LobbyBackgroundPresetConsoleId)
            button.SelectId(selectedId);

        Control.ValueChanged();
    }

    private static void AddLobbyBackgroundPresetItem(OptionButton button, int id, string key, string label)
    {
        button.AddItem(label, id);
        button.SetItemMetadata(button.GetIdx(id), key);
    }

    private void NormalizeChatTranslationTarget()
    {
        var current = _cfg.GetCVar(RMCCVars.RMCChatTranslateTarget);
        if (!string.Equals(current, "off", StringComparison.OrdinalIgnoreCase))
            return;

        var clientLocale = _cfg.GetCVar(CCVars.ClientLocale);
        var normalized = string.Equals(clientLocale, "ru-RU", StringComparison.OrdinalIgnoreCase)
            ? "ru"
            : "en";

        _cfg.SetCVar(RMCCVars.RMCChatTranslateTarget, normalized);
    }

    // CCM rework lobby - start
    private void OnClientLanguageChanged(string languageCode)
    {
        if (_ignoreLanguageSelection)
            return;

        var currentLanguage = _cfg.GetCVar(CCVars.ClientLocale);
        if (string.Equals(languageCode, currentLanguage, StringComparison.OrdinalIgnoreCase))
            return;

        _pendingLanguageCode = languageCode;
        _pendingPreviousLanguageCode = currentLanguage;
        OpenLanguageRestartConfirm();
    }

    private void OpenLanguageRestartConfirm()
    {
        if (_languageRestartWindow is { Disposed: false, IsOpen: true })
        {
            _languageRestartWindow.MoveToFront();
            return;
        }

        _languageRestartWindow?.Dispose();
        _languageRestartWindow = new LanguageRestartConfirmWindow();
        _languageRestartWindow.Confirmed += ConfirmLanguageRestart;
        _languageRestartWindow.Cancelled += CancelLanguageRestart;
        _languageRestartWindow.OpenCentered();
        _languageRestartWindow.MoveToFront();
    }

    private void ConfirmLanguageRestart()
    {
        if (string.IsNullOrWhiteSpace(_pendingLanguageCode))
            return;

        var language = _pendingLanguageCode;
        _pendingLanguageCode = null;
        _pendingPreviousLanguageCode = null;

        _cfg.SetCVar(CCVars.ClientLocale, language);
        _contentLoc.SetCulture(language);
        _cfg.SaveToFile();
        Control.ValueChanged();

        if (!RestartClientProcess())
        {
            _sawmill.Error("Language changed and saved, but automatic restart failed.");
        }
    }

    private void CancelLanguageRestart()
    {
        _pendingLanguageCode = null;
        var language = _pendingPreviousLanguageCode ?? _cfg.GetCVar(CCVars.ClientLocale);
        _pendingPreviousLanguageCode = null;
        SelectLanguageDropdown(language);
    }

    private void SelectLanguageDropdown(string languageCode)
    {
        _ignoreLanguageSelection = true;
        try
        {
            for (var i = 0; i < DropDownClientLanguage.Button.ItemCount; i++)
            {
                if (DropDownClientLanguage.Button.GetItemMetadata(i) is string metadata &&
                    string.Equals(metadata, languageCode, StringComparison.OrdinalIgnoreCase))
                {
                    DropDownClientLanguage.Button.Select(i);
                    break;
                }
            }
        }
        finally
        {
            _ignoreLanguageSelection = false;
        }

        Control.ValueChanged();
    }

    private bool RestartClientProcess()
    {
        // In client content sandbox we cannot spawn OS processes directly.
        // Restart via launcher redial API when available.
        var address = BuildRedialAddress();

        if (string.IsNullOrWhiteSpace(address))
            return false;

        try
        {
            _gameController.Redial(address, "Language restart requested");
            return true;
        }
        catch (Exception e)
        {
            _sawmill.Error($"Failed to restart via launcher redial: {e}");
            return false;
        }
    }

    private string? BuildRedialAddress()
    {
        var launchState = _gameController.LaunchState;

        if (!string.IsNullOrWhiteSpace(launchState.Ss14Address))
            return NormalizeSs14Address(launchState.Ss14Address);

        if (string.IsNullOrWhiteSpace(launchState.ConnectAddress))
            return null;

        var address = launchState.ConnectAddress.Trim();
        if (address.StartsWith("ss14://", StringComparison.OrdinalIgnoreCase))
            return NormalizeSs14Address(address);

        if (address.StartsWith("udp://", StringComparison.OrdinalIgnoreCase))
            address = address["udp://".Length..];

        address = address.TrimStart('/');
        return NormalizeSs14Address($"ss14://{address}");
    }

    private static string NormalizeSs14Address(string address)
    {
        var normalized = address.Trim();
        if (!normalized.EndsWith('/'))
            normalized += "/";

        return normalized;
    }
    // CCM rework lobby - end
}
