// CM14 rework: non-RMC edit marker.
using System;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Voting.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VotePopup : Control
    {
        [Dependency] private readonly IGameTiming _gameTiming = default!;
        [Dependency] private readonly IVoteManager _voteManager = default!;
        [Dependency] private readonly IEntityNetworkManager _net = default!;

        private readonly VoteManager.ActiveVote _vote;
        private readonly Button[] _voteButtons;
        private readonly NetEntity? _targetEntity;
        private bool _popupWidthLocked;

        public VotePopup(VoteManager.ActiveVote vote)
        {
            _vote = vote;
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetNano;

            if (_vote.TargetEntity != null && _vote.TargetEntity != 0)
            {
                _targetEntity = new NetEntity(_vote.TargetEntity.Value);
                FollowVoteTarget.OnPressed += _ => AttemptFollowVoteEntity();
                FollowVoteTarget.Visible = true;
            }

            Modulate = Color.White;
            // CCM vote popup layout rework: add explicit close button for the compact popup layout.
            HideButton.OnPressed += _ => Visible = false;

            _voteButtons = new Button[vote.Entries.Length];
            var group = new ButtonGroup();

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var button = new Button
                {
                    ToggleMode = true,
                    Group = group,
                    HorizontalExpand = true,
                    MinSize = new Vector2(118f, 28f),
                };
                button.AddStyleClass(StyleBase.StyleClassVoteButton);
                _voteButtons[i] = button;
                VoteOptionsContainer.AddChild(button);
                var i1 = i;
                button.OnPressed += _ => _voteManager.SendCastVote(vote.Id, i1);
            }
        }

        public void UpdateData()
        {
            VoteTitle.SetMessage(FormattedMessage.FromUnformatted(LocalizeVoteText(_vote.Title)));
            VoteCaller.Text = Loc.GetString("ui-vote-created", ("initiator", LocalizeVoteText(_vote.Initiator)));

            var longestEntryLength = 0;

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var entry = _vote.Entries[i];
                var entryText = LocalizeVoteText(entry.Text);
                longestEntryLength = Math.Max(longestEntryLength, entryText.Length);
                if (_vote.DisplayVotes)
                {
                    _voteButtons[i].Text = Loc.GetString("ui-vote-button", ("text", entryText), ("votes", entry.Votes));
                }
                else
                {
                    _voteButtons[i].Text = Loc.GetString("ui-vote-button-no-votes", ("text", entryText));
                }

                if (_vote.OurVote == i)
                    _voteButtons[i].Pressed = true;
            }

            var columns = CalculateColumnCount(_voteButtons.Length, longestEntryLength);
            VoteOptionsContainer.Columns = columns;

            var minButtonWidth = columns switch
            {
                1 => longestEntryLength >= 34 ? 760f : 680f,
                2 => longestEntryLength >= 24 ? 320f : 280f,
                _ => longestEntryLength >= 16 ? 240f : 210f,
            };

            var minPopupWidth = columns switch
            {
                1 => minButtonWidth + 40f,
                2 => minButtonWidth * 2f + 52f,
                _ => minButtonWidth * 3f + 64f,
            };

            foreach (var button in _voteButtons)
            {
                button.MinWidth = minButtonWidth;
                button.MaxWidth = float.MaxValue;
            }

            MinWidth = minPopupWidth;
            MaxWidth = 1500f;
            _popupWidthLocked = false;
        }

        private static int CalculateColumnCount(int buttonCount, int longestEntryLength)
        {
            if (buttonCount <= 1)
                return 1;

            if (longestEntryLength >= 40)
                return 1;

            if (longestEntryLength >= 22 || buttonCount <= 4)
                return Math.Min(2, buttonCount);

            return Math.Min(3, buttonCount);
        }

        private void AttemptFollowVoteEntity()
        {
            if (_targetEntity != null)
            {
                var msg = new GhostWarpToTargetRequestEvent(_targetEntity.Value);
                _net.SendSystemNetworkMessage(msg);
            }
        }

        private static string LocalizeVoteText(string text)
        {
            return Loc.TryGetString(text, out var localized)
                ? localized
                : text;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            if (!_popupWidthLocked && Size.X > 1f)
            {
                MinWidth = Size.X;
                MaxWidth = Size.X;
                _popupWidthLocked = true;
            }

            // Logger.Debug($"{_gameTiming.ServerTime}, {_vote.StartTime}, {_vote.EndTime}");

            var curTime = _gameTiming.RealTime;
            var timeLeft = _vote.EndTime - curTime;
            if (timeLeft < TimeSpan.Zero)
                timeLeft = TimeSpan.Zero;

            // Round up a second.
            timeLeft = TimeSpan.FromSeconds(Math.Ceiling(timeLeft.TotalSeconds));

            TimeLeftBar.Value = Math.Min(1, (float) ((curTime.TotalSeconds - _vote.StartTime.TotalSeconds) /
                                                     (_vote.EndTime.TotalSeconds - _vote.StartTime.TotalSeconds)));

            TimeLeftText.Text = $"{timeLeft:m\\:ss}";
        }
    }
}
