// CM14 rework: non-RMC edit marker.
using Content.Client.Stylesheets;
using Content.Client.Resources;
using Content.Shared._RMC14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;
using Robust.Shared.Timing;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client.Launcher
{
    [GenerateTypedNameReferences]
    public sealed partial class LauncherConnectingGui : Control
    {
        private const float RedialWaitTimeSeconds = 15f;
        private readonly LauncherConnecting _state;
        private float _waitTime;

        // Pressing reconnect will redial instead of simply reconnecting.
        private bool _redial;

        private readonly IClipboardManager _clipboard;
        private readonly IResourceCache _cache;
        private readonly IConfigurationManager _config;

        public LauncherConnectingGui(LauncherConnecting state, IRobustRandom random,
            IPrototypeManager prototype, IConfigurationManager config, IClipboardManager clipboard)
        {
            _state = state;
            _clipboard = clipboard;
            _cache = IoCManager.Resolve<IResourceCache>();
            _config = config;
            _ = random;
            _ = prototype;

            RobustXamlLoader.Load(this);

            LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetSpace;

            RetryButton.OnPressed += ReconnectButtonPressed;
            ReconnectButton.OnPressed += ReconnectButtonPressed;

            CopyButton.OnPressed += CopyButtonPressed;
            CopyButtonDisconnected.OnPressed += CopyButtonDisconnectedPressed;
            ExitButton.OnPressed += _ => _state.Exit();

            var addr = state.Address;
            if (addr != null)
                ConnectingAddress.Text = addr;

            state.PageChanged += OnPageChanged;
            state.ConnectFailReasonChanged += ConnectFailReasonChanged;
            state.ConnectionStateChanged += ConnectionStateChanged;
            state.ConnectFailed += HandleDisconnectReason;

            ConnectionStateChanged(state.ConnectionState);
            config.OnValueChanged(RMCCVars.RMCUIColorTheme, ApplyThemeToFrame, true);
            config.OnValueChanged(RMCCVars.RMCLobbyUiStyle, _ => ApplyThemeToFrame(string.Empty), false);

            // Redial flag setup
            var edim = IoCManager.Resolve<ExtendedDisconnectInformationManager>();
            edim.LastNetDisconnectedArgsChanged += LastNetDisconnectedArgsChanged;
            LastNetDisconnectedArgsChanged(edim.LastNetDisconnectedArgs);
        }

        // Just button, there's only one at once anyways :)
        private void ReconnectButtonPressed(BaseButton.ButtonEventArgs args)
        {
            if (_redial)
            {
                // Redial shouldn't fail, but if it does, try a reconnect (maybe we're being run from debug)
                if (_state.Redial())
                    return;
            }

            _state.RetryConnect();
        }

        private void CopyButtonPressed(BaseButton.ButtonEventArgs args)
        {
            CopyText(ConnectFailReason.Text);
        }

        private void CopyButtonDisconnectedPressed(BaseButton.ButtonEventArgs args)
        {
            CopyText(DisconnectReason.Text);
        }

        private void CopyText(string? text)
        {
            if (!string.IsNullOrEmpty(text))
            {
                _clipboard.SetText(text);
            }
        }

        private void ConnectFailReasonChanged(string? reason)
        {
            ConnectFailReason.SetMessage(reason == null
                ? ""
                : Loc.GetString("connecting-fail-reason", ("reason", reason)));
        }

        private void LastNetDisconnectedArgsChanged(NetDisconnectedArgs? args)
        {
            HandleDisconnectReason(args);
        }

        private void HandleDisconnectReason(INetStructuredReason? reason)
        {
            if (reason == null)
            {
                _waitTime = 0;
                _redial = false;
            }
            else
            {
                _redial = reason.RedialFlag;

                if (reason.Message.Int32Of("delay") is { } delay)
                {
                    _waitTime = delay;
                }
                else if (_redial)
                {
                    _waitTime = RedialWaitTimeSeconds;
                }

            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            var button = _state.CurrentPage == LauncherConnecting.Page.ConnectFailed
                ? RetryButton
                : ReconnectButton;

            _waitTime -= args.DeltaSeconds;
            if (_waitTime <= 0)
            {
                button.Disabled = false;
                var key = _redial
                    ? "connecting-redial"
                    : _state.CurrentPage == LauncherConnecting.Page.ConnectFailed
                        ? "connecting-reconnect"
                        : "connecting-retry";

                button.Text = Loc.GetString(key);
            }
            else
            {
                button.Disabled = true;
                button.Text = Loc.GetString("connecting-redial-wait", ("time", _waitTime.ToString("00.000")));
            }
        }

        private void OnPageChanged(LauncherConnecting.Page page)
        {
            ConnectingStatus.Visible = page == LauncherConnecting.Page.Connecting;
            ConnectFail.Visible = page == LauncherConnecting.Page.ConnectFailed;
            Disconnected.Visible = page == LauncherConnecting.Page.Disconnected;

            if (page == LauncherConnecting.Page.Disconnected)
                DisconnectReason.Text = _state.LastDisconnectReason;
        }

        private void ConnectionStateChanged(ClientConnectionState state)
        {
            ConnectStatus.Text = Loc.GetString($"connecting-state-{state}");
        }

        private void ApplyThemeToFrame(string theme)
        {
            var effectiveTheme = StyleNano.GetConfiguredTheme(_config);

            Color ThemeColor(Color blue, Color gray, Color green) => effectiveTheme switch
            {
                StyleNano.UiColorTheme.Gray => gray,
                _ => green,
            };

            var titleFont = _cache.GetFont("/Fonts/Exo2/Exo2-Bold.ttf", 22);
            var disconnectedTitleFont = _cache.GetFont("/Fonts/Exo2/Exo2-Bold.ttf", 18);
            var titleColor = ThemeColor(
                Color.FromHex("#ECF6FF"),
                Color.FromHex("#E7EDF3"),
                Color.FromHex("#E8F3EA"));
            var bodyColor = ThemeColor(
                Color.FromHex("#D8EAFB"),
                Color.FromHex("#D5DDE5"),
                Color.FromHex("#D4E7D8"));
            var background = ThemeColor(
                Color.FromHex("#121D2B"),
                Color.FromHex("#181D23"),
                Color.FromHex("#152019")).WithAlpha(0.985f);
            var border = ThemeColor(
                Color.FromHex("#76BCEC"),
                Color.FromHex("#7F8B9A"),
                Color.FromHex("#72B181")).WithAlpha(0.94f);
            var divider = ThemeColor(
                Color.FromHex("#5A81AB"),
                Color.FromHex("#586472"),
                Color.FromHex("#4F7059")).WithAlpha(0.88f);
            var cardBackground = ThemeColor(
                Color.FromHex("#1B2A3D"),
                Color.FromHex("#232A33"),
                Color.FromHex("#202F26")).WithAlpha(0.98f);
            var cardBorder = ThemeColor(
                Color.FromHex("#8CC7F2"),
                Color.FromHex("#8994A0"),
                Color.FromHex("#88BE94")).WithAlpha(0.60f);
            var addressBackground = ThemeColor(
                Color.FromHex("#172435"),
                Color.FromHex("#1E242D"),
                Color.FromHex("#1A281F")).WithAlpha(0.96f);

            FramePanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = background,
                BorderThickness = new Thickness(1),
                BorderColor = border
            };

            HeaderDivider.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = divider,
                ContentMarginLeftOverride = 2,
                ContentMarginBottomOverride = 1
            };

            ConnectFailCard.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = cardBackground,
                BorderThickness = new Thickness(1),
                BorderColor = cardBorder
            };

            DisconnectedCard.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = cardBackground,
                BorderThickness = new Thickness(1),
                BorderColor = cardBorder
            };

            AddressCard.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = addressBackground,
                BorderThickness = new Thickness(1),
                BorderColor = cardBorder.WithAlpha(0.55f)
            };

            ConnectFailHeader.Text = Loc.GetString("connecting-fail-header");
            ConnectFailHeader.FontOverride = titleFont;
            ConnectFailHeader.FontColorOverride = titleColor;
            DisconnectedHeader.FontOverride = disconnectedTitleFont;
            DisconnectedHeader.FontColorOverride = titleColor;
            DisconnectReason.FontColorOverride = bodyColor;
            ConnectingAddress.FontColorOverride = bodyColor;
            ConnectStatus.FontColorOverride = bodyColor;
        }
    }
}
