"Спрайты":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Карты":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

"UI":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"Шейдеры":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"Аудио":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"C#":
- changed-files:
  - all-glob-to-any-files: "**/*.cs"

"Локализация":
- changed-files:
  - all-glob-to-any-file: "**/*.ftl"

"Прототипы":
- changed-files:
  - all-glob-to-any-file: "**/*.yml"

"Гайбдук":
- changed-files:
  - all-glob-to-any-file: "Resources/ServerInfo/**/*.xml"

"Сервер":
- changed-files:
  - all-glob-to-any-file: "Resources/ConfigPresets/**/*.toml"
