using System.Linq;
﻿// CM14 rework: non-RMC edit marker.
using Content.Client._RMC14.Chat;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Chat.Controls;
using Content.Shared._MC;
using Content.Shared.Audio;
using Content.Shared.Chat;
using Content.Shared.Input;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.UserInterface.Systems.Chat.Widgets;

[GenerateTypedNameReferences]
[Virtual]
public partial class ChatBox : UIWidget
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly ILogManager _log = default!;

    // MC Changes:
    [Dependency] private readonly IConfigurationManager _configurationManager = null!;
    // MC Changes

    private readonly ISawmill _sawmill;
    private readonly ChatUIController _controller;

    public bool Main { get; set; }
    public bool UseLobbyTheme { get; private set; }
    public bool LobbyCrtEnabled { get; private set; }

    public ChatSelectChannel SelectedChannel => ChatInput.ChannelSelector.SelectedChannel;

    public readonly Queue<RepeatedMessage> RepeatQueue = new();
    private readonly HashSet<string> _whitelist = ["mono", "scramble", "bolditalic", "bold", "bullet", "color", "font", "head", "italic"];

    // MCChanges:
    private bool _emojiAvaible = false;
    // MCChanges

    public ChatBox()
    {
        RobustXamlLoader.Load(this);
        _sawmill = _log.GetSawmill("chat");

        ChatInput.Input.OnTextEntered += OnTextEntered;
        ChatInput.Input.OnKeyBindDown += OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged += OnTextChanged;
        ChatInput.Input.OnFocusEnter += OnFocusEnter;
        ChatInput.Input.OnFocusExit += OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect += OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter += OnChannelFilter;
        ChatInput.FilterButton.Popup.OnNewHighlights += OnNewHighlights;
        _controller = UserInterfaceManager.GetUIController<ChatUIController>();
        _controller.MessageAdded += OnMessageAdded;
        _controller.HighlightsUpdated += OnHighlightsUpdated;
        _controller.RegisterChat(this);

        // MCChanges:
        _configurationManager.OnValueChanged(MCConfigVars.ChatEmoji, value =>
        {
            _emojiAvaible = value;

            if (value)
                return;

            var toRemove = Contents.Children.Where(child => !(!child.Name?.Contains("__mcsprite_") ?? false)).ToList();
            foreach (var child in toRemove)
            {
                Contents.Children.Remove(child);
            }

        }, true);
        // MCChanges
    }

    private void OnTextEntered(LineEditEventArgs args)
    {
        _controller.SendMessage(this, SelectedChannel);
    }

    private void OnMessageAdded(ChatMessage msg)
    {
        _sawmill.Debug($"{msg.Channel}: {msg.Message}");
        if (!ChatInput.FilterButton.Popup.IsActive(msg.Channel))
            return;

        if (msg is { Read: false, AudioPath: { } })
            _entManager.System<AudioSystem>().PlayGlobal(
                msg.AudioPath,
                Filter.Local(),
                false,
                AudioParams.Default.WithVolume(AudioHelpers.SanitizeVolume(msg.AudioVolume, 0f)));

        msg.Read = true;

        var color = msg.MessageColorOverride ?? msg.Channel.TextColor();

        AddLine(msg.WrappedMessage, color, msg.SenderEntity, msg.Message, msg.Channel, msg.RepeatCheckSender);

    }

    private void OnHighlightsUpdated(string highlights)
    {
        ChatInput.FilterButton.Popup.UpdateHighlights(highlights);
    }

    private void OnChannelSelect(ChatSelectChannel channel)
    {
        _controller.UpdateSelectedChannel(this);
    }

    public void Repopulate()
    {
        Contents.Clear();

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }
    }

    public void RefreshLocalization()
    {
        ChatInput.RefreshLocalization();
        _controller.UpdateSelectedChannel(this);
    }

    private void OnChannelFilter(ChatChannel channel, bool active)
    {
        Contents.Clear();

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }

        if (active)
            _controller.ClearUnfilteredUnreads(channel);
    }

    private void OnNewHighlights(string highlighs)
    {
        _controller.UpdateHighlights(highlighs);
    }

    public void AddLine(string message, Color color, NetEntity sender, string unwrapped, ChatChannel channel, bool repeatCheckSender)
    {
        // MC changes
        color = AdjustLobbyTextColor(color);
        var formatted = new FormattedMessage(10);
        // MC changes
        formatted.PushColor(color);
        formatted.AddMarkupOrThrow(message);
        formatted.Pop();

        formatted = FilterProblematicTags(formatted);
        // RMC chat repetition guard: CMChatSystem can be unavailable during early client startup.
        if (TryRepeatWithCMChat(formatted, sender, unwrapped, channel, repeatCheckSender))
            return;

        Contents.AddMessage(formatted);
        Contents.InvalidateArrange();
    }

    public void SetLobbyTheme(bool enabled, bool crtEnabled)
    {
        UseLobbyTheme = enabled;
        LobbyCrtEnabled = crtEnabled;
    }

    private Color AdjustLobbyTextColor(Color color)
    {
        if (!UseLobbyTheme)
            return color;

        if (color == Color.LightGray || color == Color.DarkGray)
            return LobbyCrtEnabled ? StyleNano.LobbyCrtMutedText : StyleNano.LobbyCleanMutedText;

        return color;
    }

    private FormattedMessage FilterProblematicTags(FormattedMessage message)
    {
        var output = new FormattedMessage(message.Count);
        foreach (var tag in message)
        {
            // MC Changes:
            if (tag.Name is not { } name)
            {
                output.PushTag(tag);
                continue;
            }

            if (_emojiAvaible && name == "mcsprite")
            {
                output.PushTag(tag);
                continue;
            }

            if (_whitelist.Contains(name))
                output.PushTag(tag);

        }

        return output;
    }

    // RMC chat repetition guard start
    private bool TryRepeatWithCMChat(FormattedMessage formatted, NetEntity sender, string unwrapped, ChatChannel channel, bool repeatCheckSender)
    {
        try
        {
            return _entManager.SystemOrNull<CMChatSystem>()?.TryRepetition(
                this,
                Contents,
                formatted,
                sender,
                unwrapped,
                channel,
                repeatCheckSender) ?? false;
        }
        catch (NullReferenceException)
        {
            return false;
        }
    }
    // RMC chat repetition guard end

    public void Focus(ChatSelectChannel? channel = null)
    {
        var input = ChatInput.Input;
        var selectStart = Index.End;

        if (channel != null)
            ChatInput.ChannelSelector.Select(channel.Value);

        input.IgnoreNext = true;
        input.GrabKeyboardFocus();

        input.CursorPosition = input.Text.Length;
        input.SelectionStart = selectStart.GetOffset(input.Text.Length);
    }

    public void CycleChatChannel(bool forward)
    {
        var idx = Array.IndexOf(ChannelSelectorPopup.ChannelSelectorOrder, SelectedChannel);
        do
        {
            idx += forward ? 1 : -1;
            idx = MathHelper.Mod(idx, ChannelSelectorPopup.ChannelSelectorOrder.Length);
        } while ((_controller.SelectableChannels & ChannelSelectorPopup.ChannelSelectorOrder[idx]) == 0);

        SafelySelectChannel(ChannelSelectorPopup.ChannelSelectorOrder[idx]);
    }

    public void SafelySelectChannel(ChatSelectChannel toSelect)
    {
        toSelect = _controller.MapLocalIfGhost(toSelect);
        if ((_controller.SelectableChannels & toSelect) == 0)
            return;

        ChatInput.ChannelSelector.Select(toSelect);
    }

    private void OnInputKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.TextReleaseFocus)
        {
            ChatInput.Input.ReleaseKeyboardFocus();
            ChatInput.Input.Clear();
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelForward)
        {
            CycleChatChannel(true);
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelBackward)
        {
            CycleChatChannel(false);
            args.Handle();
        }
    }

    private void OnTextChanged(LineEditEventArgs args)
    {
        _controller.UpdateSelectedChannel(this);
        _controller.NotifyChatTextChange();
    }

    private void OnFocusEnter(LineEditEventArgs args)
    {
        _controller.NotifyChatFocus(true);
    }

    private void OnFocusExit(LineEditEventArgs args)
    {
        _controller.NotifyChatFocus(false);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        _controller.UnregisterChat(this);
        ChatInput.Input.OnTextEntered -= OnTextEntered;
        ChatInput.Input.OnKeyBindDown -= OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged -= OnTextChanged;
        ChatInput.ChannelSelector.OnChannelSelect -= OnChannelSelect;
    }
}
