using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CCM.CommunicationsConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class CCMCommunicationsConsoleWindow : DefaultWindow
{
    public CCMCommunicationsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
// thanks to _gadmin1 (discord) for the provided code
