using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CCM.Vehicle.UI.Weapons;

[GenerateTypedNameReferences]
public sealed partial class VehicleWeaponLoaderWindow : FancyWindow
{
    public VehicleWeaponLoaderWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
