// CM14 rework: non-RMC edit marker.
using Content.Client._CCM.UserInterface.Controls;
using Content.Client.Stylesheets;
using Content.Shared._RMC14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class EscapeMenu : DefaultCMWindow
    {
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IStylesheetManager _stylesheets = default!;
        private readonly Action<string> _onThemeColorChanged;

        public EscapeMenu()
        {
            _onThemeColorChanged = _ => RefreshTheme();
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
            Stylesheet = _stylesheets.SheetNano;

            ApplyLobbyTheme(_cfg.GetCVar(RMCCVars.RMCLobbyCrtEnabled));
            _cfg.OnValueChanged(RMCCVars.RMCLobbyCrtEnabled, ApplyLobbyTheme);
            _cfg.OnValueChanged(RMCCVars.RMCUIColorTheme, _onThemeColorChanged);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (!disposing)
                return;

            _cfg.UnsubValueChanged(RMCCVars.RMCLobbyCrtEnabled, ApplyLobbyTheme);
            _cfg.UnsubValueChanged(RMCCVars.RMCUIColorTheme, _onThemeColorChanged);
        }

        private void ApplyLobbyTheme(bool crtEnabled)
        {
            foreach (var button in EnumerateMenuButtons())
            {
                SetThemeClass(button, crtEnabled);
            }

            SetThemeClass(MenuDivider, crtEnabled);
        }

        private void RefreshTheme()
        {
            Stylesheet = _stylesheets.SheetNano;
            ApplyLobbyTheme(_cfg.GetCVar(RMCCVars.RMCLobbyCrtEnabled));
            InvalidateStyleSheet();
            DoStyleUpdate();
        }

        private Button[] EnumerateMenuButtons()
        {
            return new[]
            {
                VoteCallButton,
                RulesButton,
                GuidebookButton,
                AchievementsButton,
                SponsorshipButton,
                WikiButton,
                OptionsButton,
                DisconnectButton,
                QuitButton,
            };
        }

        private static void SetThemeClass(Control control, bool crtEnabled)
        {
            if (crtEnabled)
            {
                control.AddStyleClass(StyleNano.StyleClassLobbyThemeCrt);
                control.RemoveStyleClass(StyleNano.StyleClassLobbyThemeClean);
            }
            else
            {
                control.AddStyleClass(StyleNano.StyleClassLobbyThemeClean);
                control.RemoveStyleClass(StyleNano.StyleClassLobbyThemeCrt);
            }
        }
    }
}
