// CM14 rework: non-RMC edit marker.
using Content.Client._CCM.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageRestartConfirmWindow : DefaultCMWindow
{
    public event Action? Confirmed;
    public event Action? Cancelled;

    private bool _decisionMade;

    public LanguageRestartConfirmWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ =>
        {
            _decisionMade = true;
            Confirmed?.Invoke();
            Close();
        };

        CancelButton.OnPressed += _ =>
        {
            _decisionMade = true;
            Cancelled?.Invoke();
            Close();
        };

        OnClose += () =>
        {
            if (_decisionMade)
                return;

            Cancelled?.Invoke();
        };
    }
}
