using Content.Client.Administration.Managers;
using Content.Client.Options.UI.Tabs;
using Content.Client.Stylesheets;
using Content.Shared._RMC14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultCMWindow
    {
        [Dependency] private readonly IClientAdminManager _adminManager = default!;
        [Dependency] private readonly IConfigurationManager _config = default!;
        private readonly MiscTab _miscTab;
        private readonly GraphicsTab _graphicsTab;
        private readonly KeyRebindTab _keyRebindTab;
        private readonly AudioTab _audioTab;
        private readonly AccessibilityTab _accessibilityTab;
        private readonly AdminOptionsTab _adminOptionsTab;
        private bool _adminTabAdded;

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetNano;

            _miscTab = new MiscTab();
            _graphicsTab = new GraphicsTab();
            _keyRebindTab = new KeyRebindTab();
            _audioTab = new AudioTab();
            _accessibilityTab = new AccessibilityTab();
            _adminOptionsTab = new AdminOptionsTab();

            Tabs.AddTab(_miscTab, Loc.GetString("ui-options-tab-misc"));
            Tabs.AddTab(_graphicsTab, Loc.GetString("ui-options-tab-graphics"));
            Tabs.AddTab(_keyRebindTab, Loc.GetString("ui-options-tab-controls"));
            Tabs.AddTab(_audioTab, Loc.GetString("ui-options-tab-audio"));
            Tabs.AddTab(_accessibilityTab, Loc.GetString("ui-options-tab-accessibility"));

            OnClose += () => _keyRebindTab.RefreshKeyControls();

            UpdateTabs();
            Tabs.RefreshTabStyles();
            _config.OnValueChanged(RMCCVars.RMCUIColorTheme, OnThemeChanged, false);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
                _config.UnsubValueChanged(RMCCVars.RMCUIColorTheme, OnThemeChanged);
        }

        public void UpdateTabs()
        {
            var isAdmin = _adminManager.IsAdmin(true);
            if (isAdmin)
            {
                if (!_adminTabAdded)
                {
                    Tabs.AddTab(_adminOptionsTab, Loc.GetString("ui-options-tab-admin"));
                    _adminTabAdded = true;
                }
            }
            else if (_adminTabAdded)
            {
                Tabs.RemoveTab(_adminOptionsTab);
                _adminTabAdded = false;
            }

            _graphicsTab.Control.ReloadValues();
            _miscTab.Control.ReloadValues();
            _accessibilityTab.Control.ReloadValues();
            _audioTab.Control.ReloadValues();
            _keyRebindTab.RefreshKeyControls();
            if (_adminTabAdded)
                _adminOptionsTab.Control.ReloadValues();

            Tabs.RefreshTabStyles();
        }

        public void SelectTabIndex(int tab)
        {
            Tabs.CurrentTab = tab;
            Tabs.RefreshTabStyles();
        }

        private void OnThemeChanged(string _)
        {
            Tabs.RefreshTabStyles();
        }
    }
}

