using System;
using System.Numerics;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client.UserInterface.Systems.MenuBar.Widgets
{
    [GenerateTypedNameReferences]
    public sealed partial class GameTopMenuBar : UIWidget
    {
        [Dependency] private readonly IResourceCache _resourceCache = default!;

        public GameTopMenuBar()
        {
            IoCManager.InjectDependencies(this);

            try
            {
                RobustXamlLoader.Load(this);
            }
            catch (Exception)
            {
                BuildFallbackUi();
            }
        }

        private void BuildFallbackUi()
        {
            Name = "MenuButtons";
            VerticalExpand = false;
            Orientation = LayoutOrientation.Horizontal;
            HorizontalAlignment = HAlignment.Stretch;
            VerticalAlignment = VAlignment.Top;
            SeparationOverride = 5;

            NameScope = new NameScope();

            AddMenuButton(
                "EscapeButton",
                "/Textures/Interface/hamburger.svg.192dpi.png",
                EngineKeyFunctions.EscapeMenu,
                Loc.GetString("game-hud-open-escape-menu-button-tooltip"));

            AddMenuButton(
                "GuidebookButton",
                "/Textures/Interface/students-cap.svg.192dpi.png",
                ContentKeyFunctions.OpenGuidebook,
                Loc.GetString("ui-options-function-open-guidebook"),
                visible: false);

            AddMenuButton(
                "CharacterButton",
                "/Textures/Interface/character.svg.192dpi.png",
                ContentKeyFunctions.OpenCharacterMenu,
                Loc.GetString("ui-options-function-open-character-menu"),
                visible: false);

            AddMenuButton(
                "EmotesButton",
                "/Textures/Interface/emotes.svg.192dpi.png",
                ContentKeyFunctions.OpenEmotesMenu,
                Loc.GetString("game-hud-open-emotes-menu-button-tooltip"));

            AddMenuButton(
                "CraftingButton",
                "/Textures/Interface/hammer.svg.192dpi.png",
                ContentKeyFunctions.OpenCraftingMenu,
                Loc.GetString("game-hud-open-crafting-menu-button-tooltip"));

            AddMenuButton(
                "ActionButton",
                "/Textures/Interface/fist.svg.192dpi.png",
                ContentKeyFunctions.OpenActionsMenu,
                Loc.GetString("game-hud-open-actions-menu-button-tooltip"));

            AddMenuButton(
                "AdminButton",
                "/Textures/Interface/gavel.svg.192dpi.png",
                ContentKeyFunctions.OpenAdminMenu,
                Loc.GetString("game-hud-open-admin-menu-button-tooltip"));

            AddMenuButton(
                "SandboxButton",
                "/Textures/Interface/sandbox.svg.192dpi.png",
                ContentKeyFunctions.OpenSandboxWindow,
                Loc.GetString("game-hud-open-sandbox-menu-button-tooltip"));

            AddMenuButton(
                "AHelpButton",
                "/Textures/Interface/info.svg.192dpi.png",
                ContentKeyFunctions.OpenAHelp,
                Loc.GetString("ui-options-function-open-a-help"));

            NameScope.Complete();
        }

        private void AddMenuButton(
            string name,
            string texturePath,
            BoundKeyFunction boundKey,
            string tooltip,
            bool visible = true)
        {
            var button = new MenuButton
            {
                Name = name,
                Icon = _resourceCache.GetTexture(texturePath),
                BoundKey = boundKey,
                ToolTip = tooltip,
                MinSize = new Vector2(58f, 58f),
                HorizontalExpand = true,
                Visible = visible,
                AppendStyleClass = StyleBase.ButtonSquare,
            };

            AddChild(button);
            NameScope!.Register(name, button);
        }
    }
}
