using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Radio;

[GenerateTypedNameReferences]
public sealed partial class RMCRadioFilterWindow : DefaultCMWindow
{
    public RMCRadioFilterWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

