// CM14 rework: non-RMC edit marker.
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    private int _prevNumberRoles;

    public GhostGui()
    {
        try
        {
            RobustXamlLoader.Load(this);
        }
        catch (Exception)
        {
            BuildFallbackUi();
        }

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonCaution);
    }

    private void BuildFallbackUi()
    {
        HorizontalAlignment = HAlignment.Center;
        MouseFilter = MouseFilterMode.Ignore;

        NameScope = new NameScope();

        var root = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 4
        };

        var returnToBodyButton = new Button
        {
            Name = nameof(ReturnToBodyButton),
            Text = Loc.GetString("ghost-gui-return-to-body-button"),
            StyleClasses = { StyleBase.ButtonOpenBoth }
        };

        var ghostWarpButton = new Button
        {
            Name = nameof(GhostWarpButton),
            Text = Loc.GetString("ghost-gui-ghost-warp-button"),
            StyleClasses = { StyleBase.ButtonOpenBoth }
        };

        var ghostRolesButton = new Button
        {
            Name = nameof(GhostRolesButton),
            StyleClasses = { StyleBase.ButtonOpenBoth }
        };

        root.AddChild(returnToBodyButton);
        root.AddChild(ghostWarpButton);
        root.AddChild(ghostRolesButton);
        AddChild(root);

        NameScope.Register(returnToBodyButton.Name, returnToBodyButton);
        NameScope.Register(ghostWarpButton.Name, ghostWarpButton);
        NameScope.Register(ghostRolesButton.Name, ghostRolesButton);
        NameScope.Complete();
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleBase.ButtonCaution);
            }

            _prevNumberRoles = (int) roles;
        }

        TargetWindow.Populate();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
