# CM14 rework: non-RMC edit marker.
[net]
tickrate = 30
max_connections = 1024

[game]
hostname = "[RU]🌍 Colonial Marine Corps 🌍"
desc = "Colonial Marine Corps (ex-Corvax CM) — the first multilingual Space Station 14 build focused on Colonial Marines and based on the RMC-14. \n The server maintains Medium RP requirements."
soft_max_players = 250
map_rotation = true
lobbyduration = 180
round_end_pvs_overrides = false
defaultpreset = "CMDistressSignal"
fallbackenabled = false
fallbackpreset = "CMDistressSignal"
round_end_sound_collection = "CMRoundEnd"
contraband_examine = false
map_pool = "CCMMapPool"

[ghost]
kill_crit = false
role_time = 0

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
map_enabled = true
preset_enabled = false

[admin]
deadmin_on_join = true
see_own_notes = true
server_ban_erase_player = true
new_player_threshold = 600

[atmos]
space_wind = false
monstermos_rip_tiles = false
grid_impulse = false
max_process_time = 1

[ic]
flavor_text = true

[shuttle]
auto_call_time = 0
arrivals_planet = false
arrivals = false
grid_fill = false
preload_grids = false
startup_time = 10
travel_time = 100
arrival_time = 10
cooldown = 120
mass_limit = -1
emergency = false

[database]
engine = "sqlite"
sqlite_dbpath = "preferences.db"

[discord]
rich_main_icon_id = "corvax"

[rules]
time = 20.0

[viewport]
maximum_width = 26

[infolinks]
discord = "https://discord.gg/VWJZFUWgRc"
wiki = "https://station14.ru/wiki/Портал:Colonial_Marines"
patreon = "https://boosty.to/corvax"
appeal = "https://discord.gg/QBCV2f42xG"

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e"

[physics]
maxlinvelocity = 51
grid_splitting = false

[auth]
mode = 1

[explosion]
can_create_vacuum = false

[procgen]
preload = false

[rmc]
late_joins_per_burrowed_larva = 7
late_joins_per_burrowed_larva_early = 7.5
late_joins_per_burrowed_larva_early_threshold_minutes = 15
marines_per_xeno = 6
auto_balance_step = 0.25
auto_balance_min = 5
auto_balance_max = 6.5
distress_xenos_minimum = 1
discord_oauth_base_url = "http://127.0.0.1:2424"
discord_oauth_state_secret = "replace-me"
discord_oauth_state_lifetime_seconds = 300
emote_cooldown_seconds = 1
chat_translate_api = "http://127.0.0.1:5500/translate"
chat_translate_source = "auto"
enable_suicide = false

[gateway]
generator_enabled = false

[accessibility]
screen_shake_intensity = 1

[events]
enabled = false

[build]
engine_version = "264.0.2-fix-physics"

[movement]
mob_pushing = true

[mc.z_levels]
enabled = false
