// CM14 rework: non-RMC edit marker.
using System.Collections;
using System.Collections.Generic;
using System.Numerics;
using System;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using UIControl = Robust.Client.UserInterface.Control;

namespace Content.Client._CCM.UserInterface.Controls
{
    [GenerateTypedNameReferences]
    [Virtual]
    public partial class DefaultCMWindow : BaseWindow
    {
        public const string StyleClassWindowTitle = "windowTitle";
        public const string StyleClassWindowPanel = "windowPanel";
        public const string StyleClassWindowHeader = "windowHeader";
        public const string StyleClassWindowCloseButton = "windowCloseButton";

        public float WindowEdgeSeparation = 30;
        public float WindowEdgeBump = 50;
        public DirectionFlag AllowOffScreen = ~DirectionFlag.North;

        private string? _headerClass;
        private string? _titleClass;

        public DefaultCMWindow()
        {
            RobustXamlLoader.Load(this);
            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetRMC;
            MouseFilter = MouseFilterMode.Stop;

            WindowHeader.MinSize = new Vector2(0, HeaderSizeY);

            Contents = ContentsContainer;

            CloseButton.OnPressed += CloseButtonPressed;
            XamlChildren = new SS14ContentCollection(this);
        }

        public string? HeaderClass
        {
            get => _headerClass;
            set
            {
                if (_headerClass == value)
                    return;

                if (_headerClass != null)
                    WindowHeader.RemoveStyleClass(_headerClass);

                if (value != null)
                    WindowHeader.AddStyleClass(value);

                _headerClass = value;
            }
        }

        public string? TitleClass
        {
            get => _titleClass;
            set
            {
                if (_titleClass == value)
                    return;

                if (_titleClass != null)
                    TitleLabel.RemoveStyleClass(_titleClass);

                if (value != null)
                    TitleLabel.AddStyleClass(value);

                _titleClass = value;
            }
        }

        public UIControl Contents { get; private set; }
        public PanelContainer HeaderPanel => WindowHeader;
        public PanelContainer BodyPanel => ContentsBackground;
        public Label WindowTitleLabel => TitleLabel;
        public TextureButton WindowCloseButton => CloseButton;

        private const int DragMarginSize = 7;
        private const float HeaderSizeY = 25;
        protected virtual Vector2 ContentsMinimumSize => new Vector2(50, 50);

        protected override Vector2 MeasureOverride(Vector2 availableSize)
        {
            return Vector2.Max(
                ContentsMinimumSize,
                base.MeasureOverride(Vector2.Max(availableSize, ContentsMinimumSize)));
        }

        public string? Title
        {
            get => TitleLabel.Text;
            set => TitleLabel.Text = value;
        }

        public override void Close()
        {
            base.Close();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                CloseButton.OnPressed -= CloseButtonPressed;
            }
        }

        private void CloseButtonPressed(BaseButton.ButtonEventArgs args)
        {
            Close();
        }

        public void OpenCenteredAnimated()
        {
            if (!IsOpen)
                OpenCentered();
        }

        public void CloseAnimated()
        {
            base.Close();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            if (!IsMeasureValid)
                return;

            var (spaceX, spaceY) = Parent!.Size;

            var maxX = spaceX - ((AllowOffScreen & DirectionFlag.West) == 0 ? Size.X : WindowEdgeSeparation);
            var maxY = spaceY - ((AllowOffScreen & DirectionFlag.South) == 0 ? Size.Y : WindowEdgeSeparation);

            if (Position.X > spaceX)
                maxX -= WindowEdgeBump;

            if (Position.Y > spaceY)
                maxY -= WindowEdgeBump;

            var pos = Vector2.Min(Position, new Vector2(maxX, maxY));

            var minX = (AllowOffScreen & DirectionFlag.East) == 0 ? 0 : WindowEdgeSeparation - Size.X;
            var minY = (AllowOffScreen & DirectionFlag.North) == 0 ? 0 : WindowEdgeSeparation - Size.Y;

            pos = Vector2.Max(pos, new Vector2(minX, minY));
            if (Position != pos)
                LayoutContainer.SetPosition(this, pos);
        }

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.None;

            if (Resizable)
            {
                if (relativeMousePos.Y < DragMarginSize)
                    mode = DragMode.Top;
                else if (relativeMousePos.Y > Size.Y - DragMarginSize)
                    mode = DragMode.Bottom;

                if (relativeMousePos.X < DragMarginSize)
                    mode |= DragMode.Left;
                else if (relativeMousePos.X > Size.X - DragMarginSize)
                    mode |= DragMode.Right;
            }

            if (mode == DragMode.None && relativeMousePos.Y < HeaderSizeY)
                mode = DragMode.Move;

            return mode;
        }

        public sealed class SS14ContentCollection : ICollection<UIControl>, IReadOnlyCollection<UIControl>
        {
            private readonly DefaultCMWindow _owner;

            public SS14ContentCollection(DefaultCMWindow owner)
            {
                _owner = owner;
            }

            public Enumerator GetEnumerator()
            {
                return new(_owner);
            }

            IEnumerator<UIControl> IEnumerable<UIControl>.GetEnumerator() => GetEnumerator();
            IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

            public void Add(UIControl item)
            {
                _owner.Contents.AddChild(item);
            }

            public void Clear()
            {
                _owner.Contents.RemoveAllChildren();
            }

            public bool Contains(UIControl item)
            {
                return item?.Parent == _owner.Contents;
            }

            public void CopyTo(UIControl[] array, int arrayIndex)
            {
                _owner.Contents.Children.CopyTo(array, arrayIndex);
            }

            public bool Remove(UIControl item)
            {
                if (item?.Parent != _owner.Contents)
                    return false;

                DebugTools.AssertNotNull(_owner?.Contents);
                _owner!.Contents.RemoveChild(item);

                return true;
            }

            int ICollection<UIControl>.Count => _owner.Contents.ChildCount;
            int IReadOnlyCollection<UIControl>.Count => _owner.Contents.ChildCount;

            public bool IsReadOnly => false;

            public struct Enumerator : IEnumerator<UIControl>
            {
                private OrderedChildCollection.Enumerator _enumerator;

                internal Enumerator(DefaultCMWindow owner)
                {
                    _enumerator = owner.Contents.Children.GetEnumerator();
                }

                public bool MoveNext()
                {
                    return _enumerator.MoveNext();
                }

                public void Reset()
                {
                    _enumerator.Reset();
                }

                public UIControl Current => _enumerator.Current;

                object IEnumerator.Current => Current;

                public void Dispose()
                {
                    _enumerator.Dispose();
                }
            }
        }
    }
}
