using System.Linq;
using System.Numerics;
using Content.Client._RMC14.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Content.Client._RMC14.TacticalMap.Controls;

namespace Content.Client._RMC14.TacticalMap.UI;

[GenerateTypedNameReferences]
public sealed partial class TacticalMapWindow : RMCPopOutWindow
{
    private static readonly ISawmill _logger = Logger.GetSawmill("tactical_map_settings");
    private static readonly Vector2i DefaultWindowSize = new(600, 600);
    private const float MinimumWindowWidth = 320f;
    private const float MinimumWindowHeight = 240f;
    private const float MinimumVisibleWidth = 80f;
    private const float MinimumVisibleHeight = 80f;

    protected override Control Control => Wrapper;
    
    private TacticalMapSettingsManager? _settingsManager;
    private bool _settingsLoaded = false;
    private string? _currentMapId;

    public TacticalMapWindow()
    {
        InitializeSettings();

        Vector2i targetSize = DefaultWindowSize;
        Vector2 targetPosition = new(-1, -1);

        if (_settingsLoaded && _settingsManager != null)
        {
            try
            {
                var settings = _settingsManager.LoadSettings(_currentMapId);

                targetSize = SanitizeWindowSize(settings.WindowSize);

                if (settings.WindowPosition.X != -1.0f || settings.WindowPosition.Y != -1.0f)
                    targetPosition = settings.WindowPosition;
            }
            catch (Exception ex)
            {
                _logger.Warning($"Failed to load window settings for map '{_currentMapId}', using defaults: {ex}");
            }
        }

        SetSize = targetSize;
        RobustXamlLoader.Load(this);

        WindowHeader.Visible = false;
        WindowHeader.MinSize = Vector2.Zero;
        ContentsContainer.Margin = new Thickness(0);

        if (Children.FirstOrDefault(child => child.StyleClasses.Contains(StyleClassWindowPanel)) is { } panel)
            RemoveChild(panel);

        if (targetPosition.X != -1.0f && targetPosition.Y != -1.0f)
        {
            LayoutContainer.SetPosition(this, ClampWindowPosition(targetPosition));
        }

        OnPopout += () => Wrapper.PopoutButton.Visible = false;
        Wrapper.PopoutRequested += PopOut;
    }

    public void SetMapId(string? mapId)
    {
        if (_currentMapId == mapId)
            return;

        _currentMapId = mapId;

        if (_settingsLoaded && _settingsManager != null)
        {
            LoadWindowSettings();
        }
    }

    private void InitializeSettings()
    {
        try
        {
            _settingsManager = IoCManager.Resolve<TacticalMapSettingsManager>();
            _settingsLoaded = true;
        }
        catch (Exception ex)
        {
            _logger.Warning($"Failed to initialize tactical map settings manager: {ex}");
            _settingsLoaded = false;
        }
    }

    private void LoadWindowSettings()
    {
        if (!_settingsLoaded || _settingsManager == null)
            return;

        try
        {
            var settings = _settingsManager.LoadSettings(_currentMapId);

            var size = SanitizeWindowSize(settings.WindowSize);
            SetSize = size;

            if (settings.WindowPosition.X != -1.0f || settings.WindowPosition.Y != -1.0f)
            {
                var position = ClampWindowPosition(settings.WindowPosition);
                LayoutContainer.SetPosition(this, position);
            }
        }
        catch (Exception ex)
        {
            _logger.Warning($"Failed to load window settings for map '{_currentMapId}': {ex}");
        }
    }

    private Vector2i SanitizeWindowSize(Vector2 savedSize)
    {
        if (savedSize.X <= 0 || savedSize.Y <= 0)
            return DefaultWindowSize;

        var rootSize = GetWindowRootSize();
        var maxWidth = rootSize.X > 0 ? MathF.Max(MinimumWindowWidth, rootSize.X) : savedSize.X;
        var maxHeight = rootSize.Y > 0 ? MathF.Max(MinimumWindowHeight, rootSize.Y) : savedSize.Y;

        return new Vector2i(
            (int)Math.Clamp(savedSize.X, MinimumWindowWidth, maxWidth),
            (int)Math.Clamp(savedSize.Y, MinimumWindowHeight, maxHeight));
    }

    private Vector2 ClampWindowPosition(Vector2 savedPosition)
    {
        var rootSize = GetWindowRootSize();
        if (rootSize.X <= 0 || rootSize.Y <= 0)
            return new Vector2(Math.Max(0, savedPosition.X), Math.Max(0, savedPosition.Y));

        var windowSize = new Vector2(
            MathF.Max(MinimumVisibleWidth, SetSize.X),
            MathF.Max(MinimumVisibleHeight, SetSize.Y));

        var maxX = MathF.Max(0, rootSize.X - MathF.Min(windowSize.X, rootSize.X));
        var maxY = MathF.Max(0, rootSize.Y - MathF.Min(windowSize.Y, rootSize.Y));

        return new Vector2(
            Math.Clamp(savedPosition.X, 0, maxX),
            Math.Clamp(savedPosition.Y, 0, maxY));
    }

    private Vector2 GetWindowRootSize()
    {
        if (Parent != null)
            return Parent.Size;

        return UserInterfaceManager.WindowRoot.Size;
    }
}
