using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.UserInterface.Controls;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared.Localizations;
using Content.Shared._RMC14.Medal;
using Content.Shared._RMC14.CCVar;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Client.GameObjects;
using Robust.Shared.Utility;
using Content.Client.Stylesheets;

namespace Content.Client._RMC14.RMCPlaytimeStats;

[GenerateTypedNameReferences]
public sealed partial class RMCPlaytimeStatsWindow : FancyWindow
{
    private enum OverallCategory
    {
        Overall = 0,
        Xeno = 1,
        Marines = 2,
        Survivors = 3
    }

    [Dependency] private readonly JobRequirementsManager _jobRequirementsManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IConfigurationManager _config = default!;

    private Color _altColor = Color.FromHex("#124120");
    private Color _defaultColor = Color.FromHex("#0D3518");
    private Color _headerColor = Color.FromHex("#185B2B");
    private Color _panelColor = Color.FromHex("#05180A");
    private Color _textColor = Color.White;
    private Color _mutedTextColor = Color.White;
    private Color _separatorColor = Color.FromHex("#2B7E45");
    private Color _buttonSelectedColor = Color.FromHex("#138C2F");
    private Color _buttonNormalColor = Color.FromHex("#0D3518");
    private StyleNano.UiColorTheme _appliedTheme;
    private bool _useAltColor;
    private Button? _selectedButton;
    private OverallCategory _overallCategory = OverallCategory.Overall;
    private bool _suppressOverallCategoryEvent;

    private TimeSpan _bronzeTime;
    private TimeSpan _silverTime;
    private TimeSpan _goldTime;
    private TimeSpan _platinumTime;
    private TimeSpan _rubyTime;
    private TimeSpan _emeraldTime;
    private TimeSpan _amethystTime;
    private TimeSpan _prismaticTime;

    public RMCPlaytimeStatsWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetNano;

        SetupOverallCategorySelector();
        LayoutContainer.SetAnchorPreset(BackgroundImage, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(ContentRoot, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(ContentBackdrop, LayoutContainer.LayoutPreset.Wide);

        LoadMedalTimes();
        PopulateDepartmentButtons();
        ApplyThemeColors(true);
        ShowGeneralTab();

        // CCM sponsorship stats refresh start
        _jobRequirementsManager.Updated += OnRequirementsUpdated;
        _jobRequirementsManager.RequestSponsorshipStatus();
        _config.OnValueChanged(RMCCVars.RMCUIColorTheme, OnThemeChanged, false);
        _config.OnValueChanged(RMCCVars.RMCLobbyUiStyle, OnThemeChanged, false);
        OnClose += () =>
        {
            _jobRequirementsManager.Updated -= OnRequirementsUpdated;
        };
        // CCM sponsorship stats refresh end
    }

    // CCM sponsorship stats refresh: rebuild view when sponsorship changes available roles.
    private void OnRequirementsUpdated()
    {
        ShowGeneralTab();
    }

    private void LoadMedalTimes()
    {
        _bronzeTime = TimeSpan.FromHours(_config.GetCVar(RMCCVars.RMCPlaytimeBronzeMedalTimeHours));
        _silverTime = TimeSpan.FromHours(_config.GetCVar(RMCCVars.RMCPlaytimeSilverMedalTimeHours));
        _goldTime = TimeSpan.FromHours(_config.GetCVar(RMCCVars.RMCPlaytimeGoldMedalTimeHours));
        _platinumTime = TimeSpan.FromHours(_config.GetCVar(RMCCVars.RMCPlaytimePlatinumMedalTimeHours));
        _rubyTime = TimeSpan.FromHours(_config.GetCVar(RMCCVars.RMCPlaytimeRubyMedalTimeHours));
        _emeraldTime = TimeSpan.FromHours(_config.GetCVar(RMCCVars.RMCPlaytimeEmeraldMedalTimeHours));
        _amethystTime = TimeSpan.FromHours(_config.GetCVar(RMCCVars.RMCPlaytimeAmethystMedalTimeHours));
        _prismaticTime = TimeSpan.FromHours(_config.GetCVar(RMCCVars.RMCPlaytimePrismaticMedalTimeHours));
    }

    private RMCPlaytimeMedalType? GetMedalType(TimeSpan playtime)
    {
        if (playtime >= _prismaticTime)
            return RMCPlaytimeMedalType.Prismatic;
        else if (playtime >= _amethystTime)
            return RMCPlaytimeMedalType.Amethyst;
        else if (playtime >= _rubyTime)
            return RMCPlaytimeMedalType.Ruby;
        else if (playtime >= _emeraldTime)
            return RMCPlaytimeMedalType.Emerald;
        else if (playtime >= _platinumTime)
            return RMCPlaytimeMedalType.Platinum;
        else if (playtime >= _goldTime)
            return RMCPlaytimeMedalType.Gold;
        else if (playtime >= _silverTime)
            return RMCPlaytimeMedalType.Silver;
        else if (playtime >= _bronzeTime)
            return RMCPlaytimeMedalType.Bronze;

        return null;
    }

    private IEnumerable<RMCPlaytimeMedalType> GetMedalTypesDescending(RMCPlaytimeMedalType start)
    {
        for (var type = start; type >= RMCPlaytimeMedalType.Bronze; type--)
        {
            yield return type;
        }
    }

    private SpriteSpecifier.Rsi? GetMedalIcon(string? departmentId, TimeSpan playtime, string jobId)
    {
        if (!_prototypeManager.TryIndex<JobPrototype>(jobId, out var job) || job.Medals == null)
            return null;

        var medalType = GetMedalType(playtime);
        if (medalType == null)
            return null;

        if (departmentId == "CMXeno")
        {
            var iconName = medalType switch
            {
                RMCPlaytimeMedalType.Bronze => "hudxenoupgrade2-ui",
                RMCPlaytimeMedalType.Silver => "hudxenoupgrade3-ui",
                RMCPlaytimeMedalType.Gold => "hudxenoupgrade4-ui",
                RMCPlaytimeMedalType.Platinum => "hudxenoupgrade5-ui",
                _ => "hudxenoupgrade6-ui"
            };

            return new SpriteSpecifier.Rsi(new ResPath("/Textures/_RMC14/Interface/xeno_hud.rsi"), iconName);
        }

        foreach (var type in GetMedalTypesDescending(medalType.Value))
        {
            if (job.Medals.TryGetValue(type, out var medalId) &&
                _prototypeManager.TryIndex(medalId, out EntityPrototype? medalProto) &&
                medalProto.TryGetComponent<SpriteComponent>(out var sprite))
            {
                foreach (var layer in sprite.AllLayers)
                {
                    var rsi = layer.Rsi ?? layer.ActualRsi ?? sprite.BaseRSI;
                    if (rsi == null || !rsi.TryGetState(layer.RsiState, out var state))
                        continue;

                    var stateName = state.StateId.Name;
                    if (string.IsNullOrEmpty(stateName))
                        continue;

                    return new SpriteSpecifier.Rsi(rsi.Path, stateName);
                }
            }
        }

        return null;
    }

    private void PopulateDepartmentButtons()
    {
        DepartmentButtons.DisposeAllChildren();
        _selectedButton = null;
    }

    private void ShowDepartmentTab(DepartmentPrototype dept, List<(JobPrototype Job, TimeSpan Time)> roles)
    {
        OverallHeader.Visible = false;
        if (_selectedButton != null)
        {
            _selectedButton.Pressed = false;
        }

        foreach (var child in DepartmentButtons.Children)
        {
            if (child is Button button && button.Name == dept.ID)
            {
                button.Pressed = true;
                _selectedButton = button;
                break;
            }
        }

        DepartmentContent.RemoveAllChildren();

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
            Margin = new Thickness(0, 5, 0, 0)
        };

        var deptTotalTime = roles.Sum(r => r.Time.Ticks);
        var deptTotalTimeSpan = new TimeSpan(deptTotalTime);
        var deptName = Loc.GetString(dept.Name);
        var deptTotalLabel = new Label
        {
            Text = Loc.GetString("ui-playtime-department-total",
                ("department", deptName),
                ("time", ContentLocalizationManager.FormatPlaytime(deptTotalTimeSpan))),
            Margin = new Thickness(0, 0, 0, 5),
            FontColorOverride = _mutedTextColor
        };

        content.AddChild(deptTotalLabel);
        content.AddChild(new HSeparator { Margin = new Thickness(0, 5, 0, 5) });

        var scrollContainer = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true
        };

        var rolesList = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical
        };

        var header = new RMCPlaytimeStatsHeader();
        header.OnHeaderClicked += (header, direction) =>
            HeaderClicked(header, direction, rolesList);
        header.BackgroundColorPlaytimePanel.PanelOverride = new StyleBoxFlat(_headerColor);
        header.ApplyTheme(_textColor, _separatorColor);
        rolesList.AddChild(header);
        rolesList.AddChild(new HSeparator());

        _useAltColor = false;
        foreach (var (job, playtime) in roles.OrderBy(r => Loc.GetString(r.Job.Name)))
        {
            var entry = new RMCPlaytimeStatsEntry(
                Loc.GetString(job.Name),
                playtime,
                new StyleBoxFlat(_useAltColor ? _altColor : _defaultColor),
                GetMedalIcon(dept.ID, playtime, job.ID));
            entry.ApplyTheme(_textColor, _separatorColor);

            rolesList.AddChild(entry);
            _useAltColor ^= true;
        }

        scrollContainer.AddChild(rolesList);
        content.AddChild(scrollContainer);
        DepartmentContent.AddChild(content);
        DepartmentContent.Visible = true;
    }

    private void ShowGeneralTab()
    {
        OverallHeader.Visible = true;
        _selectedButton = null;

        DepartmentContent.RemoveAllChildren();
        var rolePlaytimes = _jobRequirementsManager.FetchPlaytimeJobIdByRoles();
        var filtered = FilterRolePlaytimes(rolePlaytimes).ToList();

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
            Margin = new Thickness(0, 5, 0, 0)
        };

        var totalTime = filtered.Sum(r => r.Value.Ticks);
        var overallLabel = new Label
        {
            Text = Loc.GetString("ui-playtime-overall", ("time", new TimeSpan(totalTime))),
            Margin = new Thickness(0, 0, 0, 5),
            FontColorOverride = _mutedTextColor
        };

        OverallLabel.Text = overallLabel.Text;
        OverallLabel.FontColorOverride = _mutedTextColor;
        content.AddChild(new HSeparator { Margin = new Thickness(0, 5, 0, 5) });

        var scrollContainer = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true
        };

        var rolesList = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical
        };

        var header = new RMCPlaytimeStatsHeader();
        header.OnHeaderClicked += (header, direction) =>
            HeaderClicked(header, direction, rolesList);

        header.BackgroundColorPlaytimePanel.PanelOverride = new StyleBoxFlat(_headerColor);
        header.ApplyTheme(_textColor, _separatorColor);

        rolesList.AddChild(header);
        rolesList.AddChild(new HSeparator());
        _useAltColor = false;

        foreach (var kvp in filtered.OrderBy(r => Loc.GetString(r.Key)))
        {
            if (!_prototypeManager.TryIndex<JobPrototype>(kvp.Key, out var job))
                continue;

            var deptId = GetDepartmentIdForOverallCategory(job);

            var entry = new RMCPlaytimeStatsEntry(
                job.LocalizedName,
                kvp.Value,
                new StyleBoxFlat(_useAltColor ? _altColor : _defaultColor),
                GetMedalIcon(deptId, kvp.Value, kvp.Key));
            entry.ApplyTheme(_textColor, _separatorColor);

            rolesList.AddChild(entry);
            _useAltColor ^= true;
        }

        scrollContainer.AddChild(rolesList);
        content.AddChild(scrollContainer);
        DepartmentContent.AddChild(content);
        DepartmentContent.Visible = true;
    }

    private void SetupOverallCategorySelector()
    {
        OverallCategorySelector.AddItem(Loc.GetString("ui-playtime-category-overall"), (int) OverallCategory.Overall);
        OverallCategorySelector.AddItem(Loc.GetString("ui-playtime-category-xeno"), (int) OverallCategory.Xeno);
        OverallCategorySelector.AddItem(Loc.GetString("ui-playtime-category-marines"), (int) OverallCategory.Marines);
        OverallCategorySelector.AddItem(Loc.GetString("ui-playtime-category-survivors"), (int) OverallCategory.Survivors);
        OverallCategorySelector.SelectId((int) _overallCategory);

        OverallCategorySelector.OnItemSelected += args =>
        {
            if (_suppressOverallCategoryEvent)
                return;

            args.Button.SelectId(args.Id);
            _overallCategory = (OverallCategory) args.Id;
            ShowGeneralTab();
        };
    }

    private IEnumerable<KeyValuePair<string, TimeSpan>> FilterRolePlaytimes(IEnumerable<KeyValuePair<string, TimeSpan>> rolePlaytimes)
    {
        if (_overallCategory == OverallCategory.Overall)
            return rolePlaytimes;

        var deptId = _overallCategory switch
        {
            OverallCategory.Xeno => "CMXeno",
            OverallCategory.Marines => "CMSquad",
            OverallCategory.Survivors => "CMSurvivor",
            _ => string.Empty
        };

        if (string.IsNullOrEmpty(deptId))
            return rolePlaytimes;

        return rolePlaytimes.Where(kvp => JobInDepartment(kvp.Key, deptId));
    }

    private bool JobInDepartment(string jobId, string deptId)
    {
        if (!_prototypeManager.TryIndex<JobPrototype>(jobId, out var job))
            return false;

        foreach (var dept in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
        {
            if (dept.ID != deptId)
                continue;

            if (dept.Roles.Contains(job.ID))
                return true;
        }

        return false;
    }

    private string? GetDepartmentIdForOverallCategory(JobPrototype job)
    {
        if (_overallCategory == OverallCategory.Overall)
        {
            var dept = _prototypeManager.EnumeratePrototypes<DepartmentPrototype>()
                .FirstOrDefault(d => d.Roles.Contains(job.ID));
            return dept?.ID;
        }

        return _overallCategory switch
        {
            OverallCategory.Xeno => "CMXeno",
            OverallCategory.Marines => "CMSquad",
            OverallCategory.Survivors => "CMSurvivor",
            _ => null
        };
    }

    private void HeaderClicked(RMCPlaytimeStatsHeader.Header header,
        RMCPlaytimeStatsHeader.SortDirection direction,
        BoxContainer targetContainer)
    {
        switch (header)
        {
            case RMCPlaytimeStatsHeader.Header.Role:
                SortByRole(direction, targetContainer);
                break;

            case RMCPlaytimeStatsHeader.Header.Playtime:
                SortByPlaytime(direction, targetContainer);
                break;
        }
    }

    private void SortByRole(RMCPlaytimeStatsHeader.SortDirection direction, BoxContainer container)
    {
        var header = container.GetChild(0) as RMCPlaytimeStatsHeader;
        var entries = container.Children.OfType<RMCPlaytimeStatsEntry>().ToList();

        container.RemoveAllChildren();

        if (header != null)
            container.AddChild(header);

        container.AddChild(new HSeparator());

        var sortedEntries = (direction == RMCPlaytimeStatsHeader.SortDirection.Ascending)
            ? entries.OrderBy(entry => entry.RoleText).ToList()
            : entries.OrderByDescending(entry => entry.RoleText).ToList();

        _useAltColor = false;
        foreach (var entry in sortedEntries)
        {
            var styleBox = new StyleBoxFlat { BackgroundColor = _useAltColor ? _altColor : _defaultColor };
            entry.UpdateShading(styleBox);
            entry.ApplyTheme(_textColor, _separatorColor);
            container.AddChild(entry);
            _useAltColor ^= true;
        }
    }

    private void SortByPlaytime(RMCPlaytimeStatsHeader.SortDirection direction, BoxContainer container)
    {
        var header = container.GetChild(0) as RMCPlaytimeStatsHeader;
        var entries = container.Children.OfType<RMCPlaytimeStatsEntry>().ToList();

        container.RemoveAllChildren();

        if (header != null)
            container.AddChild(header);

        container.AddChild(new HSeparator());

        var sortedEntries = (direction == RMCPlaytimeStatsHeader.SortDirection.Ascending)
            ? entries.OrderBy(entry => entry.Playtime).ToList()
            : entries.OrderByDescending(entry => entry.Playtime).ToList();

        _useAltColor = false;
        foreach (var entry in sortedEntries)
        {
            var styleBox = new StyleBoxFlat { BackgroundColor = _useAltColor ? _altColor : _defaultColor };
            entry.UpdateShading(styleBox);
            entry.ApplyTheme(_textColor, _separatorColor);
            container.AddChild(entry);
            _useAltColor ^= true;
        }
    }

    // CCM rework lobby - start
    private void OnThemeChanged(string _)
    {
        ApplyThemeColors();
    }

    private void ApplyThemeColors(bool force = false)
    {
        var theme = StyleNano.CurrentTheme;
        if (!force && theme == _appliedTheme)
            return;

        _appliedTheme = theme;

        switch (theme)
        {
            case StyleNano.UiColorTheme.Gray:
                _defaultColor = Color.FromHex("#26303B").WithAlpha(0.92f);
                _altColor = Color.FromHex("#2D3743").WithAlpha(0.92f);
                _headerColor = Color.FromHex("#394552").WithAlpha(0.96f);
                _panelColor = Color.FromHex("#1A2028").WithAlpha(0.84f);
                _textColor = Color.FromHex("#EEF2F6");
                _mutedTextColor = Color.FromHex("#C7CFD8");
                _separatorColor = Color.FromHex("#718092").WithAlpha(0.95f);
                _buttonNormalColor = Color.FromHex("#566577");
                _buttonSelectedColor = Color.FromHex("#66788E");
                BackgroundImage.ModulateSelfOverride = Color.FromHex("#A0ACB8").WithAlpha(0.14f);
                break;
            default:
                _defaultColor = Color.FromHex("#0D3518").WithAlpha(0.92f);
                _altColor = Color.FromHex("#124120").WithAlpha(0.92f);
                _headerColor = Color.FromHex("#185B2B").WithAlpha(0.96f);
                _panelColor = Color.FromHex("#05180A").WithAlpha(0.84f);
                _textColor = Color.FromHex("#ECFFF0");
                _mutedTextColor = Color.FromHex("#C6EACB");
                _separatorColor = Color.FromHex("#2B7E45").WithAlpha(0.95f);
                _buttonNormalColor = Color.FromHex("#138C2F");
                _buttonSelectedColor = Color.FromHex("#15A31E");
                BackgroundImage.ModulateSelfOverride = Color.FromHex("#5B9A6A").WithAlpha(0.18f);
                break;
        }

        ContentBackdrop.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = _panelColor,
            BorderColor = _separatorColor,
            BorderThickness = new Thickness(1)
        };

        OverallHeaderBackground.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = _headerColor,
            BorderColor = _separatorColor,
            BorderThickness = new Thickness(1)
        };

        OverallLabel.FontColorOverride = _mutedTextColor;
        OverallCategorySelector.ModulateSelfOverride = _buttonNormalColor;

        if (DepartmentContent.ChildCount > 0)
            ShowGeneralTab();
    }
    // CCM rework lobby - end

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _config.UnsubValueChanged(RMCCVars.RMCUIColorTheme, OnThemeChanged);
            _config.UnsubValueChanged(RMCCVars.RMCLobbyUiStyle, OnThemeChanged);

        base.Dispose(disposing);
    }
}
