using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Lobby;

[GenerateTypedNameReferences]
public sealed partial class JoinXenoWindow : DefaultCMWindow
{
    private StyleNano.UiColorTheme _appliedTheme;

    public JoinXenoWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyTheme(true);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        ApplyTheme();
    }

    public void SetAvailability(bool hasLarva)
    {
        Buttons.Visible = hasLarva;
        ButtonsPanel.Visible = hasLarva;
        Label.FontColorOverride = hasLarva
            ? GetPalette(_appliedTheme).BodyText
            : GetPalette(_appliedTheme).MutedText;
    }

    private void ApplyTheme(bool force = false)
    {
        var theme = StyleNano.CurrentTheme;
        if (!force && theme == _appliedTheme)
            return;

        _appliedTheme = theme;
        var palette = GetPalette(theme);

        StatusPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.CardBackground,
            BorderColor = palette.CardBorder,
            BorderThickness = new Thickness(1),
        };

        ButtonsPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.ActionBackground,
            BorderColor = palette.ActionBorder,
            BorderThickness = new Thickness(1),
        };

        if (Label.FontColorOverride == default)
            Label.FontColorOverride = palette.BodyText;
    }

    private static XenoJoinPalette GetPalette(StyleNano.UiColorTheme theme)
    {
        return theme switch
        {
            StyleNano.UiColorTheme.Gray => new XenoJoinPalette(
                Color.FromHex("#191E26").WithAlpha(0.96f),
                Color.FromHex("#495869").WithAlpha(0.94f),
                Color.FromHex("#212730").WithAlpha(0.94f),
                Color.FromHex("#68788B").WithAlpha(0.95f),
                Color.FromHex("#C7D0DA"),
                Color.FromHex("#E4EAF1")),
            _ => new XenoJoinPalette(
                Color.FromHex("#09150C").WithAlpha(0.96f),
                Color.FromHex("#2D633B").WithAlpha(0.94f),
                Color.FromHex("#0E2012").WithAlpha(0.94f),
                Color.FromHex("#3A7A4C").WithAlpha(0.95f),
                Color.FromHex("#C6E5CD"),
                Color.FromHex("#DFF8E5")),
        };
    }

    private readonly record struct XenoJoinPalette(
        Color CardBackground,
        Color CardBorder,
        Color ActionBackground,
        Color ActionBorder,
        Color MutedText,
        Color BodyText);
}

