using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Tracker.SquadLeader;

[GenerateTypedNameReferences]
public sealed partial class SquadInfoWindow : DefaultCMWindow
{
    public SquadInfoWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

