using System.Numerics;
using Content.Client.UserInterface;
using Content.Shared._RMC14.Xenonids.Projectile.Parasite;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client._RMC14.Xenonids.Projectile.Parasite;

[GenerateTypedNameReferences]
public sealed partial class ReserveParasitesWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _localization = default!;

    private int _maxRegular;
    private int _maxRoyal;
    private bool _isUpdating;

    public ReserveParasitesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    private SpinBox _reserveBar = default!;
    private SpinBox _royalReserveBar = default!;
    private Button _applyButton = default!;

    public SpinBox ReserveBar => _reserveBar;
    public SpinBox RoyalReserveBar => _royalReserveBar;
    public Button ApplyButton => _applyButton;

    public void SetReserveShown(int number)
    {
        Title = Loc.GetString("rmc-xeno-reserve-parasites-title");

        var vBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4),
            Children =
            {
                new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Children =
                    {
                        new Label
                        {
                            Text = Loc.GetString("rmc-xeno-reserve-parasites-label"),
                            MinSize = new Vector2(130, 0)
                        },
                        (_reserveBar = new SpinBox
                        {
                            Value = 0,
                            HorizontalExpand = true
                        })
                    }
                },
                new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Children =
                    {
                        new Label
                        {
                            Text = Loc.GetString("rmc-xeno-reserve-royal-parasites-label"),
                            MinSize = new Vector2(130, 0)
                        },
                        (_royalReserveBar = new SpinBox
                        {
                            Value = 0,
                            HorizontalExpand = true
                        })
                    }
                },
                (_applyButton = new Button
                {
                    Text = Loc.GetString("rmc-xeno-reserve-parasites-apply"),
                    HorizontalAlignment = HAlignment.Center
                })
            }
        };

        Contents.AddChild(vBox);
        MinSize = new Vector2(300, 0);
    }

    /// <param name="currentRegular">Current number of reserved regular parasites</param>
    /// <param name="currentRoyal">Current number of reserved royal parasites</param>
    /// <param name="maxRegular">Maximum number of regular parasites that can be reserved</param>
    /// <param name="maxRoyal">Maximum number of royal parasites that can be reserved</param>
    public void SetReserveShown(int currentRegular, int currentRoyal, int maxRegular, int maxRoyal)
    {
        _isUpdating = true;

        _maxRegular = maxRegular;
        _maxRoyal = maxRoyal;

        _reserveBar.Value = Math.Min(currentRegular, maxRegular);
        _royalReserveBar.Value = Math.Min(currentRoyal, maxRoyal);

        _isUpdating = false;

        _reserveBar.ValueChanged += args =>
        {
            if (_isUpdating)
                return;

            _isUpdating = true;
            var value = Math.Clamp(args.Value, 0, _maxRegular);
            _reserveBar.Value = value;
            _isUpdating = false;
        };

        _royalReserveBar.ValueChanged += args =>
        {
            if (_isUpdating)
                return;

            _isUpdating = true;
            var value = Math.Clamp(args.Value, 0, _maxRoyal);
            _royalReserveBar.Value = value;
            _isUpdating = false;
        };
    }
}
