- type: rank
  id: RMCRankSergeantMajor
  name: Сержант-майор
  prefix: СержМайр.
  paygrade: E9E

- type: rank
  id: RMCRankMasterGunnerySergeant
  name: Мастер-ганнери-сержант
  prefix: МастГанСерж.
  paygrade: E9

- type: rank
  id: RMCRankFirstSergeant
  name: Первый сержант
  prefix: 1-й Серж.
  paygrade: E8E

- type: rank
  id: RMCRankMasterSergeant
  name: Мастер-сержант
  prefix: МастСерж.
  paygrade: E8

- type: rank
  id: RMCRankGunnerySergeant
  name: Ганнери-сержант
  prefix: ГанСерж.
  paygrade: E7

- type: rank
  id: RMCRankStaffSergeant
  name: Штаб-сержант
  prefix: ШтабСерж.
  paygrade: E6

- type: rank
  id: RMCRankSergeant
  name: Сержант
  prefix: Серж.
  paygrade: E5

- type: rank
  id: RMCRankCorporal
  name: Капрал
  prefix: Кпр.
  paygrade: E4

- type: rank
  id: RMCRankLanceCorporal
  name: Лэнс-капрал
  prefix: ЛнКпр.
  paygrade: E3

- type: rank
  id: RMCRankPrivateFirstClass
  name: Рядовой первого класса
  prefix: Ряд 1-кл.
  paygrade: E2

- type: rank
  id: RMCRankPrivate
  name: Рядовой
  prefix: Ряд.
  paygrade: E1

- type: rank
  id: RMCRankRecruit
  name: Recruit
  prefix: Rct.
  paygrade: E0
