- type: rank
  id: RMCRankNavySeamanRecruit
  name: Матрос-рекрут
  prefix: Рек.
  paygrade: E1

- type: rank
  id: RMCRankNavySeamanApprentice
  name: Младший Матрос
  prefix: Мл. Мат.
  paygrade: E2

- type: rank
  id: RMCRankNavySeaman
  name: Матрос
  prefix: Мат.
  paygrade: E3

- type: rank
  id: RMCRankNavyPettyOfficer3rdClass
  name: Старшина 3-го Класса
  prefix: С3К.
  paygrade: E4

- type: rank
  id: RMCRankNavyPettyOfficer2ndClass
  name: Старшина 2-го Класса
  prefix: С2К.
  paygrade: E5

- type: rank
  id: RMCRankNavyPettyOfficer1stClass
  name: Старшина 1-го Класса
  prefix: С1К.
  paygrade: E6

- type: rank
  id: RMCRankNavyChiefPettyOfficer
  name: Старший Старшина
  prefix: Ст. Стар.
  paygrade: E7

- type: rank
  id: RMCRankNavySeniorChiefPettyOfficer
  name: Главный Старшина
  prefix: Глав. Стар
  paygrade: E8

- type: rank
  id: RMCRankNavyCommandSeniorChiefPettyOfficer
  name: Командующий Старшина
  prefix: Ком. Стар.
  paygrade: E8

- type: rank
  id: RMCRankNavyMasterChiefPettyOfficer
  name: Ведущий Старшина
  prefix: Вед. Стар.
  paygrade: E9

- type: rank
  id: RMCRankNavyCommandMasterChiefPettyOfficer
  name: Командующий Корабельный Старшина
  prefix: ККС.
  paygrade: E9

# Commissioned Officers
- type: rank
  id: RMCRankNavyEnsign
  name: Мичман
  prefix: Мич.
  paygrade: O1

- type: rank
  id: RMCRankNavyLieutenantJuniorGrade
  name: Лейтенант Первого Звена
  prefix: ЛПЗ.
  paygrade: O2

- type: rank
  id: RMCRankNavyLieutenant
  name: Лейтенант
  prefix: Лт.
  paygrade: O3

- type: rank
  id: RMCRankNavyLieutenantCommander
  name: Лейтенант-коммандер
  prefix: Лтк.
  paygrade: O4

- type: rank
  id: RMCRankNavyCommander
  name: Коммандер
  prefix: Ком.
  paygrade: O5

- type: rank
  id: RMCRankNavyCaptain
  name: Капитан
  prefix: Кап.
  paygrade: O6

- type: rank
  id: RMCRankNavyCommodore
  name: Коммандор
  prefix: Коман.
  paygrade: O7

- type: rank
  id: RMCRankNavySeniorCommodore
  name: Старший Коммандор
  prefix: Ст. Коман.
  paygrade: O7

- type: rank
  id: RMCRankNavyRearAdmiralLowerHalf
  name: Контр-Адмирал (Нижнее звено)
  prefix: Кон-Адм.
  paygrade: O8

- type: rank
  id: RMCRankNavyRearAdmiralUpperHalf
  name: Контр-Адмирал (Высшее звено)
  prefix: Кон-Адм.
  paygrade: O9

- type: rank
  id: RMCRankNavyViceAdmiral
  name: Вице-Адмирал
  prefix: Вице-Адм.
  paygrade: O9

- type: rank
  id: RMCRankNavyAdmiral
  name: Адмирал
  prefix: Адмирал
  paygrade: O10

- type: rank
  id: RMCRankNavyChiefOfNavalOperations
  name: Верховный Адмирал ВКС
  prefix: Верх. Адмирал
  paygrade: O10
