- type: rank
  id: RMCRankMajorGeneral
  name: Генерал-майор
  prefix: ГенМайр.
  paygrade: O8

- type: rank
  id: RMCRankBrigadierGeneral
  name: Бригадный генерал
  prefix: БригГен.
  paygrade: O7

- type: rank
  id: RMCRankColonel
  name: Полковник
  prefix: Полк.
  paygrade: O6

- type: rank
  id: RMCRankLieutenantColonel
  name: Подполковник
  prefix: ПодПол.
  paygrade: O5

- type: rank
  id: RMCRankMajor
  name: Майор
  prefix: Майр.
  paygrade: O4

- type: rank
  id: RMCRankCaptain
  name: Капитан
  prefix: Капт.
  paygrade: O3

- type: rank
  id: RMCRankFirstLT
  name: Первый лейтенант
  prefix: 1йЛейт.
  paygrade: O2

- type: rank
  id: RMCRankSecondLT
  name: Второй лейтенант
  prefix: 2йЛейт.
  paygrade: O1

- type: rank
  id: RMCRankChiefWarrantOfficer
  name: Старший уорент офицер
  prefix: СУО.
  paygrade: O0-2

- type: rank
  id: RMCRankWarrantOfficer
  name: Уорент офицер
  prefix: УорОф.
  paygrade: O0-1

# Военная полиция | CCM14

- type: rank
  id: RMCRankMP1
  name: Старший уорент офицер 3-го класса
  prefix: СУО3.
  paygrade: CW3MP

- type: rank
  id: RMCRankMP2
  name: Старший уорент офицер 4-го класса
  prefix: СУО4.
  paygrade: CW4MP

- type: rank
  id: RMCRankMP3
  name: Главный уорент офицер 5-го класса
  prefix: СУО5.
  paygrade: CW5MP

- type: rank
  id: RMCRankMP4
  name: Второй Лейтенант
  prefix: 2йЛт.
  paygrade: O1MP

- type: rank
  id: RMCRankMP5
  name: Первый Лейтенант
  prefix: 1йЛт.
  paygrade: O2MP

- type: rank
  id: RMCRankMP6
  name: Капитан
  prefix: Кап.
  paygrade: O3MP

- type: rank
  id: RMCRankMP7
  name: Комендант
  prefix: Ком.
  paygrade: O4MP