# Whisper
- type: rank
  id: RMCRankProvostSectorMarshal
  name: Маршал сектора
  prefix: ПровМарСек.
  paygrade: O9

# Any admin with high law understanding
- type: rank
  id: RMCRankProvostSeniorMarshal
  name: Старший маршал
  prefix: ПровСтМар.
  paygrade: O8

# Any admin with low law understanding, or wanting a lower rank
- type: rank
  id: RMCRankProvostMarshal
  name: Маршал
  prefix: ПровМар.
  paygrade: O7

# Any whitelisted CO
- type: rank
  id: RMCRankProvostDeputyMarshal
  name: Помощник маршала
  prefix: ПровПомМар.
  paygrade: O6

# Fax responder
- type: rank
  id: RMCRankProvostCommunicationsOfficer
  name: Communications Officer
  prefix: ComOff.

# Any player with high law understanding
- type: rank
  id: RMCRankProvostChiefInspector
  name: Старший инспектор
  prefix: ПровСтИн.
  paygrade: CI

# Any player with medium-low law understanding
- type: rank
  id: RMCRankProvostInspector
  name: Инспектор провост
  prefix: ПровИн.
  paygrade: I

# Any player with low law understanding, with guidance
- type: rank
  id: RMCRankProvostAdvisor
  name: Сержант-майор
  prefix: СержМайр.
  paygrade: E9E

# Any player with given objective, possible team leader
- type: rank
  id: RMCRankProvostProvostTeamLeader
  name: Мастер-сержант
  prefix: МастСерж.
  paygrade: E8

# Any player with given objective, squad member
- type: rank
  id: RMCRankProvostProvostEnforcer
  name: Штаб-сержант
  prefix: ШтабСерж.
  paygrade: E6
