using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CCM.Vehicle.UI;

[GenerateTypedNameReferences]
public sealed partial class VehicleSelectHardpointWindow : FancyWindow
{
    public VehicleSelectHardpointWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
