using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class CMSurgeryWindow : DefaultCMWindow
{
    public CMSurgeryWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

