- type: job
  parent: RMCJobMarineBase
  id: RMCJobSynthetic
  name: rmc-job-name-synth
  description: rmc-job-description-synth
  playTimeTracker: RMCJobSynthetic
  requirements:
#  CCM14 role timers [remove/start]
   - !type:TotalJobsTimeRequirement
     group: CMJobsMedical
     time: 36000 # 10 hours
   - !type:TotalJobsTimeRequirement
     group: CMJobsEngineering
     time: 32400 # 9 hours. CCM14 role timers. RMC: 72000 # 20 hours
   - !type:OverallPlaytimeRequirement
     time: 72000 # 10 hours
#  CCM14 role timers [remove/end]
  ranks:
    RMCRankChiefWarrantOfficer:
    - !type:RoleTimeRequirement
      role: RMCJobSynthetic
      time: 270000 # 75 hours
    RMCRankWarrantOfficer: [ ]
  startingGear: RMCGearSyntheticEquipped
  dummyStartingGear: RMCGearSyntheticEquipped
  icon: "RMCJobIconSynth"
  joinNotifyCrew: true
  whitelisted: true
  supervisors: cm-job-supervisors-co
  accessGroups:
  - ShipMasterAccess
  - Synth
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: TacticalMapUser
      actionId: RMCActionOpenTacticalMapMarine
      layerSets: [TacticalMapSetMarine]
    - type: TacticalMapLayerTracked
      layers: [Marines]
    - type: Skills
      skills:
        RMCSkillCqc: 5
        RMCSkillEndurance: 1
        RMCSkillEngineer: 4
        RMCSkillConstruction: 3
        RMCSkillFirearms: 2
        RMCSkillOverwatch: 1
        RMCSkillMedical: 4
        RMCSkillSurgery: 3
        RMCSkillResearch: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillPilot: 2
        RMCSkillPolice: 2
        RMCSkillFireman: 5
        RMCSkillPowerLoader: 2
        RMCSkillVehicles: 2
        RMCSkillJtac: 3
        RMCSkillIntel: 2
        RMCSkillDomestics: 2
        RMCSkillNavigations: 1
    - type: CMVendorUser
      id: RMCJobSynthetic
      points: 45
      extraPoints:
        ExperimentalTools: 35 # // CCM Changed - Base is 30
    - type: DemoSpecWhitelist
    - type: JobPrefix
      prefix: rmc-job-prefix-synth
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: MeleeWeapon
      soundHit:
        path: /Audio/_RMC14/Weapons/synthpunch1.ogg
        params:
          variation: 0.15
          volume: -1
      angle: 30
      animation: WeaponArcFist
      attackRate: 1
      damage:
        types:
          Blunt: 35
    - type: Synth
  hidden: false

- type: startingGear
  id: RMCGearSyntheticEquipped
  equipment:
    gloves: CMHandsInsulated
    shoes: RMCShoesWhite
    id: RMCIDCardSynth
    ears: RMCHeadsetSynth
    belt: CMBeltUtilityFilled
    pocket1: RMCUniversalRecorder

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSynth
  name: synthetic spawn point
  components:
  - type: SpawnPoint
    job_id: RMCJobSynthetic
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: RMCJobSynthetic
  isHumanoid: true

- type: entity
  id: RMCSynthAddComponents
  categories: [ HideSpawnMenu ]
  components:
  - type: NightVision
    innate: true
    state: half
    onlyHalf: true
    alert: SynthNightVision
  - type: EyeProtection
  - type: Insulated
  - type: RMCLeapProtection
    inherentStunDuration: 3
  - type: ZombieImmune
  - type: ParalyzeImmuneFrom
    whitelist:
      tags:
      - RMCSynthGrabbable

- type: entity
  id: RMCSynthRemoveComponents
  categories: [ HideSpawnMenu ]
  components:
  - type: Infectable
  - type: Hunger
  - type: Thirst
  - type: Perishable
  - type: ThermalRegulator
  - type: Temperature
  - type: Stamina
  - type: DamageForceSay
  - type: Dna
  - type: InjectableSolution
  - type: IVDripTarget
  - type: Woundable
  - type: Wounded
  - type: RMCSuicide
    damage: { }
