using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Shared._RMC14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Maths;
using Robust.Shared.Configuration;
using System.Numerics;
using Robust.Shared.Map;
using System;
using System.Collections.Generic;
using Content.Client.Humanoid;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _protomanager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        private readonly HumanoidProfileEditor _profileEditor;
        private readonly List<(int Slot, ICharacterProfile Profile)> _carouselProfiles = new();
        private int _carouselIndex;
        private EntityUid _leftPreviewEntity;
        private EntityUid _centerPreviewEntity;
        private EntityUid _rightPreviewEntity;
        private EntityUid _leftFarPreviewEntity;
        private EntityUid _rightFarPreviewEntity;
        private string _centerPreviewSpeciesId = SharedHumanoidAppearanceSystem.DefaultSpecies;
        private bool _showClothes = true;
        private bool _deleteCounting;
        private bool _deleteReady;
        private float _deleteCountdown;
        private DragMode _dragMode;
        private Vector2 _interactionStartMouseGlobal;
        private Vector2 _interactionStartPosition;
        private Vector2 _interactionStartSize;
        private Vector2 _manualPosition;
        private bool _hasManualPosition;
        private Vector2 _manualSize;
        private bool _hasManualSize;
        private Vector2 _resizeMinSize = new(960f, 720f);
        private Vector2 _resizeMaxSize = new(float.PositiveInfinity, float.PositiveInfinity);
        private Vector2 _resizeHostSize;
        private readonly Dictionary<SpriteView, float> _hoverRotationTimes = new();
        private readonly HashSet<SpriteView> _hoveredViews = new();
        private StyleNano.UiColorTheme _appliedTheme;
        private float _lastCarouselWidth = -1f;
        private float _lastResponsiveHeight = -1f;
        private CarouselLayoutMode _carouselLayoutMode = CarouselLayoutMode.Five;
        private CompactLayoutTier _compactTier = CompactLayoutTier.Normal;
        private bool _oldLobbyStyle;
        private enum CarouselLayoutMode
        {
            One,
            Three,
            Five
        }

        private enum CompactLayoutTier
        {
            Normal,
            Compact
        }

        [Flags]
        private enum DragMode : byte
        {
            None = 0,
            Move = 1 << 0,
            Top = 1 << 1,
            Bottom = 1 << 2,
            Left = 1 << 3,
            Right = 1 << 4,
        }

        private const float ResizeMarginSize = 7f;
        private const float HeaderDragHeight = 24f;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;
        public event Action? StatsRequested;
        public event Action? CloseRequested;
        public BaseButton CloseButtonControl => _oldLobbyStyle ? OldCloseButton : CloseButton;
        public bool HasManualPosition => _hasManualPosition;
        public Vector2 ManualPosition => _manualPosition;
        public bool HasManualSize => _hasManualSize;
        public Vector2 ManualSize => _manualSize;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _profileEditor = profileEditor;

            ApplyThemeColors(force: true);
            LayoutContainer.SetAnchorPreset(BackgroundPanel, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(MenuBorderPanel, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(NewLayoutRoot, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(OldLayoutRoot, LayoutContainer.LayoutPreset.Wide);
            CharEditor.AddChild(profileEditor);
            LayoutContainer.SetAnchorPreset(CarouselLayout, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(CarouselBackgroundPanel, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(CarouselBorderPanel, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(CarouselSideShade, LayoutContainer.LayoutPreset.Wide);

            NewCharacterButton.OnPressed += _ => CreateCharacter();
            SaveCharacterButton.OnPressed += _ => _profileEditor.RequestSave();
            ResetCharacterButton.OnPressed += _ => _profileEditor.RequestReset();
            ImportCharacterButton.OnPressed += _ => _profileEditor.RequestImport();
            ExportCharacterButton.OnPressed += _ => _profileEditor.RequestExport();
            DeleteCharacterButton.OnPressed += _ => HandleDeletePressed();
            OldNewCharacterButton.OnPressed += _ => CreateCharacter();
            OldSaveCharacterButton.OnPressed += _ => _profileEditor.RequestSave();
            OldResetCharacterButton.OnPressed += _ => _profileEditor.RequestReset();
            OldImportCharacterButton.OnPressed += _ => _profileEditor.RequestImport();
            OldExportCharacterButton.OnPressed += _ => _profileEditor.RequestExport();
            OldDeleteCharacterButton.OnPressed += _ => StatsRequested?.Invoke();
            CloseButton.OnPressed += _ => CloseRequested?.Invoke();
            OldCloseButton.OnPressed += _ => CloseRequested?.Invoke();

            LeftFarNameLabel.AddStyleClass("CharacterCarouselName");
            LeftNameLabel.AddStyleClass("CharacterCarouselName");
            CenterNameLabel.AddStyleClass("CharacterCarouselName");
            CenterNameLabel.AddStyleClass("CharacterCarouselNameSelected");
            RightNameLabel.AddStyleClass("CharacterCarouselName");
            RightFarNameLabel.AddStyleClass("CharacterCarouselName");

            // CCM rework lobby - start
            MouseFilter = MouseFilterMode.Stop;
            LeftFarPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            LeftPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            CenterPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            RightPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            RightFarPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            LeftFarPreviewContainer.OnKeyBindDown += args => PreviewClicked(args, -2);
            LeftPreviewContainer.OnKeyBindDown += args => PreviewClicked(args, -1);
            RightPreviewContainer.OnKeyBindDown += args => PreviewClicked(args, 1);
            RightFarPreviewContainer.OnKeyBindDown += args => PreviewClicked(args, 2);
            OnKeyBindDown += StartInteraction;
            OnKeyBindUp += StopInteraction;
            HookPreviewRotation(LeftFarPreviewContainer, LeftFarPreview);
            HookPreviewRotation(LeftPreviewContainer, LeftPreview);
            HookPreviewRotation(CenterPreviewContainer, CenterPreview, true);
            HookPreviewRotation(RightPreviewContainer, RightPreview);
            HookPreviewRotation(RightFarPreviewContainer, RightFarPreview);
            _profileEditor.ProfileChanged += _ => RefreshCenterPreviewFromEditor();
            _profileEditor.ShowClothesChanged += UpdateShowClothes;
            _profileEditor.ImportExportStateChanged += UpdateImportExportButtons;
            ActionButtonRow.OnResized += UpdateActionButtonLayout;
            TransferActionButtonGroup.OnResized += UpdateActionButtonLayout;
            ApplyLobbyUiStyle(force: true);
            UpdateImportExportButtons();
            // CCM rework lobby - end
        }

        private void UpdateImportExportButtons()
        {
            ImportCharacterButton.Disabled = !_profileEditor.CanImportProfile;
            ExportCharacterButton.Disabled = !_profileEditor.CanExportProfile;
            OldImportCharacterButton.Disabled = !_profileEditor.CanImportProfile;
            OldExportCharacterButton.Disabled = !_profileEditor.CanExportProfile;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            ApplyLobbyUiStyle();
            ApplyThemeColors();
            UpdateCompactLayout();
            if (!_oldLobbyStyle)
                UpdateCarouselLayoutIfNeeded();
            UpdateRotation(args.DeltaSeconds);
            UpdateDeleteCountdown(args.DeltaSeconds);
        }

        // CCM rework lobby - start
        private void ApplyThemeColors(bool force = false)
        {
            var theme = _oldLobbyStyle ? StyleNano.UiColorTheme.Gray : StyleNano.CurrentTheme;
            if (!force && theme == _appliedTheme)
                return;

            _appliedTheme = theme;

            var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var frameColor = _oldLobbyStyle
                ? StyleNano.OldLobbyPanelSoft
                : theme switch
            {
                StyleNano.UiColorTheme.Gray => Color.FromHex("#343942"),
                _ => Color.FromHex("#16301F"),
            };
            var carouselBackgroundColor = _oldLobbyStyle
                ? Color.FromHex("#1F1F23").WithAlpha(0.96f)
                : theme switch
            {
                StyleNano.UiColorTheme.Gray => Color.FromHex("#1B1D22").WithAlpha(0.92f),
                _ => Color.FromHex("#0A2C18").WithAlpha(0.90f),
            };
            var carouselSideShadeColor = Color.Transparent;
            var dividerColor = _oldLobbyStyle
                ? StyleNano.OldLobbyGold.WithAlpha(0.88f)
                : theme switch
            {
                StyleNano.UiColorTheme.Gray => Color.FromHex("#686D76").WithAlpha(0.95f),
                _ => Color.FromHex("#2B7E45").WithAlpha(0.95f),
            };

            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = frameColor
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);
            BackgroundPanel.PanelOverride = back;
            MenuBorderPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
                BorderColor = dividerColor,
                BorderThickness = new Thickness(1)
            };
            CarouselBackgroundPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = carouselBackgroundColor
            };
            CarouselBorderPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
                BorderColor = dividerColor,
                BorderThickness = new Thickness(1)
            };
            CarouselLeftShade.PanelOverride = new StyleBoxFlat { BackgroundColor = carouselSideShadeColor };
            CarouselRightShade.PanelOverride = new StyleBoxFlat { BackgroundColor = carouselSideShadeColor };

            EditorTopDivider.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = dividerColor,
                ContentMarginTopOverride = 2
            };
            OldEditorTopDivider.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = dividerColor,
                ContentMarginTopOverride = 2
            };
            OldVerticalDivider.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = dividerColor,
                ContentMarginTopOverride = 2
            };
            MenuBorderPanel.Visible = !_oldLobbyStyle;
        }

        private void ApplyLobbyUiStyle(bool force = false)
        {
            var oldStyle = string.Equals(_cfg.GetCVar(RMCCVars.RMCLobbyUiStyle), "old", StringComparison.OrdinalIgnoreCase);
            if (!force && oldStyle == _oldLobbyStyle)
                return;

            _oldLobbyStyle = oldStyle;
            NewLayoutRoot.Visible = !oldStyle;
            OldLayoutRoot.Visible = oldStyle;

            if (oldStyle)
            {
                if (_profileEditor.Parent != OldEditorHost)
                {
                    _profileEditor.Orphan();
                    OldEditorHost.AddChild(_profileEditor);
                }
            }
            else if (_profileEditor.Parent != CharEditor)
            {
                _profileEditor.Orphan();
                CharEditor.AddChild(_profileEditor);
            }

            ApplyThemeColors(force: true);
        }
        // CCM rework lobby - end

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            // CCM rework lobby - start
            ResetDeleteState();
            _carouselProfiles.Clear();
            OldCharacters.DisposeAllChildren();
            if (!_preferencesManager.ServerDataLoaded)
                return;

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;
            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();
            var allowedSpecies = new HashSet<string> { "Human", "Avali", "Arachnid", "Moth", "Felinid", "Dwarf" };
            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                if (character is HumanoidCharacterProfile humanoidProfile &&
                    !allowedSpecies.Contains(humanoidProfile.Species.Id))
                {
                    continue;
                }

                _carouselProfiles.Add((slot, character));
                numberOfFullSlots++;

                var characterPickerButton = new CharacterPickerButton(_entManager,
                    _protomanager,
                    characterButtonsGroup,
                    character,
                    slot == selectedSlot);
                OldCharacters.AddChild(characterPickerButton);
                characterPickerButton.OnPressed += _ => SelectCharacter?.Invoke(slot);
                characterPickerButton.OnDeletePressed += () => DeleteCharacter?.Invoke(slot);
            }

            _carouselIndex = 0;
            if (selectedSlot != null)
            {
                var selectedIndex = _carouselProfiles.FindIndex(p => p.Slot == selectedSlot.Value);
                if (selectedIndex >= 0)
                    _carouselIndex = selectedIndex;
            }

            UpdateCarousel();

            var maxSlots = _preferencesManager.Settings?.MaxCharacterSlots ?? 0;
            var fullSlots = _carouselProfiles.Count;
            var canDeleteCharacter = fullSlots > 1;
            NewCharacterButton.Disabled = fullSlots >= maxSlots;
            OldNewCharacterButton.Disabled = numberOfFullSlots >= maxSlots;
            DeleteCharacterButton.Disabled = !canDeleteCharacter;
            OldDeleteCharacterButton.Disabled = false;
            // CCM rework lobby - end
        }

        public void UpdateLayoutBounds(Vector2 hostSize, Vector2 minSize, Vector2 maxSize)
        {
            _resizeHostSize = hostSize;
            _resizeMaxSize = new Vector2(
                MathF.Max(1f, MathF.Min(hostSize.X, maxSize.X)),
                MathF.Max(1f, MathF.Min(hostSize.Y, maxSize.Y)));
            _resizeMinSize = new Vector2(
                MathF.Min(minSize.X, _resizeMaxSize.X),
                MathF.Min(minSize.Y, _resizeMaxSize.Y));

            MinSize = _resizeMinSize;
            MaxSize = _resizeMaxSize;

            if (_hasManualSize)
                _manualSize = ClampSize(_manualSize);

            if (_hasManualPosition)
                _manualPosition = ClampPosition(_manualPosition, _hasManualSize ? _manualSize : Size);
        }

        public Vector2 MeasurePreferredSize(Vector2 availableSize)
        {
            var constrained = Vector2.Max(Vector2.One, availableSize);
            var previousMinSize = MinSize;
            var previousMaxSize = MaxSize;
            var previousSetSize = SetSize;
            var previousCompactTier = _compactTier;
            var previousResponsiveHeight = _lastResponsiveHeight;
            var previousCarouselMode = _carouselLayoutMode;
            var previousCarouselWidth = _lastCarouselWidth;

            try
            {
                ApplyCompactLayoutTier(ResolveCompactLayoutTier(constrained.Y));
                ApplyCarouselLayoutMode(ResolveCarouselLayoutMode(constrained.X));

                MinSize = Vector2.Zero;
                MaxSize = constrained;
                SetSize = new Vector2(float.NaN, float.NaN);
                Measure(constrained);
                return Vector2.Min(DesiredSize, constrained);
            }
            finally
            {
                MinSize = previousMinSize;
                MaxSize = previousMaxSize;
                SetSize = previousSetSize;
                ApplyCompactLayoutTier(previousCompactTier);
                _lastResponsiveHeight = previousResponsiveHeight;
                ApplyCarouselLayoutMode(previousCarouselMode);
                _lastCarouselWidth = previousCarouselWidth;
            }
        }

        private void CreateCharacter()
        {
            var hadSelectedCharacter = _preferencesManager.Preferences?.TryGetSelectedCharacter(out _) == true;
            _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());

            if (!hadSelectedCharacter &&
                _preferencesManager.Preferences is { } prefs &&
                prefs.TryGetSelectedCharacter(out _))
            {
                SelectCharacter?.Invoke(prefs.SelectedCharacterIndex);
                return;
            }

            ReloadCharacterPickers();
        }

        private void StepCarousel(int direction)
        {
            // CCM rework lobby - start
            if (_carouselProfiles.Count <= 1)
                return;

            _carouselIndex = (_carouselIndex + direction) % _carouselProfiles.Count;
            if (_carouselIndex < 0)
                _carouselIndex += _carouselProfiles.Count;

            var slot = _carouselProfiles[_carouselIndex].Slot;
            SelectCharacter?.Invoke(slot);
            // CCM rework lobby - end
        }

        private void PreviewClicked(GUIBoundKeyEventArgs args, int offset)
        {
            // CCM rework lobby - start
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            if (_carouselProfiles.Count <= 1)
                return;

            if (Math.Abs(offset) == 2 && _carouselProfiles.Count < 4)
                return;

            var targetIndex = (_carouselIndex + offset) % _carouselProfiles.Count;
            if (targetIndex < 0)
                targetIndex += _carouselProfiles.Count;

            _carouselIndex = targetIndex;
            SelectCharacter?.Invoke(_carouselProfiles[_carouselIndex].Slot);
            UpdateCarousel();
            args.Handle();
            // CCM rework lobby - end
        }

        private void UpdateCarousel()
        {
            // CCM rework lobby - start
            DeletePreviewEntities();
            _carouselLayoutMode = ResolveCarouselLayoutMode(CarouselPanel.Size.X);
            ApplyCarouselLayoutMode(_carouselLayoutMode);

            if (_carouselProfiles.Count == 0)
            {
                SetPreview(LeftFarPreview, LeftFarNameLabel, null, default);
                SetPreview(LeftPreview, LeftNameLabel, null, default);
                SetPreview(CenterPreview, CenterNameLabel, null, default);
                SetPreview(RightPreview, RightNameLabel, null, default);
                SetPreview(RightFarPreview, RightFarNameLabel, null, default);
                LeftPreviewContainer.Visible = false;
                RightPreviewContainer.Visible = false;
                LeftFarPreviewContainer.Visible = false;
                RightFarPreviewContainer.Visible = false;
                return;
            }

            var center = _carouselProfiles[_carouselIndex];
            _centerPreviewEntity = CreatePreviewEntity(center.Profile, _showClothes);
            SetPreview(CenterPreview, CenterNameLabel, center.Profile, _centerPreviewEntity);
            if (center.Profile is HumanoidCharacterProfile humanoidCenter)
                _centerPreviewSpeciesId = humanoidCenter.Species;
            else
                _centerPreviewSpeciesId = SharedHumanoidAppearanceSystem.DefaultSpecies;

            if (_carouselProfiles.Count == 1 || _carouselLayoutMode == CarouselLayoutMode.One)
            {
                LeftPreviewContainer.Visible = false;
                RightPreviewContainer.Visible = false;
                LeftFarPreviewContainer.Visible = false;
                RightFarPreviewContainer.Visible = false;
                return;
            }

            LeftPreviewContainer.Visible = true;
            RightPreviewContainer.Visible = true;
            LeftFarPreviewContainer.Visible = _carouselLayoutMode == CarouselLayoutMode.Five && _carouselProfiles.Count >= 4;
            RightFarPreviewContainer.Visible = _carouselLayoutMode == CarouselLayoutMode.Five && _carouselProfiles.Count >= 4;

            var leftIndex = (_carouselIndex - 1 + _carouselProfiles.Count) % _carouselProfiles.Count;
            var rightIndex = (_carouselIndex + 1) % _carouselProfiles.Count;
            var leftFarIndex = (_carouselIndex - 2 + _carouselProfiles.Count) % _carouselProfiles.Count;
            var rightFarIndex = (_carouselIndex + 2) % _carouselProfiles.Count;

            var left = _carouselProfiles[leftIndex];
            var right = _carouselProfiles[rightIndex];
            var leftFar = _carouselProfiles[leftFarIndex];
            var rightFar = _carouselProfiles[rightFarIndex];

            _leftPreviewEntity = CreatePreviewEntity(left.Profile);
            _rightPreviewEntity = CreatePreviewEntity(right.Profile);
            if (_carouselLayoutMode == CarouselLayoutMode.Five && _carouselProfiles.Count >= 4)
            {
                _leftFarPreviewEntity = CreatePreviewEntity(leftFar.Profile);
                _rightFarPreviewEntity = CreatePreviewEntity(rightFar.Profile);
            }

            SetPreview(LeftPreview, LeftNameLabel, left.Profile, _leftPreviewEntity, true);
            SetPreview(RightPreview, RightNameLabel, right.Profile, _rightPreviewEntity, true);
            if (_carouselLayoutMode == CarouselLayoutMode.Five && _carouselProfiles.Count >= 4)
            {
                SetPreview(LeftFarPreview, LeftFarNameLabel, leftFar.Profile, _leftFarPreviewEntity, true);
                SetPreview(RightFarPreview, RightFarNameLabel, rightFar.Profile, _rightFarPreviewEntity, true);
            }
            else
            {
                SetPreview(LeftFarPreview, LeftFarNameLabel, null, default);
                SetPreview(RightFarPreview, RightFarNameLabel, null, default);
            }
            // CCM rework lobby - end
        }

        private void SetPreview(SpriteView view, Label label, ICharacterProfile? profile, EntityUid entity, bool dim = false)
        {
            // CCM rework lobby - start
            if (profile == null || entity == default)
            {
                view.SetEntity((EntityUid?) default);
                label.Text = string.Empty;
                return;
            }

            view.SetEntity((EntityUid?) entity);
            label.Text = profile.Name;
            view.Modulate = dim ? new Color(0.84f, 0.84f, 0.84f, 1f) : Color.White;
            label.Modulate = dim ? new Color(0.84f, 0.84f, 0.84f, 1f) : Color.White;
            // CCM rework lobby - end
        }

        private void RefreshCenterPreviewFromEditor(bool forceRespawn = false)
        {
            // CCM rework lobby - start
            var profile = _profileEditor.Profile;
            if (profile == null || _carouselProfiles.Count == 0)
                return;

            if (_profileEditor.CharacterSlot == null)
                return;

            if (_carouselProfiles[_carouselIndex].Slot != _profileEditor.CharacterSlot.Value)
                return;

            if (_centerPreviewEntity == default)
                return;

            var needsHumanoidRespawn = !_entManager.HasComponent<HumanoidAppearanceComponent>(_centerPreviewEntity);
            if (forceRespawn ||
                needsHumanoidRespawn ||
                profile.Species != _centerPreviewSpeciesId ||
                !_entManager.EntityExists(_centerPreviewEntity))
            {
                if (_centerPreviewEntity != default)
                    _entManager.DeleteEntity(_centerPreviewEntity);

                _centerPreviewEntity = CreatePreviewEntity(profile, _showClothes);
                _centerPreviewSpeciesId = profile.Species;
            }
            else
            {
                _entManager.System<HumanoidAppearanceSystem>().LoadProfile(_centerPreviewEntity, profile);
            }

            SetPreview(CenterPreview, CenterNameLabel, profile, _centerPreviewEntity);
            // CCM rework lobby - end
        }

        private EntityUid CreatePreviewEntity(ICharacterProfile profile, bool showClothes = true)
        {
            // CCM rework lobby - start
            if (profile is not HumanoidCharacterProfile humanoid)
            {
                var defaultSpecies = _protomanager.Index<SpeciesPrototype>(SharedHumanoidAppearanceSystem.DefaultSpecies);
                return _entManager.SpawnEntity(defaultSpecies.DollPrototype, MapCoordinates.Nullspace);
            }

            return UserInterfaceManager.GetUIController<LobbyUIController>()
                .LoadProfileEntity(humanoid, null, showClothes);
            // CCM rework lobby - end
        }

        private void UpdateShowClothes(bool showClothes)
        {
            // CCM rework lobby - start
            _showClothes = showClothes;
            RefreshCenterPreviewFromEditor(true);
            // CCM rework lobby - end
        }

        private void DeletePreviewEntities()
        {
            // CCM rework lobby - start
            if (_leftPreviewEntity != default)
                _entManager.DeleteEntity(_leftPreviewEntity);
            if (_centerPreviewEntity != default)
                _entManager.DeleteEntity(_centerPreviewEntity);
            if (_rightPreviewEntity != default)
                _entManager.DeleteEntity(_rightPreviewEntity);
            if (_leftFarPreviewEntity != default)
                _entManager.DeleteEntity(_leftFarPreviewEntity);
            if (_rightFarPreviewEntity != default)
                _entManager.DeleteEntity(_rightFarPreviewEntity);

            _leftPreviewEntity = default;
            _centerPreviewEntity = default;
            _rightPreviewEntity = default;
            _leftFarPreviewEntity = default;
            _rightFarPreviewEntity = default;
            // CCM rework lobby - end
        }

        private void UpdateRotation(float frameTime)
        {
            // CCM rework lobby - start
            if (_hoveredViews.Count == 0)
                return;

            foreach (var view in _hoveredViews)
            {
                _hoverRotationTimes[view] += frameTime;
                var progress = (_hoverRotationTimes[view] % 3f) / 3f;
                var direction = progress switch
                {
                    < 0.25f => Direction.South,
                    < 0.5f => Direction.West,
                    < 0.75f => Direction.North,
                    _ => Direction.East
                };

                view.OverrideDirection = direction;
            }
            // CCM rework lobby - end
        }

        private void HookPreviewRotation(PanelContainer container, SpriteView view, bool keepOrientationOnExit = false)
        {
            // CCM rework lobby - start
            container.OnMouseEntered += _ =>
            {
                _hoveredViews.Add(view);
                if (!keepOrientationOnExit || !_hoverRotationTimes.ContainsKey(view))
                {
                    _hoverRotationTimes[view] = 0f;
                    view.OverrideDirection = Direction.South;
                }
            };

            container.OnMouseExited += _ =>
            {
                _hoveredViews.Remove(view);
                if (!keepOrientationOnExit)
                {
                    _hoverRotationTimes[view] = 0f;
                    view.OverrideDirection = Direction.South;
                }
            };
            // CCM rework lobby - end
        }

        private void HandleDeletePressed()
        {
            // CCM rework lobby - start
            if (_carouselProfiles.Count == 0)
                return;

            if (_deleteReady)
            {
                DeleteCharacter?.Invoke(_carouselProfiles[_carouselIndex].Slot);
                ResetDeleteState();
                return;
            }

            _deleteCounting = true;
            _deleteCountdown = 3f;
            _deleteReady = false;
            var warning = new Color(1f, 0.7f, 0.7f, 1f);
            DeleteCharacterButton.Modulate = warning;
            UpdateDeleteText();
            // CCM rework lobby - end
        }

        private void UpdateDeleteCountdown(float frameTime)
        {
            // CCM rework lobby - start
            if (!_deleteCounting)
                return;

            _deleteCountdown -= frameTime;
            if (_deleteCountdown <= 0f)
            {
                _deleteCounting = false;
                _deleteReady = true;
                var confirm = new Color(1f, 0.3f, 0.3f, 1f);
                var text = Loc.GetString("character-setup-gui-delete-confirm");
                DeleteCharacterButton.Modulate = confirm;
                DeleteCharacterButton.Text = text;
                return;
            }

            UpdateDeleteText();
            // CCM rework lobby - end
        }

        private void UpdateDeleteText()
        {
            // CCM rework lobby - start
            var seconds = Math.Max(1, (int) MathF.Ceiling(_deleteCountdown));
            var text = Loc.GetString("character-setup-gui-delete-confirm-countdown", ("seconds", seconds));
            DeleteCharacterButton.Text = text;
            // CCM rework lobby - end
        }

        private void ResetDeleteState()
        {
            // CCM rework lobby - start
            _deleteCounting = false;
            _deleteReady = false;
            _deleteCountdown = 0f;
            DeleteCharacterButton.Modulate = Color.White;
            OldDeleteCharacterButton.Modulate = Color.White;
            DeleteCharacterButton.Text = Loc.GetString("character-setup-gui-delete-character");
            OldDeleteCharacterButton.Text = Loc.GetString("character-setup-gui-character-setup-stats-button");
            // CCM rework lobby - end
        }

        private void StartInteraction(GUIBoundKeyEventArgs args)
        {
            // CCM rework lobby - start
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _dragMode = GetDragModeFor(args.RelativePosition);
            var global = args.PointerLocation.Position / UIScale;
            if (_oldLobbyStyle && _dragMode == DragMode.None)
            {
                var hitControl = UserInterfaceManager.MouseGetControl(args.PointerLocation);
                if (CanStartOldLayoutFreeDrag(hitControl))
                    _dragMode = DragMode.Move;
            }

            if (_dragMode == DragMode.None)
                return;

            if (_dragMode == DragMode.Move && IsPointOverCloseButton(global))
            {
                _dragMode = DragMode.None;
                return;
            }

            _interactionStartMouseGlobal = args.PointerLocation.Position / UIScale;
            _interactionStartPosition = Position;
            _interactionStartSize = Size;

            args.Handle();
            // CCM rework lobby - end
        }

        private bool CanStartOldLayoutFreeDrag(Control? hitControl)
        {
            for (var control = hitControl; control != null && control != this; control = control.Parent)
            {
                if (IsInteractiveDragBlocker(control))
                    return false;
            }

            return true;
        }

        private static bool IsInteractiveDragBlocker(Control control)
        {
            return control is BaseButton or
                   CheckBox or
                   LineEdit or
                   OptionButton or
                   ScrollBar or
                   Slider or
                   SplitContainer or
                   TabContainer or
                   TextEdit or
                   ItemList or
                   Tree;
        }

        private void StopInteraction(GUIBoundKeyEventArgs args)
        {
            // CCM rework lobby - start
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _dragMode = DragMode.None;
            DefaultCursorShape = CursorShape.Arrow;
            args.Handle();
            // CCM rework lobby - end
        }

        protected override void MouseMove(GUIMouseMoveEventArgs args)
        {
            base.MouseMove(args);
            UpdateDragOrResize(args);
        }

        protected override void MouseExited()
        {
            base.MouseExited();

            if (_dragMode == DragMode.None)
                DefaultCursorShape = CursorShape.Arrow;
        }

        private void UpdateDragOrResize(GUIMouseMoveEventArgs args)
        {
            if (Parent == null)
                return;

            if (_dragMode == DragMode.None)
            {
                UpdateResizeCursor(args.RelativePosition);
                return;
            }

            var delta = args.GlobalPosition - _interactionStartMouseGlobal;
            if (_dragMode == DragMode.Move)
            {
                var newPos = ClampPosition(_interactionStartPosition + delta, _interactionStartSize);
                LayoutContainer.SetPosition(this, newPos);
                _manualPosition = newPos;
                _hasManualPosition = true;
                return;
            }

            var minSize = _resizeMinSize;
            var maxSize = _resizeMaxSize;
            var hostSize = _resizeHostSize.X > 0f && _resizeHostSize.Y > 0f
                ? _resizeHostSize
                : Parent.Size;

            var left = _interactionStartPosition.X;
            var top = _interactionStartPosition.Y;
            var right = _interactionStartPosition.X + _interactionStartSize.X;
            var bottom = _interactionStartPosition.Y + _interactionStartSize.Y;

            if ((_dragMode & DragMode.Top) != 0)
            {
                top = Math.Clamp(
                    _interactionStartPosition.Y + delta.Y,
                    MathF.Max(0f, bottom - maxSize.Y),
                    bottom - minSize.Y);
            }
            else if ((_dragMode & DragMode.Bottom) != 0)
            {
                bottom = Math.Clamp(
                    _interactionStartPosition.Y + _interactionStartSize.Y + delta.Y,
                    _interactionStartPosition.Y + minSize.Y,
                    MathF.Min(hostSize.Y, _interactionStartPosition.Y + maxSize.Y));
            }

            if ((_dragMode & DragMode.Left) != 0)
            {
                left = Math.Clamp(
                    _interactionStartPosition.X + delta.X,
                    MathF.Max(0f, right - maxSize.X),
                    right - minSize.X);
            }
            else if ((_dragMode & DragMode.Right) != 0)
            {
                right = Math.Clamp(
                    _interactionStartPosition.X + _interactionStartSize.X + delta.X,
                    _interactionStartPosition.X + minSize.X,
                    MathF.Min(hostSize.X, _interactionStartPosition.X + maxSize.X));
            }

            var resizedPos = new Vector2(left, top);
            var newSize = new Vector2(right - left, bottom - top);

            LayoutContainer.SetPosition(this, resizedPos);
            SetSize = newSize;
            _manualPosition = resizedPos;
            _manualSize = newSize;
            _hasManualPosition = true;
            _hasManualSize = true;
        }

        private DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.None;

            if (_resizeHostSize.X > 0f && _resizeHostSize.Y > 0f)
            {
                if (relativeMousePos.Y < ResizeMarginSize)
                    mode |= DragMode.Top;
                else if (relativeMousePos.Y > Size.Y - ResizeMarginSize)
                    mode |= DragMode.Bottom;

                if (relativeMousePos.X < ResizeMarginSize)
                    mode |= DragMode.Left;
                else if (relativeMousePos.X > Size.X - ResizeMarginSize)
                    mode |= DragMode.Right;
            }

            if (mode == DragMode.None && relativeMousePos.Y < MathF.Max(HeaderDragHeight, WindowHeader.Size.Y))
                mode = DragMode.Move;

            return mode;
        }

        private bool IsPointOverCloseButton(Vector2 globalPoint)
        {
            var closeMin = CloseButton.GlobalPosition;
            var closeMax = closeMin + CloseButton.Size;
            return globalPoint.X >= closeMin.X && globalPoint.X <= closeMax.X &&
                   globalPoint.Y >= closeMin.Y && globalPoint.Y <= closeMax.Y;
        }

        private void UpdateResizeCursor(Vector2 relativeMousePos)
        {
            var previewDragMode = GetDragModeFor(relativeMousePos) & ~DragMode.Move;
            DefaultCursorShape = previewDragMode switch
            {
                DragMode.Top or DragMode.Bottom => CursorShape.VResize,
                DragMode.Left or DragMode.Right => CursorShape.HResize,
                DragMode.Top | DragMode.Left or
                DragMode.Top | DragMode.Right or
                DragMode.Bottom | DragMode.Left or
                DragMode.Bottom | DragMode.Right => CursorShape.Crosshair,
                _ => CursorShape.Arrow,
            };
        }

        private Vector2 ClampSize(Vector2 size)
        {
            var hostSize = _resizeHostSize.X > 0f && _resizeHostSize.Y > 0f
                ? _resizeHostSize
                : Parent?.Size ?? size;
            var maxSize = new Vector2(
                MathF.Max(_resizeMinSize.X, MathF.Min(_resizeMaxSize.X, hostSize.X)),
                MathF.Max(_resizeMinSize.Y, MathF.Min(_resizeMaxSize.Y, hostSize.Y)));

            return new Vector2(
                Math.Clamp(size.X, _resizeMinSize.X, maxSize.X),
                Math.Clamp(size.Y, _resizeMinSize.Y, maxSize.Y));
        }

        private Vector2 ClampPosition(Vector2 position, Vector2 size)
        {
            var hostSize = _resizeHostSize.X > 0f && _resizeHostSize.Y > 0f
                ? _resizeHostSize
                : Parent?.Size ?? Vector2.Zero;
            var maxPosition = new Vector2(
                MathF.Max(0f, hostSize.X - size.X),
                MathF.Max(0f, hostSize.Y - size.Y));

            return new Vector2(
                Math.Clamp(position.X, 0f, maxPosition.X),
                Math.Clamp(position.Y, 0f, maxPosition.Y));
        }

        private void UpdateCarouselLayoutIfNeeded()
        {
            // CCM rework lobby - start
            var width = CarouselPanel.Size.X;
            if (width <= 0f)
                return;

            if (Math.Abs(width - _lastCarouselWidth) < 1f)
                return;

            _lastCarouselWidth = width;
            UpdateCarousel();
            // CCM rework lobby - end
        }

        private void UpdateCompactLayout()
        {
            var height = Size.Y > 1f
                ? Size.Y
                : Parent?.Size.Y ?? 0f;
            if (height <= 0f)
                return;

            var tier = ResolveCompactLayoutTier(height);

            if (tier == _compactTier && Math.Abs(height - _lastResponsiveHeight) < 1f)
                return;

            _lastResponsiveHeight = height;
            ApplyCompactLayoutTier(tier);
        }

        private CompactLayoutTier ResolveCompactLayoutTier(float height)
        {
            return height <= 700f
                ? CompactLayoutTier.Compact
                : CompactLayoutTier.Normal;
        }

        private void ApplyCompactLayoutTier(CompactLayoutTier tier)
        {
            _compactTier = tier;
            var compact = tier == CompactLayoutTier.Compact;
            NewLayoutRoot.Margin = compact ? new Thickness(6) : new Thickness(8);
            NewLayoutRoot.SeparationOverride = compact ? 6 : 8;
            BodyStack.SeparationOverride = compact ? 6 : 8;
            CarouselPanel.MinSize = new Vector2(CarouselPanel.MinSize.X, compact ? 168f : 200f);
            CarouselPreviewRow.Margin = compact ? new Thickness(8) : new Thickness(12);
            CarouselLeftShade.MinWidth = compact ? 96f : 140f;
            CarouselRightShade.MinWidth = compact ? 96f : 140f;
            PrimaryActionButtonGroup.SeparationOverride = compact ? 6 : 10;
            TransferActionButtonGroup.SeparationOverride = compact ? 6 : 10;
            OldPrimaryActionButtonGroup.SeparationOverride = compact ? 3 : 4;
            OldTransferActionButtonGroup.SeparationOverride = compact ? 3 : 4;

            var actionButtonHeight = compact ? 32f : 36f;
            ActionButtonRow.MinSize = new Vector2(ActionButtonRow.MinSize.X, actionButtonHeight + 6f);
            ActionButtonRow.Margin = compact
                ? new Thickness(6f, 1f, 6f, 1f)
                : new Thickness(6f, 2f, 6f, 2f);
            NewCharacterButton.MinSize = new Vector2(NewCharacterButton.MinSize.X, actionButtonHeight);
            SaveCharacterButton.MinSize = new Vector2(SaveCharacterButton.MinSize.X, actionButtonHeight);
            ResetCharacterButton.MinSize = new Vector2(ResetCharacterButton.MinSize.X, actionButtonHeight);
            ImportCharacterButton.MinSize = new Vector2(ImportCharacterButton.MinSize.X, actionButtonHeight);
            ExportCharacterButton.MinSize = new Vector2(ExportCharacterButton.MinSize.X, actionButtonHeight);
            DeleteCharacterButton.MinSize = new Vector2(DeleteCharacterButton.MinSize.X, actionButtonHeight);
            OldNewCharacterButton.MinSize = new Vector2(OldNewCharacterButton.MinSize.X, actionButtonHeight);
            OldSaveCharacterButton.MinSize = new Vector2(OldSaveCharacterButton.MinSize.X, actionButtonHeight);
            OldResetCharacterButton.MinSize = new Vector2(OldResetCharacterButton.MinSize.X, actionButtonHeight);
            OldImportCharacterButton.MinSize = new Vector2(OldImportCharacterButton.MinSize.X, actionButtonHeight);
            OldExportCharacterButton.MinSize = new Vector2(OldExportCharacterButton.MinSize.X, actionButtonHeight);
            OldDeleteCharacterButton.MinSize = new Vector2(OldDeleteCharacterButton.MinSize.X, actionButtonHeight);

            if (_oldLobbyStyle)
            {
                OldLayoutRoot.Margin = compact ? new Thickness(6) : new Thickness(10);
                OldCharactersScroll.MinSize = new Vector2(compact ? 360f : 420f, 0f);
                OldCharactersScroll.Margin = compact ? new Thickness(6, 6, 0, 0) : new Thickness(8, 8, 0, 0);
                OldEditorHost.Margin = compact ? new Thickness(8, 6, 0, 0) : new Thickness(10, 8, 0, 0);
                OldWindowHeader.MinSize = new Vector2(0f, compact ? 40f : 48f);
                OldNewCharacterButton.MinSize = new Vector2(MathF.Max(OldNewCharacterButton.MinSize.X, compact ? 116f : 128f), actionButtonHeight);
                OldSaveCharacterButton.MinSize = new Vector2(MathF.Max(OldSaveCharacterButton.MinSize.X, compact ? 116f : 128f), actionButtonHeight);
                OldResetCharacterButton.MinSize = new Vector2(MathF.Max(OldResetCharacterButton.MinSize.X, compact ? 116f : 128f), actionButtonHeight);
                OldImportCharacterButton.MinSize = new Vector2(MathF.Max(OldImportCharacterButton.MinSize.X, compact ? 116f : 128f), actionButtonHeight);
                OldExportCharacterButton.MinSize = new Vector2(MathF.Max(OldExportCharacterButton.MinSize.X, compact ? 116f : 128f), actionButtonHeight);
                OldDeleteCharacterButton.MinSize = new Vector2(MathF.Max(OldDeleteCharacterButton.MinSize.X, compact ? 128f : 144f), actionButtonHeight);
                OldCloseButton.MinSize = new Vector2(MathF.Max(OldCloseButton.MinSize.X, compact ? 96f : 112f), actionButtonHeight);
            }

            _lastCarouselWidth = -1f;
            UpdateActionButtonLayout();
        }

        private void UpdateActionButtonLayout()
        {
            if (_oldLobbyStyle)
                return;

            var transferWidth = MathF.Max(TransferActionButtonGroup.Size.X, TransferActionButtonGroup.DesiredSize.X);
            TransferActionButtonSpacer.MinWidth = transferWidth;
        }

        private CarouselLayoutMode ResolveCarouselLayoutMode(float width)
        {
            // CCM rework lobby - start
            if (_carouselProfiles.Count <= 1)
                return CarouselLayoutMode.One;

            if (width <= 0f)
                return _carouselProfiles.Count >= 4 ? CarouselLayoutMode.Five : CarouselLayoutMode.Three;

            const float minThreeWidth = 640f;
            const float minFiveWidth = 980f;

            if (width < minThreeWidth)
                return CarouselLayoutMode.One;

            if (_carouselProfiles.Count >= 4 && width >= minFiveWidth)
                return CarouselLayoutMode.Five;

            return CarouselLayoutMode.Three;
            // CCM rework lobby - end
        }

        private void ApplyCarouselLayoutMode(CarouselLayoutMode mode)
        {
            // CCM rework lobby - start
            _carouselLayoutMode = mode;
            var compactFactor = _compactTier == CompactLayoutTier.Compact ? 0.9f : 1f;
            var compactSpriteFactor = _compactTier == CompactLayoutTier.Compact ? 0.92f : 1f;

            switch (mode)
            {
                case CarouselLayoutMode.One:
                    CarouselPreviewRow.SeparationOverride = _compactTier == CompactLayoutTier.Compact ? 6 : 8;
                    CenterPreviewContainer.MinSize = new Vector2(200f, 170f) * compactFactor;
                    CenterPreview.Scale = new Vector2(6.4f, 6.4f) * compactSpriteFactor;
                    LeftPreviewContainer.MinSize = new Vector2(140f, 130f) * compactFactor;
                    RightPreviewContainer.MinSize = new Vector2(140f, 130f) * compactFactor;
                    LeftFarPreviewContainer.MinSize = new Vector2(120f, 120f) * compactFactor;
                    RightFarPreviewContainer.MinSize = new Vector2(120f, 120f) * compactFactor;
                    LeftPreview.Scale = new Vector2(5.2f, 5.2f) * compactSpriteFactor;
                    RightPreview.Scale = new Vector2(5.2f, 5.2f) * compactSpriteFactor;
                    LeftFarPreview.Scale = new Vector2(4.6f, 4.6f) * compactSpriteFactor;
                    RightFarPreview.Scale = new Vector2(4.6f, 4.6f) * compactSpriteFactor;
                    break;
                case CarouselLayoutMode.Three:
                    CarouselPreviewRow.SeparationOverride = _compactTier == CompactLayoutTier.Compact ? 8 : 10;
                    CenterPreviewContainer.MinSize = new Vector2(200f, 170f) * compactFactor;
                    CenterPreview.Scale = new Vector2(6.6f, 6.6f) * compactSpriteFactor;
                    LeftPreviewContainer.MinSize = new Vector2(150f, 140f) * compactFactor;
                    RightPreviewContainer.MinSize = new Vector2(150f, 140f) * compactFactor;
                    LeftFarPreviewContainer.MinSize = new Vector2(120f, 120f) * compactFactor;
                    RightFarPreviewContainer.MinSize = new Vector2(120f, 120f) * compactFactor;
                    LeftPreview.Scale = new Vector2(5.6f, 5.6f) * compactSpriteFactor;
                    RightPreview.Scale = new Vector2(5.6f, 5.6f) * compactSpriteFactor;
                    LeftFarPreview.Scale = new Vector2(4.8f, 4.8f) * compactSpriteFactor;
                    RightFarPreview.Scale = new Vector2(4.8f, 4.8f) * compactSpriteFactor;
                    break;
                default:
                    CarouselPreviewRow.SeparationOverride = _compactTier == CompactLayoutTier.Compact ? 10 : 12;
                    CenterPreviewContainer.MinSize = new Vector2(220f, 180f) * compactFactor;
                    CenterPreview.Scale = new Vector2(7f, 7f) * compactSpriteFactor;
                    LeftPreviewContainer.MinSize = new Vector2(180f, 160f) * compactFactor;
                    RightPreviewContainer.MinSize = new Vector2(180f, 160f) * compactFactor;
                    LeftFarPreviewContainer.MinSize = new Vector2(160f, 140f) * compactFactor;
                    RightFarPreviewContainer.MinSize = new Vector2(160f, 140f) * compactFactor;
                    LeftPreview.Scale = new Vector2(6.4f, 6.4f) * compactSpriteFactor;
                    RightPreview.Scale = new Vector2(6.4f, 6.4f) * compactSpriteFactor;
                    LeftFarPreview.Scale = new Vector2(5.1f, 5.1f) * compactSpriteFactor;
                    RightFarPreview.Scale = new Vector2(5.1f, 5.1f) * compactSpriteFactor;
                    break;
            }
            // CCM rework lobby - end
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (!disposing)
                return;

            // CCM rework lobby - start
            DeletePreviewEntities();
            // CCM rework lobby - end
        }
    }
}
