// CM14 rework: non-RMC edit marker.
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterSetupGuiSavePanel : DefaultCMWindow
{
    public CharacterSetupGuiSavePanel()
    {
        RobustXamlLoader.Load(this);

        Title = string.Empty;
        HeaderPanel.Visible = false;

        CancelButton.OnPressed += _ =>
        {
            Close();
        };

        CloseButton.Visible = false;
    }
}

