using System;
using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared._RMC14.CCVar;
using Content.Client.UserInterface.Controls;
using Prometheus;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public Button CharacterSetupButton => CharacterSetup;
    public Button CustomizationButton => Customization;

    private EntityUid? _previewDummy;
    private bool _oldStyleApplied;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyButtonStyle();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        ApplyButtonStyle();
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        Summary.Text = value;
    }

    public void SetSprite(EntityUid uid)
    {
        _previewDummy = uid;

        ViewBox.DisposeAllChildren();
        var spriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(4f, 4f),
            MaxSize = new Vector2(112, 112),
            Stretch = SpriteView.StretchMode.Fill,
        };
        spriteView.SetEntity(uid);
        ViewBox.AddChild(spriteView);
    }

    public void ClearPreview()
    {
        _previewDummy = null;
        ViewBox.DisposeAllChildren();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _previewDummy = null;
    }

    private void ApplyButtonStyle()
    {
        var oldStyle = string.Equals(_cfg.GetCVar(RMCCVars.RMCLobbyUiStyle), "old", StringComparison.OrdinalIgnoreCase);
        if (_oldStyleApplied == oldStyle)
            return;

        _oldStyleApplied = oldStyle;

        if (oldStyle)
        {
            CharacterSetup.RemoveStyleClass("LobbyMenuButton");
            CharacterSetup.RemoveStyleClass("ButtonBig");
            CharacterSetup.AddStyleClass("OldLobbyButton");
            Customization.RemoveStyleClass("LobbyMenuButton");
            Customization.RemoveStyleClass("ButtonBig");
            Customization.AddStyleClass("OldLobbyButton");
            Customization.Visible = true;
            Summary.AddStyleClass("OldLobbyMutedText");
            Summary.FontColorOverride = StyleNano.OldLobbyMuted;
            ApplyOldHeaderStyle();
        }
        else
        {
            CharacterSetup.RemoveStyleClass("OldLobbyButton");
            CharacterSetup.AddStyleClass("LobbyMenuButton");
            Customization.RemoveStyleClass("OldLobbyButton");
            Customization.Visible = false;
            Summary.RemoveStyleClass("OldLobbyMutedText");
            Summary.FontColorOverride = null;
            ClearOldHeaderStyle();
        }
    }

    private void ApplyOldHeaderStyle()
    {
        if (Header.Children.FirstOrDefault() is not PanelContainer panel)
            return;

        panel.PanelOverride = null;

        if (panel.Children.FirstOrDefault() is not Label label)
            return;

        label.FontColorOverride = StyleNano.OldLobbyGold;
        PreviewCard.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = StyleNano.OldLobbyPanelSoft.WithAlpha(0.92f),
            BorderColor = StyleNano.OldLobbyButtonBorderHover.WithAlpha(0.82f),
            BorderThickness = new Thickness(1f)
        };
    }

    private void ClearOldHeaderStyle()
    {
        if (Header.Children.FirstOrDefault() is not PanelContainer panel)
            return;

        panel.PanelOverride = null;

        if (panel.Children.FirstOrDefault() is not Label label)
            return;

        label.FontColorOverride = null;
        PreviewCard.PanelOverride = null;
    }
}
