using Content.Client._RMC14.Roadmap;
using Content.Client._RMC14.RMCPlaytimeStats;
using Content.Client._RMC14.LinkAccount;
using Content.Client._CCM.Achievements;
using Content.Client._CCM.Sponsorship;
using Content.Client._CCM.Stats;
using Content.Client.CrewManifest;
using Content.Client.GameTicking.Managers;
using Content.Client._RMC14.Lobby;
using Content.Client.Info;
using Content.Client.Interaction;
using Content.Client.LateJoin;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Client.Voting.UI;
using Content.Client.Lobby;
using Content.Shared._RMC14.CCVar;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Animations;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.State;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Animations;
using Robust.Shared.Configuration;
using Robust.Shared.Network;
using Robust.Shared.Localization;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using System;
using System.Collections.Generic;
using System.Numerics;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;
        [Dependency] private readonly LinkAccountManager _linkAccount = default!;
        [Dependency] private readonly IStateManager _stateManager = default!;
        [Dependency] private readonly IUriOpener _uriOpener = default!;

        private RulesAndInfoWindow? _tutorialWindow;
        private LateJoinGui? _lateJoinWindow;
        private VoteCallMenu? _voteMenu;
        private ObserveWarningWindow? _observeWindow;
        private CCMStatisticsWindow? _statsWindow;
        private CCMLeaderboardWindow? _leaderboardWindow;
        private readonly LobbyOldLayout _oldLayout;
        private bool _suppressReadyToggle;
        private bool _leftMenuVisible = true;
        private readonly DragDropHelper<Control> _leftMenuDragHelper;
        private bool _leftMenuDragStarted;
        private Vector2 _leftMenuDragOffset;
        private bool _leftMenuAnchorInitialized;
        private bool _leftMenuAutoCenter = true;
        private Vector2 _leftMenuLastGlobal;
        private Vector2 _voteLastSize;
        private Vector2 _lastResponsiveMainSize;
        private Vector2 _lastResponsiveLeftSize;
        private bool _compactLobbyLayout;
        private bool _oldRightPanelVisible = true;

        private const string LeftMenuHideAnimationKey = "lobby-left-menu-hide";
        private const string LeftMenuShowAnimationKey = "lobby-left-menu-show";
        private const float LeftMenuCenterYOffsetPercent = 0.06f;
        private const float LobbyCenterWidthMin = 420f;
        private const float LobbyCenterWidthMax = 460f;
        private const float LobbyTaskbarWidthMin = 500f;
        private const float LobbyTaskbarWidthMax = 760f;
        private const float LobbyTaskbarHeightDefault = 84f;
        private const float LobbyTaskbarHeightCompact = 72f;
        private const float LobbyEdgePaddingDefault = 12f;
        private const float LobbyEdgePaddingCompact = 8f;
        private const string LobbyUiStyleNewClass = "LobbyUiStyleNew";
        private const string LobbyUiStyleOldClass = "LobbyUiStyleOld";

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetNano;
            _oldLayout = new LobbyOldLayout();
            OldLayoutHost.AddChild(_oldLayout);
            _leftMenuDragHelper = new DragDropHelper<Control>(OnBeginLeftMenuDrag, OnContinueLeftMenuDrag, OnEndLeftMenuDrag);
            LayoutContainer.SetAnchorPreset(RootContainer, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(DefaultState, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(CharacterSetupState, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(OldLayoutHost, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(_oldLayout.CharacterSetupState, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(BackgroundViewportArea, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(Background, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(LeftContentArea, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(ConsoleBackground, LayoutPreset.Wide);
            LayoutContainer.SetAnchorAndMarginPreset(CenterMenuGlow, LayoutPreset.Center);
            LayoutContainer.SetAnchorPreset(VoteContainer, LayoutPreset.TopLeft); // # CCM priority rework
            LayoutContainer.SetAnchorAndMarginPreset(LobbyMusicPanel, LayoutPreset.TopRight, margin: 6);
            LayoutContainer.SetGrowHorizontal(LobbyMusicPanel, LayoutContainer.GrowDirection.Begin);

            SetupChatStyles();
            SetupLeftMenuToggle();
            SetupTaskbarLabelHover();
            SetupButtonIconHover();

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            GuidesButton.OnPressed += _ => UserInterfaceManager.GetUIController<GuidebookUIController>().ToggleGuidebook();
            UpdatesButton.OnPressed += _ => UserInterfaceManager.GetUIController<RoadmapUIController>().ToggleRoadmap();
            LinkDiscordButton.OnPressed += _ => UserInterfaceManager.GetUIController<DiscordOAuthUIController>().OpenLink();
            TaskbarMenuButton.OnPressed += _ => ToggleLeftMenu(!_leftMenuVisible);
            TaskbarRatingButton.OnPressed += _ => ToggleLeaderboard();
            TaskbarAchievementsButton.OnPressed += _ => UserInterfaceManager.GetUIController<CCMAchievementsUIController>().ToggleWindow();
            TaskbarDonateButton.OnPressed += _ => UserInterfaceManager.GetUIController<CCMSponsorshipUIController>().ToggleWindow();
            TaskbarCustomizationButton.OnPressed += _ => UserInterfaceManager.GetUIController<CCMCustomizationUIController>().ToggleWindow();

            StatsButton.OnPressed += _ => OpenStats();
            SetupCharacterButton.OnPressed += _ => OpenCharacterSetup();
            PollsButton.OnPressed += _ => OpenPolls();
            ObserveButton.OnPressed += _ => OpenObserve();
            ReadyButton.OnToggled += args => ToggleReady(args.Pressed);
            JoinUsmcButton.OnPressed += _ => OpenLateJoin();
            JoinHiveButton.OnPressed += _ => UserInterfaceManager.GetUIController<RMCLobbyUIController>().OpenJoinXenoWindow();
            CrewManifestButton.OnPressed += _ => OpenCrewManifest();

            _oldLayout.LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            _oldLayout.OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            _oldLayout.DiscordInfoButton.OnPressed += _ => OpenInfoLink(CCVars.InfoLinksDiscord);
            _oldLayout.WikiButton.OnPressed += _ => OpenInfoLink(CCVars.InfoLinksWiki);
            _oldLayout.GuidesButton.OnPressed += _ => UserInterfaceManager.GetUIController<GuidebookUIController>().ToggleGuidebook();
            _oldLayout.UpdatesButton.OnPressed += _ => UserInterfaceManager.GetUIController<RoadmapUIController>().ToggleRoadmap();
            _oldLayout.LinkDiscordButton.OnPressed += _ => UserInterfaceManager.GetUIController<DiscordOAuthUIController>().OpenLink();
            _oldLayout.StatsButton.OnPressed += _ => ToggleLeaderboard();
            _oldLayout.PollsButton.OnPressed += _ => OpenPolls();
            _oldLayout.ObserveButton.OnPressed += _ => OpenObserve();
            _oldLayout.ReadyButton.OnToggled += args => ToggleReady(args.Pressed);
            _oldLayout.CharacterPreview.CharacterSetupButton.OnPressed += _ => OpenCharacterSetup();
            _oldLayout.CharacterPreview.CustomizationButton.OnPressed += _ => UserInterfaceManager.GetUIController<CCMCustomizationUIController>().ToggleWindow();
            _oldLayout.JoinUsmcButton.OnPressed += _ => OpenLateJoin();
            _oldLayout.JoinHiveButton.OnPressed += _ => UserInterfaceManager.GetUIController<RMCLobbyUIController>().OpenJoinXenoWindow();
            _oldLayout.AchievementsButton.OnPressed += _ => UserInterfaceManager.GetUIController<CCMAchievementsUIController>().ToggleWindow();
            _oldLayout.SponsorshipButton.OnPressed += _ => UserInterfaceManager.GetUIController<CCMSponsorshipUIController>().ToggleWindow();
            _oldLayout.CollapseButton.OnPressed += _ => ToggleOldPanel(false);
            _oldLayout.ExpandButton.OnPressed += _ => ToggleOldPanel(true);

            UpdateReadyLabel(ReadyButton.Pressed);
            ApplyLobbyTheme(_cfg.GetCVar(RMCCVars.RMCLobbyCrtEnabled));
            _cfg.OnValueChanged(RMCCVars.RMCLobbyCrtEnabled, ApplyLobbyTheme);
            _cfg.OnValueChanged(RMCCVars.RMCUIColorTheme,
                _ => ApplyLobbyTheme(_cfg.GetCVar(RMCCVars.RMCLobbyCrtEnabled)));
            _cfg.OnValueChanged(RMCCVars.RMCLobbyUiStyle, ApplyLobbyUiStyleClasses, true);
            if (_cfg.GetCVar(RMCCVars.RMCLobbyInvertSides))
                _cfg.SetCVar(RMCCVars.RMCLobbyInvertSides, false);
            _linkAccount.Updated += UpdateDiscordLinkState;
            UpdateDiscordLinkState();
            ApplyLobbyColumnLayout();
            UpdateLobbyLayering();
        }

        public BoxContainer ActiveVoteContainer => IsOldLayoutActive ? _oldLayout.VoteContainer : VoteContainer;
        public Control ActiveRightSide => IsOldLayoutActive ? _oldLayout.RightSide : RightSide;
        public Control ActiveCharacterSetupState => IsOldLayoutActive ? _oldLayout.CharacterSetupState : CharacterSetupState;
        public TextureRect ActiveBackground => IsOldLayoutActive ? _oldLayout.Background : Background;
        public Label ActiveRoundStartTimer => IsOldLayoutActive ? _oldLayout.RoundStartTimer : RoundStartTimer;
        public Label ActiveStationTime => IsOldLayoutActive ? _oldLayout.StationTime : StationTime;
        public ServerInfo ActiveServerInfo => IsOldLayoutActive ? _oldLayout.ServerInfo : ServerInfo;
        public Label ActiveLobbyMusicText => IsOldLayoutActive ? _oldLayout.LobbyMusicText : LobbyMusicText;
        public Button ActiveAHelpButton => IsOldLayoutActive ? _oldLayout.AHelpButton : AHelpButton;
        public Label OldStartTimeLabel => _oldLayout.StartTimeLabel;
        public Label OldServerNameLabel => _oldLayout.ServerName;
        public LobbyCharacterPreviewPanel OldCharacterPreview => _oldLayout.CharacterPreview;
        private bool IsOldLayoutActive => string.Equals(_cfg.GetCVar(RMCCVars.RMCLobbyUiStyle), "old", StringComparison.OrdinalIgnoreCase);

        public void SetLobbyBackground(Texture? texture, bool fullScreen)
        {
            if (IsOldLayoutActive)
            {
                _oldLayout.Background.Texture = texture;
                Background.Texture = null;
                ConsoleBackground.Texture = null;
                Background.Visible = false;
                ConsoleBackground.Visible = false;
                RightSideBackground.Visible = true;
                return;
            }

            Background.Texture = fullScreen ? texture : null;
            ConsoleBackground.Texture = fullScreen ? null : texture;
            Background.Visible = fullScreen && texture != null;
            ConsoleBackground.Visible = !fullScreen && texture != null;
            RightSideBackground.Visible = !fullScreen;
        }

        public void SetLobbyChatMain(bool setting)
        {
            Chat.Main = false;
            _oldLayout.Chat.Main = false;
            (IsOldLayoutActive ? _oldLayout.Chat : Chat).Main = setting;
        }

        public void SetOldRoundCountdownVisible(bool visible)
        {
            _oldLayout.StartTimeLabel.Visible = visible;
            _oldLayout.ReadyButton.Visible = visible;
            _oldLayout.JoinHiveButton.Visible = !visible && !_oldLayout.JoinHiveButton.Disabled;
            _oldLayout.JoinUsmcButton.Visible = !visible && !_oldLayout.JoinUsmcButton.Disabled;
        }

        public void SwitchState(LobbyGuiState state)
        {
            CharacterSetupState.Visible = false;
            _oldLayout.CharacterSetupState.Visible = false;
            UpdateLobbyLayering();

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    CharacterSetupState.Visible = false;
                    _oldLayout.DefaultState.Visible = true;
                    _oldLayout.RightSide.Visible = _oldRightPanelVisible;
                    _oldLayout.ExpandPanel.Visible = !_oldRightPanelVisible;
                    _oldLayout.CharacterSetupState.Visible = false;
                    break;
                case LobbyGuiState.CharacterSetup:
                    DefaultState.Visible = true;
                    CharacterSetupState.Visible = !IsOldLayoutActive;
                    RightSide.Visible = true;
                    _oldLayout.DefaultState.Visible = true;
                    _oldLayout.CharacterSetupState.Visible = IsOldLayoutActive;
                    _oldLayout.RightSide.Visible = _oldRightPanelVisible;
                    _oldLayout.ExpandPanel.Visible = !_oldRightPanelVisible;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void UpdateLobbyLayering()
        {
            if (IsOldLayoutActive)
            {
                OldLayoutHost.SetPositionLast();
                if (_oldLayout.CharacterSetupState.Visible)
                    _oldLayout.CharacterSetupState.SetPositionLast();
                return;
            }

            BackgroundViewportArea.SetPositionFirst();
            MainContainer.SetPositionLast();
            CharacterSetupState.SetPositionLast();
        }

        private void ApplyLobbyColumnLayout()
        {
            if (IsOldLayoutActive)
                return;

            LeftColumn.SetPositionFirst();
            RightSide.SetPositionLast();

            _lastResponsiveMainSize = Vector2.Zero;
            _lastResponsiveLeftSize = Vector2.Zero;
            _leftMenuAnchorInitialized = false;
        }

        private void ToggleOldPanel(bool value)
        {
            _oldRightPanelVisible = value;
            _oldLayout.RightSide.Visible = value;
            _oldLayout.ExpandPanel.Visible = !value;
        }

        private void UpdateOldHeaderWidths()
        {
            var availableWidth = _oldLayout.LeftSide.Size.X;
            if (availableWidth <= 1f)
                return;

            var targetWidth = Math.Clamp(availableWidth, 760f, 840f);

            _oldLayout.LeftSideHeader.SetWidth = targetWidth;
            _oldLayout.LeftSideTop.SetWidth = targetWidth;
            _oldLayout.LeftSideHeader.MinSize = new Vector2(targetWidth, _oldLayout.LeftSideHeader.MinSize.Y);
            _oldLayout.LeftSideTop.MinSize = new Vector2(targetWidth, _oldLayout.LeftSideTop.MinSize.Y);
            _oldLayout.LeftSideHeader.MaxSize = new Vector2(targetWidth, float.PositiveInfinity);
            _oldLayout.LeftSideTop.MaxSize = new Vector2(targetWidth, float.PositiveInfinity);
        }


        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }

        public void SetReadyState(bool ready)
        {
            _suppressReadyToggle = true;
            ReadyButton.Pressed = ready;
            _oldLayout.ReadyButton.Pressed = ready;
            _suppressReadyToggle = false;
            UpdateReadyLabel(ready);
        }

        public void SetRoundState(bool roundStarted)
        {
            _suppressReadyToggle = true;
            ReadyButton.Disabled = roundStarted;
            _oldLayout.ReadyButton.Disabled = roundStarted;
            if (roundStarted)
            {
                ReadyButton.Pressed = false;
                _oldLayout.ReadyButton.Pressed = false;
            }
            _suppressReadyToggle = false;
            UpdateReadyLabel(ReadyButton.Pressed);

            ObserveButton.Disabled = !roundStarted;
            JoinUsmcButton.Disabled = !roundStarted;
            JoinHiveButton.Disabled = !roundStarted;
            CrewManifestButton.Disabled = !roundStarted;
            _oldLayout.ObserveButton.Disabled = !roundStarted;
            _oldLayout.JoinUsmcButton.Disabled = !roundStarted;
            _oldLayout.JoinHiveButton.Disabled = !roundStarted;
            SetOldRoundCountdownVisible(!roundStarted);
        }

        private void SetupChatStyles()
        {
            Chat.ChatWindowPanel.AddStyleClass("LobbyChatPanelInner");
            Chat.ChatInput.AddStyleClass("LobbyChatInputPanel");
            Chat.ChatInput.Input.AddStyleClass("LobbyChatLineEdit");
            Chat.ChatInput.ChannelSelector.AddStyleClass("LobbyChatSelectorButton");
            Chat.ChatInput.FilterButton.AddStyleClass("LobbyChatFilterButton");
            Chat.ChatInput.MinSize = new Vector2(0f, 36f);
            Chat.ChatInput.Input.MinSize = new Vector2(0f, 28f);
        }

        private void SetupLeftMenuToggle()
        {
            CenterMenuGlow.AnimationCompleted += OnLeftMenuAnimationCompleted;
            CenterMenuGlow.MouseFilter = Control.MouseFilterMode.Pass;
            CenterMenuPanel.MouseFilter = Control.MouseFilterMode.Pass;
            CenterMenuGlow.OnKeyBindDown += OnLeftMenuDragKeyBindDown;
            CenterMenuGlow.OnKeyBindUp += OnLeftMenuDragKeyBindUp;
            CenterCharacterSprite.Modulate = new Color(0.76f, 0.76f, 0.76f, 1f);
            CenterFacehuggerPortrait.Modulate = new Color(0.72f, 0.72f, 0.72f, 1f);
        }

        private void SetupTaskbarLabelHover()
        {
            BindTaskbarLabelHover(TaskbarMenuButton, TaskbarMenuLabel);
            BindTaskbarLabelHover(TaskbarDonateButton, TaskbarDonateLabel);
            BindTaskbarLabelHover(TaskbarCustomizationButton, TaskbarCustomizationLabel);
        }

        private static void BindTaskbarLabelHover(ContainerButton button, Label label)
        {
            button.OnMouseEntered += _ => label.FontColorOverride = StyleNano.LobbyMenuButtonBase;
            button.OnMouseExited += _ => label.FontColorOverride = Color.Black;
            label.FontColorOverride = Color.Black;
        }

        private void SetupButtonIconHover()
        {
            BindButtonIconHover(ReadyButton);
            BindButtonIconHover(SetupCharacterButton);
            BindButtonIconHover(StatsButton);
            BindButtonIconHover(OptionsButton);
            BindButtonIconHover(JoinUsmcButton);
            BindButtonIconHover(JoinHiveButton);
            BindButtonIconHover(ObserveButton);
            BindButtonIconHover(CrewManifestButton);
            BindButtonIconHover(TaskbarRatingButton);
            BindButtonIconHover(TaskbarAchievementsButton);
        }

        private static void BindButtonIconHover(Control button)
        {
            button.OnMouseEntered += _ =>
            {
                if (button is BaseButton { Disabled: true })
                {
                    SetButtonIconColor(button, Color.Black);
                    return;
                }

                SetButtonIconColor(button, StyleNano.LobbyMenuButtonBase);
            };
            button.OnMouseExited += _ => SetButtonIconColor(button, Color.Black);
            SetButtonIconColor(button, Color.Black);
        }

        private static void SetButtonIconColor(Control root, Color color)
        {
            foreach (var texture in EnumerateTextureRects(root))
            {
                texture.ModulateSelfOverride = color;
            }
        }

        private static IEnumerable<TextureRect> EnumerateTextureRects(Control root)
        {
            foreach (var child in root.Children)
            {
                if (child is TextureRect texture)
                    yield return texture;

                foreach (var nested in EnumerateTextureRects(child))
                {
                    yield return nested;
                }
            }
        }

        private void ApplyLobbyTheme(bool crtEnabled)
        {
            if (IsOldLayoutActive)
            {
                _oldLayout.Chat.SetLobbyTheme(false, false);
                return;
            }

            SetThemeClass(CenterMenuGlow, crtEnabled);
            SetThemeClass(CenterMenuPanel, crtEnabled);
            SetThemeClass(ServerInfoPanel, crtEnabled);
            SetThemeClass(ServerInfoDivider, crtEnabled);
            SetThemeClass(ServerInfo, crtEnabled);
            SetThemeClass(RightSide, crtEnabled);
            SetThemeClass(Chat.ChatWindowPanel, crtEnabled);
            SetThemeClass(Chat.ChatInput, crtEnabled);
            SetThemeClass(Chat.ChatInput.Input, crtEnabled);
            SetThemeClass(Chat.ChatInput.ChannelSelector, crtEnabled);
            SetThemeClass(Chat.ChatInput.FilterButton, crtEnabled);
            SetThemeClass(LeftTaskbarPanel, crtEnabled);
            SetThemeClass(WelcomeLine1, crtEnabled);
            SetThemeClass(WelcomeCharacterName, crtEnabled);
            SetThemeClass(WelcomeXenoName, crtEnabled);
            SetThemeClass(RoundStartTimer, crtEnabled);
            SetThemeClass(ReadyDivider, crtEnabled);
            SetThemeClass(ObserveDivider, crtEnabled);
            SetThemeClass(ServerInfoTitle, crtEnabled);
            SetThemeClass(LinkDiscordButton, crtEnabled);
            SetThemeClass(StationTime, crtEnabled);
            SetThemeClass(LobbyMusicPanel, crtEnabled);
            SetThemeClass(LobbyMusicHeader, crtEnabled);
            SetThemeClass(LobbyMusicText, crtEnabled);

            SetThemeClass(UpdatesButton, crtEnabled);
            SetThemeClass(GuidesButton, crtEnabled);
            SetThemeClass(AHelpButton, crtEnabled);
            SetThemeClass(OptionsButton, crtEnabled);
            SetThemeClass(LeaveButton, crtEnabled);
            SetThemeClass(SetupCharacterButton, crtEnabled);
            SetThemeClass(PollsButton, crtEnabled);
            SetThemeClass(ObserveButton, crtEnabled);
            SetThemeClass(ReadyButton, crtEnabled);
            SetThemeClass(StatsButton, crtEnabled);
            SetThemeClass(JoinUsmcButton, crtEnabled);
            SetThemeClass(JoinHiveButton, crtEnabled);
            SetThemeClass(CrewManifestButton, crtEnabled);
            SetThemeClass(TaskbarRatingButton, crtEnabled);
            SetThemeClass(TaskbarDonateButton, crtEnabled);
            SetThemeClass(TaskbarMenuButton, crtEnabled);
            SetThemeClass(TaskbarCustomizationButton, crtEnabled);
            SetThemeClass(TaskbarAchievementsButton, crtEnabled);
            SetThemeClass(TaskbarRatingLabel, crtEnabled);
            SetThemeClass(TaskbarDonateLabel, crtEnabled);
            SetThemeClass(TaskbarMenuLabel, crtEnabled);
            SetThemeClass(TaskbarCustomizationLabel, crtEnabled);
            SetThemeClass(TaskbarAchievementsLabel, crtEnabled);

            TaskbarMenuLabel.FontColorOverride = Color.Black;
            TaskbarDonateLabel.FontColorOverride = Color.Black;
            TaskbarCustomizationLabel.FontColorOverride = Color.Black;
            SetButtonIconColor(ReadyButton, Color.Black);
            SetButtonIconColor(SetupCharacterButton, Color.Black);
            SetButtonIconColor(StatsButton, Color.Black);
            SetButtonIconColor(OptionsButton, Color.Black);
            SetButtonIconColor(JoinUsmcButton, Color.Black);
            SetButtonIconColor(JoinHiveButton, Color.Black);
            SetButtonIconColor(ObserveButton, Color.Black);
            SetButtonIconColor(CrewManifestButton, Color.Black);
            SetButtonIconColor(TaskbarRatingButton, Color.Black);
            SetButtonIconColor(TaskbarAchievementsButton, Color.Black);

            ApplyGlow(WelcomeLine1, crtEnabled);
            ApplyGlow(WelcomeCharacterName, crtEnabled);
            ApplyGlow(WelcomeXenoName, crtEnabled);
            ApplyGlow(RoundStartTimer, crtEnabled);
            ApplyGlow(ServerInfoTitle, crtEnabled);
            ApplyGlow(LobbyMusicHeader, crtEnabled);

            ApplyButtonGlow(UpdatesButton, crtEnabled);
            ApplyButtonGlow(GuidesButton, crtEnabled);
            ApplyButtonGlow(AHelpButton, crtEnabled);
            ApplyButtonGlow(LinkDiscordButton, crtEnabled);
            ApplyButtonGlow(OptionsButton, crtEnabled);
            ApplyButtonGlow(LeaveButton, crtEnabled);
            ApplyButtonGlow(SetupCharacterButton, crtEnabled);
            ApplyButtonGlow(PollsButton, crtEnabled);
            ApplyButtonGlow(ObserveButton, crtEnabled);
            ApplyButtonGlow(ReadyButton, crtEnabled);
            ApplyButtonGlow(StatsButton, crtEnabled);
            ApplyButtonGlow(JoinUsmcButton, crtEnabled);
            ApplyButtonGlow(JoinHiveButton, crtEnabled);

            Chat.SetLobbyTheme(true, crtEnabled);
        }

        protected override void Dispose(bool disposing)
        {
            _linkAccount.Updated -= UpdateDiscordLinkState;
            _cfg.UnsubValueChanged(RMCCVars.RMCLobbyUiStyle, ApplyLobbyUiStyleClasses);
            base.Dispose(disposing);
        }

        private void ApplyLobbyUiStyleClasses(string style)
        {
            var oldStyle = style.Equals("old", StringComparison.OrdinalIgnoreCase);
            var showingCharacterSetup = CharacterSetupState.Visible || _oldLayout.CharacterSetupState.Visible;
            ApplyExclusiveStyleClass(RootContainer, oldStyle);
            ApplyExclusiveStyleClass(MainContainer, oldStyle);
            ApplyExclusiveStyleClass(DefaultState, oldStyle);
            ApplyExclusiveStyleClass(CharacterSetupState, oldStyle);
            ApplyExclusiveStyleClass(OldLayoutHost, oldStyle);
            OldLayoutHost.Visible = oldStyle;
            MainContainer.Visible = !oldStyle;
            CharacterSetupState.Visible = !oldStyle && showingCharacterSetup;
            DefaultState.Visible = true;
            RightSide.Visible = true;
            _oldLayout.Visible = oldStyle;
            _oldLayout.CharacterSetupState.Visible = oldStyle && showingCharacterSetup;
            _oldLayout.DefaultState.Visible = true;
            _oldLayout.RightSide.Visible = _oldRightPanelVisible;
            _oldLayout.ExpandPanel.Visible = !_oldRightPanelVisible;
            _oldLayout.Chat.SetLobbyTheme(false, false);
            SetLobbyChatMain(true);
            ApplyLobbyColumnLayout();
            _voteLastSize = Vector2.Zero;

            if (!oldStyle)
            {
                ApplyLobbyTheme(_cfg.GetCVar(RMCCVars.RMCLobbyCrtEnabled));
                RootContainer.InvalidateStyleSheet();
                RootContainer.ForceRunStyleUpdate();
                UpdateResponsiveLayout();
                UpdateVoteContainerAnchor();
                UpdateLeftMenuAnchor();
                UpdateTaskbarAnchor();
            }

            UpdateLobbyLayering();
        }

        private static void ApplyExclusiveStyleClass(Control control, bool oldStyle)
        {
            if (oldStyle)
            {
                control.AddStyleClass(LobbyUiStyleOldClass);
                control.RemoveStyleClass(LobbyUiStyleNewClass);
            }
            else
            {
                control.AddStyleClass(LobbyUiStyleNewClass);
                control.RemoveStyleClass(LobbyUiStyleOldClass);
            }
        }

        private static void SetThemeClass(Control control, bool crtEnabled)
        {
            if (crtEnabled)
            {
                control.AddStyleClass(StyleNano.StyleClassLobbyThemeCrt);
                control.RemoveStyleClass(StyleNano.StyleClassLobbyThemeClean);
            }
            else
            {
                control.AddStyleClass(StyleNano.StyleClassLobbyThemeClean);
                control.RemoveStyleClass(StyleNano.StyleClassLobbyThemeCrt);
            }
        }

        private static void ApplyGlow(Label label, bool crtEnabled)
        {
            if (crtEnabled)
            {
                label.FontColorShadowOverride = StyleNano.LobbyCrtGlow;
                label.ShadowOffsetXOverride = 1;
                label.ShadowOffsetYOverride = 1;
            }
            else
            {
                label.FontColorShadowOverride = null;
                label.ShadowOffsetXOverride = null;
                label.ShadowOffsetYOverride = null;
            }
        }

        private static void ApplyButtonGlow(Button button, bool crtEnabled)
        {
            ApplyGlow(button.Label, crtEnabled);
        }

        private void UpdateDiscordLinkState()
        {
            var linked = _linkAccount.Linked;
            LinkDiscordButton.Visible = !linked;
            LinkDiscordButton.Text = Loc.GetString(linked
                ? "ui-lobby-discord-linked-button"
                : "ui-lobby-link-discord-button");
            _oldLayout.LinkDiscordButton.Visible = !linked;
            _oldLayout.LinkDiscordButton.Text = LinkDiscordButton.Text;
        }

        private void ToggleLeftMenu(bool show)
        {
            if (_leftMenuVisible == show)
                return;

            _leftMenuVisible = show;
            CenterMenuGlow.StopAnimation(LeftMenuHideAnimationKey);
            CenterMenuGlow.StopAnimation(LeftMenuShowAnimationKey);

            if (show)
            {
                _leftMenuAutoCenter = true;
                _leftMenuAnchorInitialized = false;
                CenterMenuGlow.Visible = true;
                CenterMenuGlow.Modulate = Color.Transparent;
                CenterMenuGlow.PlayAnimation(BuildLeftMenuAnimation(Color.Transparent, Color.White), LeftMenuShowAnimationKey);
            }
            else
            {
                CenterMenuGlow.PlayAnimation(BuildLeftMenuAnimation(Color.White, Color.Transparent), LeftMenuHideAnimationKey);
            }
        }

        private void OnLeftMenuAnimationCompleted(string key)
        {
            if (key == LeftMenuHideAnimationKey)
            {
                CenterMenuGlow.Visible = false;
                CenterMenuGlow.Modulate = Color.White;
            }
        }

        private static Animation BuildLeftMenuAnimation(Color from, Color to)
        {
            return new Animation
            {
                Length = TimeSpan.FromSeconds(0.15f),
                AnimationTracks =
                {
                    new AnimationTrackControlProperty
                    {
                        Property = nameof(Control.Modulate),
                        InterpolationMode = AnimationInterpolationMode.Linear,
                        KeyFrames =
                        {
                            new AnimationTrackProperty.KeyFrame(from, 0f),
                            new AnimationTrackProperty.KeyFrame(to, 0.15f)
                        }
                    }
                }
            };
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            _leftMenuDragHelper.Update(args.DeltaSeconds);

            if (IsOldLayoutActive)
            {
                if (_oldLayout.VoteContainer.Size.X > 1f && _oldLayout.VoteContainer.Size.Y > 1f)
                    _voteLastSize = _oldLayout.VoteContainer.Size;
                UpdateOldHeaderWidths();
                return;
            }

            UpdateResponsiveLayout();

            if (CenterMenuGlow.Visible)
                _leftMenuLastGlobal = CenterMenuGlow.GlobalPosition;

            // CCM rework lobby - start
            if (VoteContainer.Size.X > 1f && VoteContainer.Size.Y > 1f)
                _voteLastSize = VoteContainer.Size;
            // CCM rework lobby - end

            UpdateVoteContainerAnchor();
            UpdateLeftMenuAnchor();
            UpdateTaskbarAnchor();
        }

        private void UpdateResponsiveLayout()
        {
            var mainSize = MainContainer.Size;
            var leftSize = LeftColumn.Size;
            if (mainSize.X <= 1f || mainSize.Y <= 1f || leftSize.X <= 1f || leftSize.Y <= 1f)
                return;

            if (Math.Abs(mainSize.X - _lastResponsiveMainSize.X) < 1f &&
                Math.Abs(mainSize.Y - _lastResponsiveMainSize.Y) < 1f &&
                Math.Abs(leftSize.X - _lastResponsiveLeftSize.X) < 1f &&
                Math.Abs(leftSize.Y - _lastResponsiveLeftSize.Y) < 1f)
            {
                return;
            }

            _lastResponsiveMainSize = mainSize;
            _lastResponsiveLeftSize = leftSize;

            _compactLobbyLayout = mainSize.Y <= 820f;
            var shortHeightLayout = mainSize.Y <= 920f;

            var centerFactor = _compactLobbyLayout
                ? 0.36f
                : shortHeightLayout
                    ? 0.34f
                    : 0.32f;
            var centerWidth = Math.Clamp(leftSize.X * centerFactor, LobbyCenterWidthMin, LobbyCenterWidthMax);
            CenterMenuGlow.SetWidth = centerWidth;
            CenterMenuPanel.SetWidth = centerWidth;
            CenterMenuGlow.MinSize = new Vector2(centerWidth, CenterMenuGlow.MinSize.Y);
            CenterMenuPanel.MinSize = new Vector2(centerWidth, CenterMenuPanel.MinSize.Y);

            var taskbarFactor = _compactLobbyLayout
                ? 0.72f
                : shortHeightLayout
                    ? 0.68f
                    : 0.64f;
            var taskbarWidth = Math.Clamp(leftSize.X * taskbarFactor, LobbyTaskbarWidthMin, LobbyTaskbarWidthMax);
            var taskbarHeight = _compactLobbyLayout ? LobbyTaskbarHeightCompact : LobbyTaskbarHeightDefault;
            LeftTaskbarPanel.SetWidth = taskbarWidth;
            LeftTaskbarPanel.SetHeight = taskbarHeight;
            LeftTaskbarPanel.MinSize = new Vector2(taskbarWidth, taskbarHeight);
            LeftTaskbarPanel.MaxSize = new Vector2(taskbarWidth, taskbarHeight);

            MainContainer.SeparationOverride = _compactLobbyLayout ? 6 : 8;
            TopButtonBar.SeparationOverride = _compactLobbyLayout ? 4 : 6;

            var topButtonHeight = _compactLobbyLayout ? 36f : 40f;
            LinkDiscordButton.MinSize = new Vector2(0f, topButtonHeight);
            AHelpButton.MinSize = new Vector2(0f, topButtonHeight);
            UpdatesButton.MinSize = new Vector2(0f, topButtonHeight);
            GuidesButton.MinSize = new Vector2(0f, topButtonHeight);
            PollsButton.MinSize = new Vector2(0f, topButtonHeight);
            LeaveButton.MinSize = new Vector2(0f, topButtonHeight);
            TopButtonBar.MinSize = new Vector2(0f, topButtonHeight);

            TaskbarRatingButton.MinSize = _compactLobbyLayout ? new Vector2(54f, 40f) : new Vector2(64f, 48f);
            TaskbarDonateButton.MinSize = _compactLobbyLayout ? new Vector2(96f, 48f) : new Vector2(108f, 56f);
            TaskbarMenuButton.MinSize = _compactLobbyLayout ? new Vector2(76f, 40f) : new Vector2(86f, 48f);
            TaskbarCustomizationButton.MinSize = _compactLobbyLayout ? new Vector2(96f, 48f) : new Vector2(108f, 56f);
            TaskbarAchievementsButton.MinSize = _compactLobbyLayout ? new Vector2(54f, 40f) : new Vector2(64f, 48f);
        }

        private float GetLobbySafePadding()
        {
            return _compactLobbyLayout ? LobbyEdgePaddingCompact : LobbyEdgePaddingDefault;
        }

        private void UpdateLeftMenuAnchor()
        {
            if (_leftMenuDragStarted || CenterMenuGlow.Parent == null)
                return;

            if (!_leftMenuAutoCenter)
                return;

            var menuSize = CenterMenuGlow.Size;
            var leftSize = LeftColumn.Size;
            if (menuSize.X <= 1f || menuSize.Y <= 1f || leftSize.X <= 1f || leftSize.Y <= 1f)
                return;

            var parentGlobal = CenterMenuGlow.Parent.GlobalPosition;
            var leftGlobal = LeftColumn.GlobalPosition;
            var padding = GetLobbySafePadding();

            var x = leftGlobal.X - parentGlobal.X + (leftSize.X - menuSize.X) * 0.5f;
            var y = leftGlobal.Y - parentGlobal.Y + (leftSize.Y - menuSize.Y) * 0.5f + leftSize.Y * LeftMenuCenterYOffsetPercent;

            var minX = leftGlobal.X - parentGlobal.X + padding;
            var maxX = leftGlobal.X - parentGlobal.X + leftSize.X - menuSize.X - padding;
            var minY = leftGlobal.Y - parentGlobal.Y + padding;
            var maxY = leftGlobal.Y - parentGlobal.Y + leftSize.Y - menuSize.Y - padding;
            if (maxX >= minX)
                x = Math.Clamp(x, minX, maxX);
            if (maxY >= minY)
                y = Math.Clamp(y, minY, maxY);

            LayoutContainer.SetAnchorPreset(CenterMenuGlow, LayoutPreset.TopLeft);
            LayoutContainer.SetPosition(CenterMenuGlow, new Vector2(x, y));
            _leftMenuAnchorInitialized = true;
        }

        private void UpdateVoteContainerAnchor()
        {
            if (VoteContainer.Parent == null)
                return;

            var voteSize = VoteContainer.Size;
            if (voteSize.X <= 1f || voteSize.Y <= 1f)
                voteSize = _voteLastSize;
            if (voteSize.X <= 1f || voteSize.Y <= 1f)
                return;

            var parentSize = VoteContainer.Parent.Size;
            if (parentSize.X <= 1f || parentSize.Y <= 1f)
                return;

            var padding = GetLobbySafePadding();
            var voteX = (parentSize.X - voteSize.X) * 0.5f;
            var voteY = _compactLobbyLayout ? 4f : 6f;

            var minX = padding;
            var maxX = parentSize.X - voteSize.X - padding;
            if (maxX >= minX)
                voteX = Math.Clamp(voteX, minX, maxX);

            LayoutContainer.SetAnchorPreset(VoteContainer, LayoutPreset.TopLeft);
            LayoutContainer.SetPosition(VoteContainer, new Vector2(voteX, voteY));
        }

        private void UpdateOldVoteContainerAnchor()
        {
            if (_oldLayout.VoteContainer.Parent == null)
                return;

            var voteSize = _oldLayout.VoteContainer.Size;
            if (voteSize.X <= 1f || voteSize.Y <= 1f)
                voteSize = _voteLastSize;
            if (voteSize.X <= 1f || voteSize.Y <= 1f)
                return;

            var parentSize = _oldLayout.VoteContainer.Parent.Size;
            if (parentSize.X <= 1f || parentSize.Y <= 1f)
                return;

            var padding = 8f;
            var voteX = padding;
            var voteY = 8f;
            var maxX = MathF.Max(padding, parentSize.X - voteSize.X - padding);
            voteX = Math.Clamp(voteX, padding, maxX);

            LayoutContainer.SetAnchorPreset(_oldLayout.VoteContainer, LayoutPreset.TopLeft);
            LayoutContainer.SetPosition(_oldLayout.VoteContainer, new Vector2(voteX, voteY));
        }

        private void UpdateTaskbarAnchor()
        {
            if (LeftTaskbarPanel.Parent == null)
                return;

            var panelSize = LeftTaskbarPanel.Size;
            if (panelSize.X <= 1f || panelSize.Y <= 1f)
                return;

            var parentGlobal = LeftTaskbarPanel.Parent.GlobalPosition;
            var leftGlobal = LeftColumn.GlobalPosition;
            var leftSize = LeftColumn.Size;
            if (leftSize.X <= 1f || leftSize.Y <= 1f)
                return;

            var padding = GetLobbySafePadding();
            var x = leftGlobal.X - parentGlobal.X + (leftSize.X - panelSize.X) * 0.5f;
            var y = leftGlobal.Y - parentGlobal.Y + leftSize.Y - panelSize.Y - padding;

            var minX = leftGlobal.X - parentGlobal.X + padding;
            var maxX = leftGlobal.X - parentGlobal.X + leftSize.X - panelSize.X - padding;
            if (maxX >= minX)
                x = Math.Clamp(x, minX, maxX);

            LayoutContainer.SetAnchorPreset(LeftTaskbarPanel, LayoutPreset.TopLeft);
            LayoutContainer.SetPosition(LeftTaskbarPanel, new Vector2(x, y));
        }

        private void OnLeftMenuDragKeyBindDown(GUIBoundKeyEventArgs args)
        {
            if (args.Function != EngineKeyFunctions.UIClick || !CenterMenuGlow.Visible)
                return;

            _leftMenuDragStarted = false;
            _leftMenuDragHelper.MouseDown(CenterMenuGlow);
            args.Handle();
        }

        private void OnLeftMenuDragKeyBindUp(GUIBoundKeyEventArgs args)
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _leftMenuDragHelper.EndDrag();
            args.Handle();
        }

        private bool OnBeginLeftMenuDrag()
        {
            if (!CenterMenuGlow.Visible || CenterMenuGlow.Parent == null)
                return false;

            _leftMenuDragStarted = true;
            _leftMenuAutoCenter = false;

            if (!_leftMenuAnchorInitialized && CanInitializeLeftMenuAnchor())
                InitializeLeftMenuAnchor(CenterMenuGlow.GlobalPosition);

            var menuGlobal = CenterMenuGlow.GlobalPosition;

            _leftMenuDragOffset = UserInterfaceManager.MousePositionScaled.Position - menuGlobal;
            return true;
        }

        private bool OnContinueLeftMenuDrag(float frameTime)
        {
            if (!_leftMenuDragStarted || CenterMenuGlow.Parent == null)
                return false;

            var parentGlobal = CenterMenuGlow.Parent.GlobalPosition;
            var mousePos = UserInterfaceManager.MousePositionScaled.Position;
            var newPos = mousePos - _leftMenuDragOffset - parentGlobal;
            // CCM rework lobby - start
            var menuSize = CenterMenuGlow.Size;
            var leftGlobal = LeftColumn.GlobalPosition;
            var leftSize = LeftColumn.Size;
            var padding = GetLobbySafePadding();
            if (leftSize.X > 1f && leftSize.Y > 1f && menuSize.X > 1f && menuSize.Y > 1f)
            {
                var minX = leftGlobal.X - parentGlobal.X + padding;
                var maxX = leftGlobal.X - parentGlobal.X + leftSize.X - menuSize.X - padding;
                var minY = leftGlobal.Y - parentGlobal.Y + padding;
                var maxY = leftGlobal.Y - parentGlobal.Y + leftSize.Y - menuSize.Y - padding;
                if (maxX >= minX)
                    newPos.X = Math.Clamp(newPos.X, minX, maxX);
                if (maxY >= minY)
                    newPos.Y = Math.Clamp(newPos.Y, minY, maxY);
            }
            // CCM rework lobby - end
            LayoutContainer.SetPosition(CenterMenuGlow, newPos);
            return true;
        }

        private void OnEndLeftMenuDrag()
        {
            _leftMenuDragStarted = false;
        }

        private void InitializeLeftMenuAnchor(Vector2 menuGlobal)
        {
            if (_leftMenuAnchorInitialized || CenterMenuGlow.Parent == null)
                return;

            var parentGlobal = CenterMenuGlow.Parent.GlobalPosition;
            LayoutContainer.SetAnchorPreset(CenterMenuGlow, LayoutPreset.TopLeft);
            LayoutContainer.SetPosition(CenterMenuGlow, menuGlobal - parentGlobal);
            _leftMenuAnchorInitialized = true;
        }

        private bool CanInitializeLeftMenuAnchor()
        {
            if (CenterMenuGlow.Parent == null)
                return false;

            var parentSize = CenterMenuGlow.Parent.Size;
            var menuSize = CenterMenuGlow.Size;
            return parentSize.X > 1f && parentSize.Y > 1f && menuSize.X > 1f && menuSize.Y > 1f;
        }


        private void UpdateReadyLabel(bool ready)
        {
            var text = ready
                ? Loc.GetString("ui-lobby-ready-up-button")
                : Loc.GetString("ui-lobby-not-ready-button");
            ReadyButton.Text = text;
            _oldLayout.ReadyButton.Text = text;
        }

        private void OpenTutorial()
        {
            if (_tutorialWindow == null || _tutorialWindow.Disposed)
            {
                _tutorialWindow = new RulesAndInfoWindow();
                _tutorialWindow.OnClose += () => _tutorialWindow = null;
            }

            _tutorialWindow.OpenCentered();
            _tutorialWindow.MoveToFront();
        }

        private void OpenInfoLink(CVarDef<string> cvar)
        {
            var uri = NormalizeAbsoluteHttpUriString(_cfg.GetCVar(cvar));
            if (uri == null)
                return;

            _uriOpener.OpenUri(uri);
        }

        private static string? NormalizeAbsoluteHttpUriString(string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return null;

            var trimmed = value.Trim();
            if (!trimmed.StartsWith("http://", StringComparison.OrdinalIgnoreCase) &&
                !trimmed.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
                return null;

            return trimmed;
        }

        public void OpenStats()
        {
            if (_statsWindow == null || _statsWindow.Disposed)
            {
                _statsWindow = new CCMStatisticsWindow();
                _statsWindow.OnClose += () => _statsWindow = null;
            }

            _statsWindow.RefreshData();
            _statsWindow.OpenCenteredAnimated();
            _statsWindow.MoveToFront();
        }

        private void ToggleStats()
        {
            if (_statsWindow != null && !_statsWindow.Disposed && _statsWindow.IsOpen)
            {
                _statsWindow.CloseAnimated();
                return;
            }

            OpenStats();
        }

        private void OpenLeaderboard()
        {
            if (_leaderboardWindow == null || _leaderboardWindow.Disposed)
            {
                _leaderboardWindow = new CCMLeaderboardWindow();
                _leaderboardWindow.OnClose += () => _leaderboardWindow = null;
            }

            _leaderboardWindow.RefreshData();
            _leaderboardWindow.OpenCenteredAnimated();
            _leaderboardWindow.MoveToFront();
        }

        private void ToggleLeaderboard()
        {
            if (_leaderboardWindow != null && !_leaderboardWindow.Disposed && _leaderboardWindow.IsOpen)
            {
                _leaderboardWindow.CloseAnimated();
                return;
            }

            OpenLeaderboard();
        }

        private void OpenCharacterSetup()
        {
            if (_stateManager.CurrentState is LobbyState lobby)
                lobby.SwitchState(LobbyGuiState.CharacterSetup);
        }

        private void OpenPolls()
        {
            if (_voteMenu == null || _voteMenu.Disposed)
            {
                _voteMenu = new VoteCallMenu();
                _voteMenu.OnClose += () => _voteMenu = null;
            }

            _voteMenu.OpenCentered();
            _voteMenu.MoveToFront();
        }

        private void OpenObserve()
        {
            if (_observeWindow == null || _observeWindow.Disposed)
            {
                _observeWindow = new ObserveWarningWindow();
                _observeWindow.OnClose += () => _observeWindow = null;
            }

            _observeWindow.OpenCentered();
            _observeWindow.MoveToFront();
        }

        private void OpenLateJoin()
        {
            if (_lateJoinWindow == null || _lateJoinWindow.Disposed)
            {
                _lateJoinWindow = new LateJoinGui();
                _lateJoinWindow.OnClose += () => _lateJoinWindow = null;
            }

            _lateJoinWindow.OpenCentered();
            _lateJoinWindow.MoveToFront();
        }

        private void OpenCrewManifest()
        {
            if (!TryGetLobbyStation(out var station))
                return;

            _entityManager.System<CrewManifestSystem>().RequestCrewManifest(station);
        }

        private bool TryGetLobbyStation(out NetEntity station)
        {
            var gameTicker = _entityManager.System<ClientGameTicker>();

            foreach (var entry in gameTicker.StationNames)
            {
                station = entry.Key;
                return true;
            }

            foreach (var entry in gameTicker.JobsAvailable)
            {
                station = entry.Key;
                return true;
            }

            station = default;
            return false;
        }

        private void ToggleReady(bool ready)
        {
            if (_suppressReadyToggle)
                return;

            UpdateReadyLabel(ready);
            _consoleHost.ExecuteCommand($"toggleready {ready.ToString().ToLowerInvariant()}");
        }
    }
}
