using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Client._RMC14.Xenonids.UI;

namespace Content.Client._RMC14.Xenonids.Construction;

[GenerateTypedNameReferences]
public sealed partial class XenoChooseStructureWindow : DefaultWindow
{
    private StyleNano.UiColorTheme _appliedTheme;

    public XenoChooseStructureWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetDisplayTitle(string title)
    {
        Title = title;
        WindowTitleLabel.Text = title;
        ApplyTheme(true);
    }

    public void ApplyTheme(bool force = false)
    {
        var theme = StyleNano.CurrentTheme;
        if (!force && _appliedTheme == theme)
            return;

        _appliedTheme = theme;
        var palette = GetPalette(theme);

        HeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.HeaderBackground,
            BorderColor = palette.HeaderBorder,
            BorderThickness = new Thickness(1),
        };

        StructureListPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = palette.ListBackground,
            BorderColor = palette.ListBorder,
            BorderThickness = new Thickness(1),
        };

        WindowTitleLabel.FontColorOverride = palette.TitleText;
        NodeCountLabel.FontColorOverride = palette.SubtitleText;
    }

    public void StyleChoiceControl(XenoChoiceControl control, bool selected)
    {
        ApplyTheme();

        var palette = GetPalette(_appliedTheme);
        control.Button.StyleBoxOverride = selected
            ? new StyleBoxFlat
            {
                BackgroundColor = palette.SelectedBackground,
                BorderColor = palette.SelectedBorder,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginTopOverride = 2,
                ContentMarginRightOverride = 4,
                ContentMarginBottomOverride = 2,
            }
            : null;

        control.SetTextColor(selected ? palette.SelectedText : palette.NormalText);
        control.Texture.ModulateSelfOverride = selected
            ? palette.SelectedIcon
            : palette.NormalIcon;
    }

    private static ThemePalette GetPalette(StyleNano.UiColorTheme theme)
    {
        return theme switch
        {
            StyleNano.UiColorTheme.Gray => new ThemePalette(
                Color.FromHex("#2A333E").WithAlpha(0.96f),
                Color.FromHex("#75869A").WithAlpha(0.95f),
                Color.FromHex("#181F27").WithAlpha(0.92f),
                Color.FromHex("#465363").WithAlpha(0.95f),
                Color.FromHex("#F0F4F8"),
                Color.FromHex("#C7D0D9"),
                Color.FromHex("#E7ECF1"),
                Color.White,
                Color.White.WithAlpha(0.92f),
                Color.FromHex("#E0E7EF"),
                Color.FromHex("#465364").WithAlpha(0.96f),
                Color.FromHex("#ADB9C7").WithAlpha(0.98f)),
            _ => new ThemePalette(
                Color.FromHex("#123A1C").WithAlpha(0.96f),
                Color.FromHex("#37814A").WithAlpha(0.95f),
                Color.FromHex("#09160C").WithAlpha(0.92f),
                Color.FromHex("#285D36").WithAlpha(0.95f),
                Color.FromHex("#ECFFF0"),
                Color.FromHex("#C8E8CF"),
                Color.FromHex("#E6F6EA"),
                Color.FromHex("#F5FFF7"),
                Color.White.WithAlpha(0.92f),
                Color.FromHex("#CFF4D7"),
                Color.FromHex("#236131").WithAlpha(0.96f),
                Color.FromHex("#78D48F").WithAlpha(0.98f)),
        };
    }

    private readonly record struct ThemePalette(
        Color HeaderBackground,
        Color HeaderBorder,
        Color ListBackground,
        Color ListBorder,
        Color TitleText,
        Color SubtitleText,
        Color NormalText,
        Color SelectedText,
        Color NormalIcon,
        Color SelectedIcon,
        Color SelectedBackground,
        Color SelectedBorder);
}


