using System.Collections.Generic;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class ClientVerticalTabContainer : BoxContainer
{
    private readonly Dictionary<Control, BaseButton> _tabs = new();
    private readonly List<Control> _controls = new();
    private readonly ButtonGroup _tabGroup = new(false);
    private Control? _currentControl;

    public int CurrentTab
    {
        get => _currentControl != null ? _controls.IndexOf(_currentControl) : -1;
        set
        {
            if (value < 0 || value >= _controls.Count)
                return;

            SelectTab(_controls[value]);
        }
    }

    public ClientVerticalTabContainer()
    {
        RobustXamlLoader.Load(this);
    }

    public int AddTab(Control control, string title)
    {
        var button = new Button
        {
            Text = title,
            Group = _tabGroup,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Stretch,
            MinHeight = 34,
        };
        button.AddStyleClass(StyleBase.StyleClassVerticalTabButton);

        control.VerticalExpand = true;
        control.HorizontalExpand = true;

        TabContainer.AddChild(button);
        button.SetPositionLast();
        ContentsContainer.AddChild(control);
        var index = ChildCount - 1;
        button.OnPressed += _ => SelectTab(control);

        _controls.Add(control);
        _tabs.Add(control, button);

        if (ContentsContainer.ChildCount > 1)
        {
            control.Visible = false;
        }
        else
        {
            SelectTab(control);
        }

        return index;
    }

    public void RefreshTabStyles()
    {
        RefreshStylesRecursive(this);

        foreach (var (control, button) in _tabs)
        {
            var shouldBePressed = control == _currentControl;
            if (button.Pressed != shouldBePressed)
                button.Pressed = shouldBePressed;
        }
    }

    public void RemoveTab(Control control)
    {
        if (!_tabs.TryGetValue(control, out var button))
            return;

        _tabs.Remove(control);
        _controls.Remove(control);

        if (control.Parent == ContentsContainer)
            ContentsContainer.RemoveChild(control);
        else
            control.Visible = false;

        if (button.Parent == TabContainer)
            TabContainer.RemoveChild(button);
        else
            button.Visible = false;

        if (_currentControl == control)
        {
            var previous = _controls.Count > 0 ? _controls[^1] : null;
            if (previous != null)
                SelectTab(previous);
            else
                _currentControl = null;
        }
    }

    protected override void ChildRemoved(Control child)
    {
        if (_tabs.Remove(child, out var button))
        {
            button.Dispose();
        }

        if (_currentControl == child)
        {
            var previous = _controls.IndexOf(child) - 1;

            if (previous > -1)
            {
                var setControl = _controls[previous];
                SelectTab(setControl);
            }
            else
            {
                _currentControl = null;
            }
        }

        _controls.Remove(child);
        base.ChildRemoved(child);
    }

    private void SelectTab(Control control)
    {
        if (_currentControl != null)
        {
            _currentControl.Visible = false;
        }

        var button = _tabs[control];
        button.Pressed = true;
        control.Visible = true;
        _currentControl = control;
    }

    private static void RefreshStylesRecursive(Control control)
    {
        control.InvalidateStyleSheet();
        control.DoStyleUpdate();

        foreach (var child in control.Children)
        {
            RefreshStylesRecursive(child);
        }
    }
}
// # CCM priority rework
