using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Xenonids.UI;

[GenerateTypedNameReferences]
[Virtual]
public partial class XenoChoiceControl : Control
{
    private FormattedMessage? _message;

    public XenoChoiceControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Set(string name, Texture? texture, Color? textColor = null)
    {
        var msg = new FormattedMessage();
        msg.AddText(name);
        Set(msg, texture, textColor);
    }

    public void Set(FormattedMessage msg, Texture? texture, Color? textColor = null)
    {
        _message = new FormattedMessage(msg);
        NameLabel.SetMessage(_message, defaultColor: textColor);
        Texture.Texture = texture;
    }

    public void SetTextColor(Color? textColor)
    {
        if (_message == null)
            return;

        NameLabel.SetMessage(_message, defaultColor: textColor);
    }
}
