using System.Linq;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared.Access;
using Content.Shared.Access.Systems;

namespace Content.Client.Access.UI;

[GenerateTypedNameReferences]
public sealed partial class AccessLevelControl : GridContainer
{
    [Dependency] private readonly ILogManager _logManager = default!;

    private ISawmill _sawmill = default!;

    public readonly Dictionary<ProtoId<AccessLevelPrototype>, CheckBox> ButtonsList = new();

    public AccessLevelControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("accesslevelcontrol");
    }

    public void Populate(List<ProtoId<AccessLevelPrototype>> accessLevels, IPrototypeManager prototypeManager)
    {
        foreach (var access in accessLevels)
        {
            if (!prototypeManager.TryIndex(access, out var accessLevel))
            {
                _sawmill.Error($"Unable to find accesslevel for {access}");
                continue;
            }

            var newButton = new TextAccessCheckBox
            {
                ToggleMode = true,
                HorizontalExpand = true,
                ClipText = false,
            };
            newButton.AccessText = accessLevel.GetAccessLevelName();
            newButton.Label.HorizontalAlignment = HAlignment.Left;
            AddChild(newButton);
            ButtonsList.Add(accessLevel.ID, newButton);
        }
    }

    public void UpdateState(
        List<ProtoId<AccessLevelPrototype>> pressedList,
        List<ProtoId<AccessLevelPrototype>>? enabledList = null)
    {
        foreach (var (accessName, button) in ButtonsList)
        {
            button.Pressed = pressedList.Contains(accessName);
            button.Disabled = !(enabledList?.Contains(accessName) ?? true);
        }
    }

    private sealed class TextAccessCheckBox : CheckBox
    {
        private string _accessText = string.Empty;

        public string AccessText
        {
            get => _accessText;
            set
            {
                _accessText = value;
                UpdateDisplayText();
            }
        }

        public TextAccessCheckBox()
        {
            TextureRect.AddStyleClass(MonotoneCheckBox.StyleClassMonotoneCheckBox);
            TextureRect.Visible = false;
            LeftAlign = true;
            Label.HorizontalAlignment = HAlignment.Left;
            Label.HorizontalExpand = true;
            UpdateDisplayText();
        }

        protected override void DrawModeChanged()
        {
            base.DrawModeChanged();
            Modulate = Disabled ? Color.Gray : Color.White;
            UpdateDisplayText();
        }

        private void UpdateDisplayText()
        {
            Text = $"{(Pressed ? "[x]" : "[ ]")} {_accessText}";
        }
    }
}
