using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using System.Numerics;

namespace Content.Client._RMC14.Access;

public enum AccessGroupState
{
    None,
    Partial,
    Full,
}

[GenerateTypedNameReferences]
public sealed partial class IdModificationConsoleAccessGroupButton : Control
{
    public string Tag = "";

    public IdModificationConsoleAccessGroupButton()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetAccessState(AccessGroupState state)
    {
        StateDiamond.State = state;
    }
}

public sealed class AccessStateDiamond : Control
{
    private const float DiamondSize = 10f;

    public AccessGroupState State
    {
        get => _state;
        set
        {
            _state = value;
        }
    }

    private AccessGroupState _state;

    public AccessStateDiamond()
    {
        MinSize = new Vector2(18f, 30f);
        HorizontalExpand = false;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var center = PixelPosition + new Vector2(PixelWidth / 2f, PixelHeight / 2f);
        var half = DiamondSize / 2f;
        var outline = new[]
        {
            center + new Vector2(0f, -half),
            center + new Vector2(half, 0f),
            center + new Vector2(0f, half),
            center + new Vector2(-half, 0f),
            center + new Vector2(0f, -half),
        };

        var accent = State switch
        {
            AccessGroupState.Full => Color.FromHex("#68D36F"),
            AccessGroupState.Partial => Color.FromHex("#D4B45F"),
            _ => Color.FromHex("#C7CFD8"),
        };

        if (State == AccessGroupState.Full)
        {
            var fill = new[]
            {
                center + new Vector2(0f, -half),
                center + new Vector2(half, 0f),
                center + new Vector2(0f, half),
                center + new Vector2(-half, 0f),
            };
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, fill, accent);
            return;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, outline, accent);

        if (State != AccessGroupState.Partial)
            return;

        var inner = half * 0.48f;
        var fillPartial = new[]
        {
            center + new Vector2(0f, -inner),
            center + new Vector2(inner, 0f),
            center + new Vector2(0f, inner),
            center + new Vector2(-inner, 0f),
        };
        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, fillPartial, accent);
    }
}
