using Content.Client._RMC14.TacticalMap.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._CCM.Teleporter.UI;

[GenerateTypedNameReferences]
public sealed partial class CCMPlanetTeleporterWindow : DefaultWindow
{
    public event Action<Vector2i>? OnSelected;

    public CCMPlanetTeleporterWindow()
    {
        RobustXamlLoader.Load(this);
        TacticalMap.MouseFilter = Control.MouseFilterMode.Stop;
        TacticalMap.CanKeyboardFocus = true;
        TacticalMap.Drawing = false;
        TacticalMap.IsCanvas = false;
        TacticalMap.QueenEyeMode = true;
        TacticalMap.CurrentLabelMode = TacticalMapControl.LabelMode.None;
        TacticalMap.OnQueenEyeMove += pos => OnSelected?.Invoke(pos);
        TacticalMap.GrabKeyboardFocus();
    }

    public void SetStatus(string text)
    {
        StatusLabel.Text = text;
    }
}
