using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CCM.VehicleElevator;

[GenerateTypedNameReferences]
public sealed partial class VehicleElevatorWindow : DefaultCMWindow
{
    public VehicleElevatorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

