- type: rank
  id: RMCRankWeYaExecutiveSpecialist
  name: Специализированный руководитель
  prefix: Спец. рук.

- type: rank
  id: RMCRankWeYaSeniorExecutive
  name: Старший руководитель
  prefix: Стар. рук.

- type: rank
  id: RMCRankWeYaExecutive
  name: Руководитель
  prefix: Рук.

- type: rank
  id: RMCRankWeYaJuniorExecutive
  name: Младший руководитель
  prefix: Млад. рук.
