using System.Numerics;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._CCM.Vehicle.Attachables.UI;

[GenerateTypedNameReferences]
public sealed partial class VehicleAttachableHolderStripMenu : FancyWindow
{
    private readonly Dictionary<string, VehicleAttachableSlotControl> _attachableSlotControls;

    public VehicleAttachableHolderStripMenu()
    {
        RobustXamlLoader.Load(this);
        _attachableSlotControls = new Dictionary<string, VehicleAttachableSlotControl>();
    }

    public void UpdateMenu(Dictionary<string, (string? attachableName, bool locked)> attachableSlots, Action<string> onPressed)
    {
        foreach (var slotId in attachableSlots.Keys)
        {
            if (!_attachableSlotControls.ContainsKey(slotId))
                AddSlotControl(slotId, onPressed);

            _attachableSlotControls[slotId].Update(
                attachableSlots[slotId].attachableName,
                attachableSlots[slotId].locked);
        }
    }

    private void AddSlotControl(string slotId, Action<string> onPressed)
    {
        var slotControl = new VehicleAttachableSlotControl(slotId, onPressed);
        VehicleAttachablesContainer.AddChild(slotControl);
        _attachableSlotControls.Add(slotId, slotControl);
    }

    private sealed class VehicleAttachableSlotControl : Control
    {
        private readonly Button _attachableButton;
        private readonly string _slotId;
        private readonly Action<string> _onPressed;

        public VehicleAttachableSlotControl(string slotId, Action<string> onPressed)
        {
            _slotId = slotId;
            _onPressed = onPressed;

            var slotLabel = new Label
            {
                Text = Loc.GetString(slotId) + ':',
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center,
                MinSize = new Vector2(120, 0)
            };

            var icon = new TextureRect
            {
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MaxSize = new Vector2(24, 24),
                Margin = new Thickness(5, 0, 5, 0)
            };

            _attachableButton = new Button
            {
                Text = Loc.GetString("ccm-vehicle-attachable-holder-strip-ui-empty-slot"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Stretch,
                StyleClasses = { StyleBase.ButtonOpenRight },
                VerticalAlignment = VAlignment.Center
            };

            var hBox = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    icon,
                    slotLabel,
                    _attachableButton
                },
                Margin = new Thickness(0, 0, 0, 5)
            };

            AddChild(hBox);

            _attachableButton.OnPressed += _ => onPressed(slotId);
        }

        public void Update(string? attachableName, bool slotLocked)
        {
            if (attachableName == null)
            {
                _attachableButton.Text = Loc.GetString("ccm-ui-attachable-holder-strip-ui-empty-slot");
                _attachableButton.Disabled = true;
                return;
            }

            _attachableButton.Text = attachableName;
            _attachableButton.Disabled = slotLocked;
        }
    }
}
