using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._CCM.Vehicle.Attachables.UI;

[GenerateTypedNameReferences]
public sealed partial class VehicleAttachableHolderChooseSlotMenu : FancyWindow
{
    private readonly Dictionary<string, VehicleAttachableSlotControl> _attachableSlotControls;

    public VehicleAttachableHolderChooseSlotMenu()
    {
        RobustXamlLoader.Load(this);
        _attachableSlotControls = new Dictionary<string, VehicleAttachableSlotControl>();
    }

    public void UpdateMenu(List<string> attachableSlots, Action<string> onPressed)
    {
        foreach (var slotId in attachableSlots)
        {
            if (!_attachableSlotControls.ContainsKey(slotId))
                AddSlotControl(slotId, onPressed);
        }
    }

    private void AddSlotControl(string slotId, Action<string> onPressed)
    {
        var slotControl = new VehicleAttachableSlotControl(slotId, onPressed);
        SlotsContainer.AddChild(slotControl);
        _attachableSlotControls.Add(slotId, slotControl);
    }

    private sealed class VehicleAttachableSlotControl : Control
    {
        public VehicleAttachableSlotControl(string slotId, Action<string> onPressed)
        {
            var button = new Button
            {
                Text = Loc.GetString(slotId),
                StyleClasses = { StyleBase.ButtonOpenBoth },
                HorizontalExpand = true
            };

            var container = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 5)
            };

            var icon = new TextureRect
            {
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MaxSize = new Vector2(20, 20),
                Margin = new Thickness(5, 0, 5, 0)
            };

            container.AddChild(icon);
            container.AddChild(button);

            button.OnPressed += _ => onPressed(slotId);
            AddChild(container);
        }
    }
}
