lore-examinable-verb-text = Лор
lore-examinable-verb-disabled = Узнать больше об объекте.
rmc-lore-examinable-trimax-polarized-shades = Последняя технология TriMax - "TactOptix" одна из самых популярных продукций за этот год! Оснащены слабым бронированным стеклом, которые могут защитить от лёгких шрапнельных осколоков. Крайне популярна среди солдат на фронте а также разведчиков глубоко космоса, как военных так и независимых авантюристов, официальные источники утверждают "проверены в боях, одобрены солдатами ОПЗ!" Ходят слухи, что некоторым счастливчикам удалось выжить после выстрела лазерного оружия на близком расстоянии, хотя TriMax продолжает свою позицию "Перестаньте вставать под лазер и проверять это!"
rmc-lore-examinable-trimex-personal-shades = Рекламируются как 'TriMex', (гениальная мысль использовать Е для обхода авторских прав), подделки популярны среди независимых "авантюристов" и у тех кто хочет казаться крутым. В то время как оригинал хвастается официальной защитой от атомной вспышки, радиации и лазеров, эти дешевые подделки едва хватает на защиту от УФ-лучей. Что с той знаменитой истории об отражении лазерного оружия от оригинала? Вряд ли кто-то поверит, что с такими очками это возможно. Но, они дешевы, и их слоган что то вроде "Экономь деньги и выгляди какой крутой космический рейнджер" на удивление это существенно повышает продажи.
rmc-lore-examinable-m3-eod-pattern-heavy-armor = Эта версия брони была разработана во время войны между СССП и ОПЗ. Созданная для полевых техников, которые были назначенны саперами (EOD) во время конфликта, она предоставляет довольно эффективную бронирование для обычного морпеха. Наплечники и наколенники сделанные из пластин были значительно укреплены и модифицированы, прикрывая важные части каждой конечности. Для этой брони была разработана специальная противоосоколочная система, использовавшия ту же технологию, что и разрабатывавшийся в то же время бронежилет M70.
rmc-lore-examinable-armor-xm4-pattern-intel-armor = Совершенство от AEGIS. На броне используется система, которая работает от нескольких подключенных датчиков движения на броне, , закрепленные на нагруднике. Если подключить ее к оптическому визору то будет имитировать работу датчика движения M314, повышая это значительно повышает эффективность в разведывательных операциях для отслеживания ситуации. Сейчас активно участвует в испытаниях на разведывательных миссиях или специально выделенных лабораторий.
rmc-lore-examinable-thirteen-loko = Редкий продукт на рынке, Thirteen Loko — земной продукт. Такое название было придумано из-за стериотипа, что данный напиток будут пить только безумцы. Энергетик приобрёл известную не в лучшем свете репутацию, а после фанбазу. После многочисленных судебных исков и разбирательств на  Viteztvi, яд кобры был убран из рецепта, что сильно разочаровало потребителей напитка.
rmc-lore-examinable-boda = созданная ещё в 3000 году, реклама кампании BODA изначально была попыткой СССП завоевать сердца и умы колонизаторов по всему космосу. Вскоре после этого везде начали появляться бирюзовые торговые автоматы BODA, а большие запасы данного напитка стали появляться на складах ОПЗ без прямых поставщиков. Несмотря на предостережения, после многочисленных экспериментов и исследований, которые выяснили, что продукция BODA безопасна для употребления, а также удивительно популярна, неизвестный излишек BODA был одобрен к использованию на колониях, ассоциируемые с ОПЗ. Впоследствии он пользовался популярностью, прежде чем пропасть в безвестность в далекие десятилетия, когда запасы все больше и больше истощались.
rmc-lore-examinable-red-hot-bottle = предпологается что соус создавался как что то среднее между кетчупом и острым перцем, соус получил невероятную популярность и признание OOH, после этого он часто начал появляться не только на колониях, но ещё и на космических кораблях. Неожиданная популярность и признание любопытно совпало с закрытием первого оригинального соуса "ULTRA". Совпадение?
rmc-lore-examinable-pitchblende = Колонии по всех галактике добывают урановую руду, она используется для питания устаревших ядерных реакторов, позже началась военная программа, где урановую руду начали использовать в бронебойных боеприпасах, исследовательская группа нанятая VI подтвердило, что вред от излучаемой радиации "незначителен" и безопасен для человека.
rmc-lore-examinable-bottle-of-bone-gel = Костный гель - биологический аналог кости с использованием крепкой специальной глины, костный гель может излечить как лёгкие переломы, так и тяжёлые. Костный гель не стоит использовать для лечения костного мозга, это может привести к... Не самому приятному результату. Черезмерное использование данного геля приводит к ухудшению иммунитета, прочности природных костей а также нехватке кальция.
rmc-lore-examinable-fountain-pen =
     "это больше, чем просто канцелярия, она получила признание и авторитет внутри ККМП ОПЗ, такая элитная ручка выдаётся исключительно старшему командному составу корпуса, является престижем и статусом, а в руках знаком хорошего командира.
     AEGIS известен своими разработками и исследованиями в области вооружения, но ручка это нечто оссобеное. Они сохранили все свои принципы для разработки этой ручки. Элегантность и эффективность главное составляющее, словно хорошее оружие - не требует многого, но эффективно во всех ситуациях.
    Золото используется на ручке для придания не только элегантности, но и прочности, проффесианальнальный сплав металла и золота, крепление и составляющее, это символизирует офицеров ККМП ОПЗ. Проффесианализм и прочность с предачей элегантности.
    Ручка имеет у себя многофункциональную систему смены цвета, на основе системы наведения вооружения - ручка использует специально разработанный механизм подачи разных чернил в стержень, при этом нарушение механизме не может повредить общей работе ручки.
    Цвета чернил выбраны в соответствии с различными структурами и званиями ККМ ОПЗ, также есть особо яркие цвета для подчеркивания важного текста, что позволяет писать не только эффективно, но и в соответствии с своей структурой и должностью.
     Несмотря на роскошный и дорогой вид ручки, это не мешает также быть ей эффективной, ручка имеет крепкое металлическое покрытие, длинный стержень и долговечность конструкции, сплавы металлов корпуса не ржавеют и не повержены коррозии. Это учитывает все сложные ситуации - данный ручки эффективны для огромного объема работ для высших офицеров ОПЗ, а также полевых командиров.
     Роскош, элегантность и эффективность это слияние личностей упорных лидеров в лице офицеров ККМ ОПЗ, это настоящая награда и наследие, AEGIS утверждает - это не просто ручка. Это сердца и мужества армии ОПЗ, переданные в канцелярию. Это награда и реликвия. Хотя конкуренты  AEGIS утверждают, что огромные речи и рекламная кампания созданы для поднятия авторитета и стоимости ручек."
rmc-lore-examinable-s5-red-dot-sight = Многофункциональный погодный прицел S5 оснащен специальными линзами, которые способны приглушать слишком яркий свет для эффективности, а также устойчив к погодным условиям, настоящая гениальная мысль военных инженеров и снайперов, до того как узнаешь, что это гражданский вариант с наклеенной эмблемой армии ОПЗ. Использует обозначение AN/PVQ-64 Dot Sight
rmc-lore-examinable-s6-reflex-sight = Рефлекторный прицел, простой в своей системе, громоздкий и сделан для долгой службы, используется для более сложных и ограниченных военных расчётах, совместим с многими рельсовыми системами и устанавливается почти на все вооружение. использует обозначение AN/PVG-72 Reflex Sight
rmc-lore-examinable-s8-4x-telescopic-scope = Телескопический прицел S8 одна из самых простых, долговечных и эффективных моделей прицелов, примерная максимальная дальность 780 м с использованием 10.24 мм патронов. Что в общем неплохо для данного прицела. Сделан  организацией Armat и носит обозначения AN/PVQ-31 4x Optic.
rmc-lore-examinable-s4-2x-telescopic-mini-scope = Мини прицел AN/PVQ-45 (2x). Идеален для боя на ближних и средних дистанциях. Первая партия страдала нарушением прицелов в горячих точках — не ленитесь проверять оборудование. Использует обозначение AN/PVQ-45.
rmc-lore-examinable-b8-smart-scope = Баллистический прицел B8 - умный прицел с системой "свой-чужой". AEGIS уверяет, что косяки с несрабатыванием системы были исправлены. Все равно, большинство корпусов ККМ все ещё требуют диагностику после операций. Использует обозначение XAN/PVG-110
rmc-lore-examinable-laser-sight = Базовый лазерный целеуказатель AN/PEQ-42.
rmc-lore-examinable-xm-vesg-1-flamer-nozzle = Насадка-огнемёт "Генератор экзотермических сфер" для М34. По задумке должен — запускать напалмовые шары в укрепления врага. По факту шар разрывает встречным потоком. Зато в увольнительную офицеров или высокопоставленных чинов из этой штуки палят как из фейерверка.
rmc-lore-examinable-sasos = A cutting-edge IFF-enabling optic, designed and produced for the L91 Support Weapon System, and designated the L91O1 Small Arms Smart Optical Sight - though RCM marksmen affectionately refer to it as "the Sauce". While the production model is widely regarded by its operators as an essential part of the L91 SWS, early prototypes were dangerously unreliable and widely decried by its testers, leading only to limited adoption by RCM marksmen, with many continuing to use standard 2x or 4x optics.
rmc-lore-examinable-hjra-12-extreme-intensity-incendiary-rocket = Ракета с зажигательной смесью "R-189" от СССП. Должна прожигать бункеры, но на боевых операциях ранит союзные войска — отменен из-за трудностей в эксплуатации а также сложном применении, но все еще может использоваться в некоторых корпусах СССП.
rmc-lore-examinable-ar10-assault-rifle = AR10 от Armalite (с 2709 года — собственность Viteztvi). Дитя 1950-х, первая в мире серийная винтовка с газоотводной автоматикой. Всего выпустили тысяч десять, и на вооружение её приняли только Португалия с Суданом. С конца XX века эти раритеты (вместе с массовыми M16 и AR15) кочуют по самым глухим уголкам космоса. В джунглях и на окраинах колоний до сих пор звенят их гильзы, ибо на сегодня одна единица стоит чуть ли не копейки.
rmc-lore-examinable-m54c-ap-magazine = В этих бронебойных патронах используется не бронированный наконечник, это сделало его легче, быстрее и пробивнее, но компенсировано меньшим уроном.
rmc-lore-examinable-xm-88-heavy-rifle = Разработана инженерами War Technologies по заказу ОПЗ — для борьбы со "стальными тварями". Встроенная ЭВМ, датчики и автомат запядае бьют по одному месту, расшатывая броню. Партию XM88 погрузили на один из кораблей ККМП ОПЗ перед совместной с авианосцем СССП "Армада" операцией "Кузнечик".
rmc-lore-examinable-type-64-submachine-gun = Type 64 — универсальный инструмент. Он есть не только у силовых регулярных структур СССП, но и у революционеров, корпоративных охранников и наемников.
rmc-lore-examinable-smart-gun =
    The ML66A smart gun system was designed to provide UNMC squads with the mobile heavy firepower and raw lead-spitting capacity proven necessary on the modern battlefield. It utilizes groundbreaking technologies originating from Aegis Armaments research and development to rapidly identify its targets in the field, and allows the user to target, or ignore, specific IFF frequencies on the fly.
    UNMC models are hard-wired to the IFF frequencies used by marine forces, as to avoid friendly fire incidents, and streamline use for the smart gunner in the heat of battle. Additionally, it has several motion tracking sensors built into the gun and accompanying rig able to relay any motion it detects straight to the user's HUD, allowing for even faster target acquisition.
    Although more advanced smart guns exist, the ML66A has proven to be the perfect balance of affordability and capability for a large scale military such as the UNMC. Research on the IFF technologies required for the smart gun took several decades to complete, an endeavor partially funded by the UN to ensure it was the first nation to get its hands on the promising new technology. Although, the TSE quickly secured its own variants for use with the Royal Crown Marines.
rmc-lore-examinable-m54c-mk2 =
    The Aegis Armaments M54C Mk2 is the ubiquitous standard issue rifle in the UNMC, and the embodiment of a true space age rifle. The M54 platform was built off of decades of field experience fighting in the newly discovered and varied environments the greater universe had to offer. Withstanding the environments of earth was no longer enough; a true space age rifle had to withstand the extremes of space.
    The platform dominated in UNMC trials thanks to its innovative design and caseless ammunition usage. The UNMC quickly ordered a large production run of M54C Mk1s to get field feedback before committing to a new standard issue rifle. While still effective, after extended use the flaws of the Mk1 were clear; a lack of modularity combined with bulky magazines contributed to an overall lackluster performance. Aegis, not wanting to lose the contract, swiftly came up with the Mk2.
    The M54C Mk2 improves upon the Mk1 mainly in its attachment compatibility. While the Mk1 lacked a standardized attachment mounting system, the Mk2 supported nearly every standard attachment mounting system employed by the UNMC. Additionally, the larger bulky magazines of the Mk1 were exchanged for smaller and more ergonomic magazines, improving reload times and ammunition storage efficiency.
    Because of its effectiveness within the marine corp, the M54C Mk2 has seen adoption by several PMC groups, and even some colonial riot response teams. Its modularity and easily replaceable parts make it extremely adaptable to any given organization's needs, as well as allowing the average soldier to perform even advanced maintenance.
rmc-lore-examinable-ssg-45 =
    Developed in response to persistent complaints from Weston Yamada’s internal security and PMC divisions, the SSG45 is a direct result of field dissatisfaction with the UNMC-standard M54C Mk2.
    While the M54C was lightweight and easy to mass-produce, it lacked the stopping power and durability required for the kind of off-grid, high-intensity operations typically assigned to WeYa corporate teams.
    Several units began modifying their standard-issue rifles into custom variants, unofficially dubbed M54C/2s, to improve handling, penetration, and reliability. These field modifications drew enough attention that Weston Yamada’s R&D division launched a formal weapons program to design a purpose-built rifle based on actual combat feedback.
    The result was the SSG45: a heavy-caliber, caseless assault rifle designed for harsh environments and close-quarters superiority. It features an integrated recoil mitigation system, hardened internal components, and support for smart optics and upgraded attachments. Though still technically in field testing, the SSG45 has seen wide adoption across multiple WeYa security teams operating in high-threat zones.
    Reports suggest the rifle performs well in sustained engagements, with only minor overheating issues during prolonged automatic fire. The R&D team is already addressing these issues in ongoing iterations.
rmc-lore-examinable-un-flag =
    The United Nations. The most prosperous nation in the universe. Through trials and tribulations, insurgencies and wars, the United Nations has united the people of earth, the people of the galaxy, all together under one banner. This banner.
    This is a nation worth dying for. You will triumph, you will fail, you will live, and you will die, but this flag will stand through it all. Glory to the United Nations.
rmc-lore-examinable-ceremonial-sabre =
    Standard issue to commanding officers of the United Nations Marine Corps, the ceremonial sabre is more than a relic, it’s a rite. Forged from composite alloy and polished to a mirror gleam, each sabre is engraved with the Marine’s name and unit upon promotion to command.
    While primarily used in formal ceremonies and change-of-command rituals, the blade is combat-capable, a silent reminder that in the UNMC, even tradition draws blood when necessary.
    Veteran officers are known to carry their sabres into battle, not for the weapon’s edge, but for what it represents: unwavering leadership in the unforgiving cold dark void of space. The sabre’s design dates back to the Old Earth naval traditions, carried forward into the stars with grim pride.
    Some say that if you die with it in your hand, your name is forever etched deeper into UNMC history.
rmc-lore-examinable-fax-machine =
    The fax machine, although of archaic origin, is surprisingly apt to the modern spacefaring nations of today.
    It utilizes the preexisting groundbreaking interstellar phone system to transmit documents as audio signals, which can then be decoded into the original document at the receiving fax machine.
    Weston-Yamada has patented the technology, resulting in other models of fax machines being far slower, and far less common.
    Security concerns have been raised as to the security of using the telephone system for sensitive documents, but Weston-Yamada has promised their infrastructure is extremely secure.
rmc-lore-examniable-orbital-cannon =
    After repeated use of nuclear weapons during UNMC operations involving civilian colonies resulted in both unnecessary civilian casualties and long term ecological disasters in affected areas, the UNMC determined an intermediate weapon between conventional artillery and nuclear explosives was necessary to avoid further nuclear incidents and public ill-will.
    Several companies offered various prototypes to help solve this issue, including anti-ship missiles modified to target laser designations on the ground, and large low altitude conventional bombs intended to be delivered via a standard AUD-25 dropship. In the end, the UNMC decided Aegis Armament’s proposal to be most practical; a large, 400mm ship mounted artillery cannon designed to fire a variety of specially made ammunition.
    A vast majority of troop carrying UNMC starships were outfitted with these cannons, giving each and every marine company the capability of orbital bombardment. After widespread success in the field, several new models of orbital cannon were created to address a few major concerns with the weapon, namely the concerningly high rate of blue on blue incidents.
    Most notably, new models of Aegis orbital cannons are able to effectively target and fire both laser and precision GPS guided shells, vastly increasing the accuracy and reducing the risk of friendly fire. Unfortunately, these new models have yet to reach the poorly funded frontier fleets, and friendly fire incidents involving orbital bombardments are all too common.
rmc-lore-examinable-ssg45 = Стреляет безгильзовыми 7x62мм. По боеспособности и экономичности превосходит M54C MK2, не теряя эффективности в тесных пространствах. Предприниматели из Viteztvi быстро разочаровались в М54К — особенно на дальних расстояниях, где важна точность и мощь. Их КБ ответило созданием SSG, заточенного под их нужды.
rmc-lore-examinable-lady-fingers = Дерзкий маркетинговый ход - жёсткие ментоловые сигареты без фильтра в упаковке цвета завявшей розы. Аудитория и любители — женщины морпехи. Запах такой, что в полевых условиях эти "Пальцы дамы" иногда работает как репеллент от насекомых. В вендинговых автоматах они пылятся чаще, чем их покупают. Будто ждут смельчака, который решится их попробовать. А нравятся ли они вообще кому-нибудь — большой вопрос.
rmc-lore-examinable-kierland-electro-golds = Эти сигареты прославились ещё на стройке станции "Novaris". Зажигаются от одной искры, горят ровно, тяга — стабильная. Немудрёный,  вкус пыли быстро сделал их культовыми в колониях. Позже Kierlan развернул производство на аграрных планетах у границы и заключил эксклюзивный контракт на поставки для ККМ.
rmc-lore-examinable-emerald-greens = Их цена ниже бутылки воды, их состав это тайна, которую никто не знает, их вкус это то о чем ты думаешь в последний момент.
rmc-lore-examinable-boots-07 = Описывает как комплект брони B18 сделает из морпеха неубиваемого, а также как командный состав много поставили на эффективность этой брони.
rmc-lore-examinable-boots-45 = Первая половина — базовые правила ухода за служебным оружием, а также реклама известного оружейника со станции "Врата". Вторая — инструкция, в каких позах заснуть морпеху, держа пистолет под подушкой.
rmc-lore-examinable-boots-58 = Древний репортаж о том, как ветераны первой развед роты СОиС воюют в джунглях с отрядами СССП и партизанами.
rmc-lore-examinable-boots-113 = Рассказывается о жестокости восстания на Ксибу, местные обитатели отказались попадать под юрисдикцию корпораций, в конечном итоге это привело к вооруженным нападениям поселенцев, где пришлось вмешаться ОПЗ, упоминается о некоторых танкистах и об каком-то отряде спецназа, также эта операция одна из первых, где было использовано орбитальное оружие.
rmc-lore-examinable-boots-150 = Основные части посвящены продовольственнвым кризисом войск СССП, где  их ИРП нестандартные и производиться в самых дальних и странных местах этого мира. Поэтому в продовольственнвых ящиках можно найти что угодно!  От печенки и столетних яиц до лютефиска, маринованного свиного рыла, консервированного рубца и вяленой свеклы, ужас!
rmc-lore-examinable-orrery-65 = Первая часть какая история, где какая-то важная шишка отправила какой отчёт не туда.  Дальше — словесная перепалка двух колониальных корпоратив где строить новейшую колонию  Mu Arae. Один — за газовый завод на орбите гиганта, другой — за зеленый агромир. В середине дискуссия скатывается на базар, оппоненты начинают поливать друг друга оскорблять, а потом... Все, что после — зачёркнуто цензурой.
rmc-lore-examinable-orrery-175 = Главная тема - ОПЗ и Viteztvi создали абсолютно новую линейку флота, мало того что этот новый корабль не убиваем, так ещё и может стирать колонии, мегаполисы а может и планеты одним выстрелом, инженеры ОПЗ вместе с инженерами Viteztvi в основном говорят мало, но вы часто видите слова "рельсатрон, турели, ракеты", интересно, вас туда отправят?.
rmc-lore-examinable-orrery-34 = A large portion of this issue is dedicated to wide-assortment of different clothing options which are currently in-style for Weston-Yamada executives across the galaxy by region. It displays the clothing choices of the inner rim to be somewhat conspicuous, but stylish and attractive. Sleek suits with price tags in the quadruple digits dominate much of this section, along with snappy ties. However, closer to the frontier the common choices branch out, from thick jackets able to rebuff cold fronts with ease, to fashionable shorts able to keep hard-working executives cool in sweltering climates. The article also mentions R&D's efforts towards redefining and improving the classic 'We-Ya Stompers'.
rmc-lore-examinable-orrery-202 = The main focus of this issue is on Weston-Yamada's synthetic programm specifically how the rollout of Generation 3 synthetics has been massively successful by all accounts. It contrasts the flaws of the previous Generation 2s, such as their somewhat fragile build, as well as their habit of suffering malfunctions with the advancements made by the Generation 3 program which claims to amend the afformentioned issues, raising the bar for future synthetic projects. It also explains how the rollout has increased WEYA's stock price by 4%, and that many nations and organizations have invested in Gen 3 synths, such as the TSE, UN, and policing agencies such as the CMP and TSEPA.
rmc-lore-examinable-orrery-217 = This issue focuses on Weston-Yamada's Silverguard Private Military Company assets, such as AZURE-15. Deployed to various zones to secure, protect, or acquire corporate assets, these mercenaries work entirely on Weston-Yamada's payroll, and are trained and provided with gear on the level of many formal militaries. Weapons such as the SSG-45 and M80 are mentioned, as well as state-of-the-art armour. It goes on to discuss the success of PMC deployment in putting down CLF agitator cells, as well as making sure WEYA's assets are secure from hostile forces. Midway through the magazine, a smaller article talks about the potential demotion of a Special Services Executive Supervisor after they failed to disclose a large-scale industrial accident they oversaw to their superiors.
rmc-lore-examinable-orrery-220 = Much of this issue is centered on recent issues faced by Weston-Yamada's Logistics Division, specifically on the frontier in Zypheron. It speaks of how recent tensions between the UN/TSE and SPP, as well as riots caused by the CLF have impacted the Company's supply chain, such as increased cost of consumer goods, as well as the reduced number of viable ports for restock and refuel. However, it does discuss current plans to fix this issue and minimize costs, such as constructing additional supply depots in key locations, such as OCP-583, and deepening trade tides with Stakeholder organizations such as the UN and TSE. It also discusses the newest options in bulk transport vessels, able to freight fifty-thousand shipping containers across the galaxy.
rmc-lore-examinable-orrery-258 = This issue discusses the efforts made to establish a colony in the mid-rim, on the temperate world of LV-676. Initially scouted as a possible colony location, it was only in recent times that plans to colonize the planet were considered. Following a 2102 Shareholder meeting, Weston-Yamada Special Services were given the go ahead to begin colonization. Initially consisting of 234 personnel and 2 synthetics, they staked their claim, and named the planet 'Fort Denst'. Initial efforts proved difficult; challenging terrain, broken water purifiers, and heavy winds resulted in casualties and injuries. However, the people of Fort Denst held on and persevered; nowadays, the colony hosts a population of 1430 personnel, and is famed for its cheese exports.
rmc-lore-examinable-weya-windbreaker = A result of a 7-year R&D program, this windbreaker features advanced temperature regulation, comfortable design, and a hydrophobic exterior, making it perfect for almost all weather. Unfortunately, nobody thought to give it a hood.
rmc-lore-examinable-atmospheric-composition-scanner = A handheld piece of heavy-duty equipment able to collect information about the local atmospheric data and information using advanced tech which WEYA R&D is keen on keeping secret. Utilized across the galaxy for a multitude of purposes, such as searching for gas leaks, ensuring terraforming efforts are making progress, and gathering scientific data on exoplanet environs. This device has seen use with WEYA, TSE, and UN since 2078 with very few changes, and is renowned for it's reliability, especially in harsher conditions.
rmc-lore-examinable-spp-survival-ration = Mass produced as emergency rations, they are available in abundance anywhere in the Progressive Peoples, and are packed with nutritional additives. They are commonplace in the diets of many citizens of the Peoples who eat them out of convenience in place of more flavourful nutrient bars, or as nutritional additives to dishes. Despite popular myths in the UN, they are not the standard MRE of the SPP's Naval Infantry, but are utilized in scenarios where the actual MRE supply has been depleted, as one would expect of survival food.
rmc-lore-examinable-m13-extended-recoil-compensator = A limited-production muzzle device developed by AEGIS Armaments. The compensator channels muzzle gases to counteract recoil and slightly increase bullet velocity through focused pressure, marginally improving ballistic performance.
rmc-lore-examinable-orrery-184 = Спецвыпуск о разработках Viteztvi допущенный главным дивизионным акционером, вы видите бледнер UY-21 (в этот раз не перегревается и не взрывается!), ручной лазерный резак, который режет металы и пласталь как масло нож, а также ПЗРК "Тайфун" для боевых частей Viteztvi, вы замечайте купон на середине страницы - "купи один - получи второй в подарок!", этот на ящик пива, он просрочен.
