using System.Numerics;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRoleInfoBox : BoxContainer
    {
        [Dependency] private readonly IEntityManager _entityManager = default!;
        [Dependency] private readonly IPlayerManager _playerManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IUserInterfaceManager _uiManager = default!;

        private EntityUid? _previewDummy;

        public GhostRoleInfoBox(string name, string description, NetEntity entity, string? entityPrototype, string? jobPrototype)
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Title.Text = name;
            Description.SetMessage(description);
            PreviewFrame.AddChild(CreatePreview(entity, entityPrototype, jobPrototype, name));
        }

        public void AddButtons(Control buttons)
        {
            ButtonHost.AddChild(buttons);
        }

        private Control CreatePreview(NetEntity entity, string? entityPrototype, string? jobPrototype, string fallback)
        {
            if (_entityManager.TryGetEntity(entity, out var uid) &&
                _entityManager.HasComponent<SpriteComponent>(uid.Value) &&
                GhostPreviewHelper.CanUseLiveSprite(_entityManager, _playerManager, uid.Value))
            {
                return CreateSpritePreview(uid.Value);
            }

            if (_entityManager.TryGetEntity(entity, out uid) &&
                GhostPreviewHelper.TryCreateJobPreviewDummy(
                    _uiManager,
                    _prototypeManager,
                    _entityManager,
                    uid.Value,
                    jobPrototype,
                    fallback,
                    out var dummy))
            {
                _previewDummy = dummy;
                return CreateSpritePreview(dummy);
            }

            if (!string.IsNullOrWhiteSpace(entityPrototype))
            {
                var preview = new EntityPrototypeView
                {
                    SetSize = new Vector2(60, 60),
                    Stretch = SpriteView.StretchMode.Fit,
                    Scale = new Vector2(1.15f, 1.15f),
                };
                preview.SetPrototype(entityPrototype);
                return preview;
            }

            return new Label
            {
                Text = string.IsNullOrWhiteSpace(fallback)
                    ? "?"
                    : fallback[0].ToString().ToUpperInvariant(),
                Align = Label.AlignMode.Center,
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                MinSize = new Vector2(60, 60),
                Modulate = Color.FromHex("#A6BECD"),
            };
        }

        private static SpriteView CreateSpritePreview(EntityUid uid)
        {
            var preview = new SpriteView
            {
                SetSize = new Vector2(60, 60),
                OverrideDirection = Direction.South,
                Stretch = SpriteView.StretchMode.Fit,
                Scale = new Vector2(1.15f, 1.15f),
            };
            preview.SetEntity(uid);
            return preview;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (!disposing || _previewDummy is not { } dummy)
                return;

            _entityManager.DeleteEntity(dummy);
            _previewDummy = null;
        }
    }
}
