using System.Linq;
using System.Numerics;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRolesWindow : DefaultWindow
    {
        public event Action<GhostRoleInfo>? OnRoleRequestButtonClicked;
        public event Action<GhostRoleInfo>? OnRoleFollow;

        private readonly List<EntryState> _entries = new();
        private string _searchText = string.Empty;
        private int _availableRoleCount;
        private int _previousAvailableRoleCount;
        private bool _updatingEntries;

        public GhostRolesWindow()
        {
            RobustXamlLoader.Load(this);
            SearchBar.OnTextChanged += OnSearchTextChanged;
        }

        public void ClearEntries()
        {
            _availableRoleCount = 0;
            _entries.Clear();
            EntryContainer.DisposeAllChildren();
            if (!_updatingEntries)
                UpdateVisibleEntries();
        }

        public void SaveCollapsibleBoxesStates()
        {
        }

        public void RestoreCollapsibleBoxesStates()
        {
        }

        public void AddEntry(string name, string description, bool hasAccess, FormattedMessage? reason, IEnumerable<GhostRoleInfo> roles, SpriteSystem spriteSystem)
        {
            var ghostRoleInfos = roles.ToList();
            if (ghostRoleInfos.Count == 0)
                return;

            _availableRoleCount += ghostRoleInfos.Count;
            var info = new GhostRoleInfoBox(
                name,
                description,
                ghostRoleInfos[0].Entity,
                ghostRoleInfos[0].EntityPrototype,
                ghostRoleInfos[0].JobPrototype);
            var buttons = new GhostRoleButtonsBox(hasAccess, reason, ghostRoleInfos, spriteSystem);
            buttons.OnRoleSelected += OnRoleRequestButtonClicked;
            buttons.OnRoleFollow += OnRoleFollow;
            info.AddButtons(buttons);

            EntryContainer.AddChild(info);
            _entries.Add(new EntryState(info, $"{name} {description}"));
            if (!_updatingEntries)
                UpdateVisibleEntries();
        }

        public void BeginEntryUpdate()
        {
            _previousAvailableRoleCount = _availableRoleCount;
            _updatingEntries = true;
            ClearEntries();
        }

        public void EndEntryUpdate()
        {
            _updatingEntries = false;
            UpdateVisibleEntries();

            if (_availableRoleCount != _previousAvailableRoleCount)
                RoleScroll.SetScrollValue(Vector2.Zero);
        }

        private void UpdateVisibleEntries()
        {
            CountLabel.Text = Loc.GetString("ghost-roles-window-available-count", ("count", _availableRoleCount));

            var anyVisible = false;
            foreach (var entry in _entries)
            {
                var visible = string.IsNullOrWhiteSpace(_searchText) ||
                              entry.SearchText.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
                entry.Control.Visible = visible;
                anyVisible |= visible;
            }

            ContentPanel.Visible = anyVisible;
            NoRolesMessage.Text = _availableRoleCount == 0
                ? Loc.GetString("ghost-roles-window-no-roles-available-label")
                : Loc.GetString("ghost-roles-window-no-results-label");
            NoRolesMessage.Visible = !anyVisible;
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;
            UpdateVisibleEntries();
        }

        private readonly record struct EntryState(Control Control, string SearchText);
    }
}